/**
 * Fachdatenbank – Gastechnik: Gasinstallation, Prüfungen, Geräte,
 * Verbrennungsluft, Abgasanlagen und Flüssiggas.
 */

export const GAS = [
  {
    id: 'gasinstallation',
    begriff: 'Gasinstallation (TRGI)',
    bereich: 'gas',
    kategorie: 'Anlage',
    synonyme: ['Gasleitung', 'TRGI', 'G 600', 'Gasrohr', 'Gasleitungsanlage'],
    kurz: 'Die DVGW-TRGI G 600 regelt Planung, Errichtung, Änderung und Instandhaltung von Gasleitungsanlagen in Gebäuden.',
    funktion:
      'Die Gasleitung beginnt hinter der Hauptabsperreinrichtung und endet an den Geräteanschlüssen. Zulässig sind Stahl, Kupfer, Edelstahl und – in engen Grenzen – Mehrschichtverbundrohr für Anschlussleitungen; die Verbindungstechnik ist werkstoff- und systemabhängig geregelt. Arbeiten an Gasanlagen dürfen nur Unternehmen ausführen, die beim Netzbetreiber im Installateurverzeichnis eingetragen sind. Jede neue oder geänderte Anlage wird vor Inbetriebnahme geprüft und in Betrieb genommen.',
    aufbau: [
      'Hauptabsperreinrichtung (HAE), Gasdruckregler und Gaszähler',
      'Verteilungsleitungen im Gebäude mit Absperrarmaturen',
      'Gasströmungswächter (GS) in der Verteilung',
      'Geräteanschlussarmatur mit thermisch auslösender Absperreinrichtung (TAE)',
      'Anschluss der Geräte über feste Leitung oder Sicherheitsgasschlauch',
    ],
    einsatz: ['Wohngebäude mit Erdgasversorgung', 'Gewerbliche Gasverwendung', 'Umstellung, Erweiterung und Instandsetzung im Bestand'],
    hinweise: [
      'Kupfer in Gasleitungen wird hartgelötet oder mit zugelassenen Pressfittings (HNBR-Dichtung, gelb gekennzeichnet) verbunden.',
      'Gasleitungen nicht als Erder verwenden, aber in den Potentialausgleich einbeziehen.',
      'Leitungen in Schächten, Hohlräumen und Fluchtwegen nur nach den besonderen Anforderungen der TRGI verlegen.',
      'Keine Gasleitung in Aufzugsschächten, Lüftungsleitungen oder Aufzugstriebwerksräumen.',
      'Nicht mehr genutzte Leitungen fachgerecht stilllegen: trennen, entleeren, dicht verschließen.',
    ],
    werte: [
      'Nenndruck Niederdruck-Hausanschluss: 20 bis 23 mbar (Erdgas E/H)',
      'Zulässiger Druckverlust in der Leitungsanlage: 1,3 mbar bei Niederdruck',
      'Heizwert Erdgas H: etwa 11 kWh/m³ · Erdgas L: etwa 9,8 kWh/m³',
    ],
    normen: ['DVGW-TRGI G 600 (2018)', 'DIN EN 1775', 'NDAV', 'DVGW G 459 (Hausanschluss)'],
    verwandt: ['gaspruefung', 'gasgeraete', 'gasstroemungswaechter', 'verbrennungsluft', 'gasgeruch'],
  },
  {
    id: 'gaspruefung',
    begriff: 'Prüfungen an Gasleitungen',
    bereich: 'gas',
    kategorie: 'Verfahren',
    synonyme: ['Belastungsprüfung', 'Dichtheitsprüfung Gas', 'Gebrauchsfähigkeitsprüfung', 'Leckmengenmessung'],
    kurz: 'Neue Gasleitungen werden mit Luft belastet und auf Dichtheit geprüft; im Bestand wird die Gebrauchsfähigkeit über die Leckmenge beurteilt.',
    funktion:
      'Die Belastungsprüfung weist die Festigkeit der Leitung nach und erfolgt vor dem Einbau von Armaturen und Geräten mit Luft oder Inertgas bei 1 bar. Die Dichtheitsprüfung erfolgt anschließend an der fertigen Leitung ohne Geräte bei 150 mbar; der Druck darf während der Prüfzeit nicht abfallen. Bei bestehenden, in Betrieb befindlichen Anlagen wird stattdessen die Gebrauchsfähigkeit über die Leckmenge in Litern je Stunde bestimmt.',
    aufbau: ['Prüfgerät mit U-Rohr- oder elektronischem Manometer', 'Absperrungen und Stopfen', 'Leckmengenmessgerät für die Gebrauchsfähigkeitsprüfung', 'Prüfprotokoll'],
    einsatz: ['Neuinstallation und Erweiterung', 'Nach Instandsetzung', 'Wiederkehrende Prüfung im Bestand'],
    hinweise: [
      'Vor der Prüfung Temperaturausgleich abwarten – Temperaturänderungen verfälschen das Ergebnis erheblich.',
      'Geräte und Armaturen mit geringerem zulässigem Druck abtrennen.',
      'Prüfergebnisse immer protokollieren und dem Betreiber übergeben.',
      'Bei nicht gebrauchsfähigen Anlagen sofort stilllegen und den Betreiber schriftlich informieren.',
    ],
    werte: [
      'Belastungsprüfung: 1 bar Luft, Prüfdauer 10 Minuten (nach Angleichzeit)',
      'Dichtheitsprüfung: 150 mbar Luft, Prüfdauer je nach Leitungsvolumen – bis 100 Liter mindestens 10 Minuten',
      'Gebrauchsfähigkeit: unter 1 l/h gebrauchsfähig · 1 bis 5 l/h vermindert gebrauchsfähig (Instandsetzung innerhalb von 4 Wochen) · über 5 l/h nicht gebrauchsfähig (sofortige Stilllegung)',
    ],
    normen: ['DVGW-TRGI G 600', 'DVGW G 5952 (Gebrauchsfähigkeit)', 'DIN EN 1775'],
    verwandt: ['gasinstallation', 'gasgeruch', 'dichtheitspruefung'],
  },
  {
    id: 'gasgeraete',
    begriff: 'Gasgeräte und Gerätearten',
    bereich: 'gas',
    kategorie: 'Bauteil',
    synonyme: ['Gasgerät', 'Art A', 'Art B', 'Art C', 'raumluftunabhängig', 'raumluftabhängig'],
    kurz: 'Gasgeräte werden nach ihrer Verbrennungsluftversorgung und Abgasführung in die Arten A, B und C eingeteilt.',
    funktion:
      'Geräte der Art A haben keine Abgasleitung; die Abgase treten in den Aufstellraum (z. B. Gasherd). Geräte der Art B entnehmen die Verbrennungsluft dem Aufstellraum und führen die Abgase über eine Abgasanlage ab – sie sind raumluftabhängig. Geräte der Art C sind raumluftunabhängig: Verbrennungsluftzufuhr und Abgasabführung erfolgen über ein geschlossenes System, meist als konzentrische Leitung; der Aufstellraum bleibt unbeeinflusst.',
    aufbau: ['Brenner mit Gasarmatur und Zündsicherung', 'Wärmeübertrager', 'Abgasführung je nach Geräteart', 'Sicherheitseinrichtungen: Flammenüberwachung, STB, Abgasüberwachung'],
    einsatz: ['Brennwertgeräte (meist Art C)', 'Gasheizkessel im Bestand (häufig Art B)', 'Gasherd und Gaskochfeld (Art A)', 'Gasdurchlauferhitzer'],
    hinweise: [
      'Bei Art B ist die Verbrennungsluftversorgung des Aufstellraums nachzuweisen.',
      'Raumluftabhängige Geräte und Abluftanlagen (Dunstabzug, Wäschetrockner, kontrollierte Lüftung) im selben Raum brauchen eine Sicherheitseinrichtung, etwa einen Unterdruckwächter.',
      'Aufstellräume dürfen nicht als Lagerraum für brennbare Stoffe dienen.',
      'Gerätetausch beim Netzbetreiber anzeigen; Inbetriebnahme nur durch das eingetragene Fachunternehmen.',
    ],
    normen: ['DVGW-TRGI G 600', 'DIN EN 15502', 'Feuerungsverordnung des Landes', '1. BImSchV'],
    verwandt: ['verbrennungsluft', 'abgasanlage', 'brennwert', 'abgasmessung'],
  },
  {
    id: 'gasstroemungswaechter',
    begriff: 'Gasströmungswächter (GS)',
    bereich: 'gas',
    kategorie: 'Bauteil',
    synonyme: ['GS', 'Strömungswächter', 'Gassicherung'],
    kurz: 'Der Gasströmungswächter sperrt die Leitung selbsttätig ab, wenn ein deutlich zu großer Volumenstrom auftritt – etwa bei einem Rohrbruch.',
    funktion:
      'Ein federbelasteter Schließkörper wird vom strömenden Gas gegen die Feder bewegt. Im Normalbetrieb bleibt er in Offenstellung. Übersteigt der Volumenstrom den Nennwert deutlich – wie bei einer abgerissenen Leitung –, schließt der Körper auf dem Sitz und unterbricht die Gaszufuhr bis auf eine kleine Bypassmenge, die das Wiederöffnen nach Beseitigung der Ursache ermöglicht.',
    aufbau: ['Gehäuse mit Schließkörper und Feder', 'Kennzeichnung mit Nennvolumenstrom (z. B. GS 2,5 / GS 4 / GS 6)', 'Einbau hinter dem Zähler bzw. am Abgang der Verteilung'],
    einsatz: ['Neue Leitungsanlagen in Gebäuden', 'Nachrüstung bei wesentlichen Änderungen', 'Leitungen in Schächten und Hohlräumen'],
    hinweise: [
      'Nennvolumenstrom passend zur nachfolgenden Geräteleistung wählen – zu groß gewählt wirkt er nicht, zu klein löst er im Betrieb aus.',
      'Einbaurichtung und Einbaulage nach Herstellerangabe beachten.',
      'Nach dem Auslösen zuerst die Ursache beseitigen, dann die Anlage wieder in Betrieb nehmen.',
    ],
    normen: ['DVGW-TRGI G 600', 'DIN 3586', 'DVGW VP 305-1'],
    verwandt: ['gasinstallation', 'tae', 'gasgeruch'],
  },
  {
    id: 'tae',
    begriff: 'Thermisch auslösende Absperreinrichtung (TAE)',
    bereich: 'gas',
    kategorie: 'Bauteil',
    synonyme: ['TAE', 'thermische Absperreinrichtung', 'Brandschutzabsperrung Gas'],
    kurz: 'Die TAE unterbricht bei Brandeinwirkung die Gaszufuhr zum Gerät und verhindert, dass Gas den Brand zusätzlich speist.',
    funktion:
      'Im Bauteil sitzt ein Schmelzelement oder eine Dehnstoffpatrone. Steigt die Umgebungstemperatur über den Auslösewert – üblicherweise etwa 100 °C –, gibt das Element den federbelasteten Schließkörper frei und die Leitung wird dicht verschlossen. Die TAE ist Bestandteil der Geräteanschlussarmatur oder wird separat unmittelbar vor dem Gerät eingebaut.',
    aufbau: ['Gehäuse mit Schließkörper und Feder', 'Schmelzelement bzw. Dehnstoffpatrone', 'oft kombiniert mit Geräteanschlussarmatur und Gasströmungswächter'],
    einsatz: ['Unmittelbar vor jedem Gasgerät', 'Bei Gerätetausch nachzurüsten'],
    hinweise: [
      'Nach dem Auslösen ist die TAE zu ersetzen – sie ist nicht rückstellbar.',
      'Einbaulage und maximale Entfernung zum Gerät nach Herstellerangabe beachten.',
      'Bei Geräteanschlüssen mit Sicherheitsgasschlauch ist die TAE in der Anschlussarmatur integriert.',
    ],
    werte: ['Auslösetemperatur etwa 100 °C', 'Dichtheit nach dem Auslösen bis 100 mbar gefordert'],
    normen: ['DVGW-TRGI G 600', 'DIN 3586', 'DIN EN 1775'],
    verwandt: ['gasstroemungswaechter', 'gasgeraete', 'gasinstallation'],
  },
  {
    id: 'verbrennungsluft',
    begriff: 'Verbrennungsluftversorgung',
    bereich: 'gas',
    kategorie: 'Regelwerk',
    synonyme: ['Aufstellraum', 'Luftverbund', 'Zuluftöffnung', 'Unterdruckwächter'],
    kurz: 'Raumluftabhängige Feuerstätten brauchen eine gesicherte Zufuhr von Verbrennungsluft; sonst droht unvollständige Verbrennung mit Kohlenmonoxid.',
    funktion:
      'Für die vollständige Verbrennung von einem Kubikmeter Erdgas werden etwa zehn Kubikmeter Luft benötigt. Reicht die Luft nicht nach, sinkt der Sauerstoffgehalt, die Verbrennung wird unvollständig und es entsteht Kohlenmonoxid. Die TRGI lässt daher für raumluftabhängige Geräte entweder ein ausreichend großes Raumvolumen mit Verbindung zu weiteren Räumen (Luftverbund) oder eine Öffnung ins Freie zu. Abluftanlagen im selben Raum können den nötigen Unterdruck erzeugen, der Abgase zurück in den Raum zieht – hier ist eine Sicherheitseinrichtung erforderlich.',
    aufbau: [
      'Aufstellraum mit ausreichendem Volumen',
      'Verbrennungsluftverbund über Türen mit Lüftungsgittern',
      'Öffnung ins Freie mit definiertem freiem Querschnitt',
      'Unterdruckwächter oder Fensterkontaktschalter bei gleichzeitigem Abluftbetrieb',
    ],
    einsatz: ['Gasheizkessel Art B', 'Gasdurchlauferhitzer', 'Gasherde in kleinen Küchen', 'Räume mit Dunstabzugshaube oder Abluft-Trockner'],
    hinweise: [
      'Raumluftunabhängige Geräte der Art C sind der sicherste Weg – bei Sanierung mit dichten Fenstern praktisch immer vorzuziehen.',
      'Lüftungsöffnungen dürfen nicht verschlossen oder zugestellt werden – Betreiber darauf hinweisen.',
      'Zusammenwirken mit dem Schornsteinfeger klären; er prüft die Abgasführung und die Verbrennungsluftversorgung.',
    ],
    werte: [
      'Richtwert Raumvolumen für Geräte bis 35 kW: mindestens 4 m³ je kW Nennleistung',
      'Alternativ Öffnung ins Freie: 150 cm² freier Querschnitt bzw. zwei Öffnungen mit je 75 cm² (bis 35 kW)',
      'Luftbedarf: etwa 10 m³ Luft je m³ Erdgas',
    ],
    normen: ['DVGW-TRGI G 600', 'Feuerungsverordnung (FeuVO) des Landes', 'DIN 18017 (Lüftung)'],
    verwandt: ['gasgeraete', 'abgasanlage', 'gasgeruch', 'wohnungslueftung'],
  },
  {
    id: 'abgasanlage',
    begriff: 'Abgasanlage und Abgasleitung',
    bereich: 'gas',
    kategorie: 'Anlage',
    synonyme: ['Schornstein', 'Kamin', 'LAS', 'Abgasleitung', 'Abgasrohr', 'Abgassystem'],
    kurz: 'Die Abgasanlage führt die Verbrennungsgase sicher ins Freie; bei Brennwertgeräten muss sie feuchteunempfindlich und überdruckdicht sein.',
    funktion:
      'Abgase steigen durch Auftrieb oder werden vom Gebläse gefördert. Bei Brennwertbetrieb kühlen sie unter den Taupunkt ab, sodass ständig Kondensat anfällt – die Leitung muss deshalb feuchteunempfindlich (Kennzeichnung W) und für Überdruck geeignet sein (P bzw. H). Das Luft-Abgas-System (LAS) führt in einem konzentrischen Rohr Abgas nach außen und Verbrennungsluft von außen zum Gerät; damit arbeitet das Gerät raumluftunabhängig. Bestehende gemauerte Schornsteine werden mit Kunststoff- oder Edelstahlrohren saniert.',
    aufbau: [
      'Abgasleitung aus PP, Edelstahl oder Keramik',
      'Konzentrische Führung (LAS) oder getrennte Luft-/Abgasführung',
      'Revisionsöffnung und Messöffnung',
      'Kondensatablauf und Mündung über Dach bzw. an der Fassade nach Zulassung',
    ],
    einsatz: ['Alle Feuerstätten mit Abgasabführung', 'Kesseltausch mit Schornsteinsanierung', 'Mehrfachbelegung nach Zulassung'],
    hinweise: [
      'Nur zugelassene, zum Gerät passende Systeme verwenden; Herstellerkombination beachten.',
      'Mündungshöhe und Abstände zu Fenstern, Dachflächen und Nachbargebäuden einhalten.',
      'Vor Inbetriebnahme Abnahme durch den bevollmächtigten Bezirksschornsteinfeger.',
      'Alte Schornsteine vor Weiterverwendung auf Versottung und Querschnitt prüfen lassen.',
    ],
    werte: [
      'Kennzeichnung Brennwert: Temperaturklasse T120, Druckklasse P1/H1, Kondensatbeständigkeit W',
      'Abgastemperatur Brennwert: 40 bis 60 °C',
      'Mündung über Dach in der Regel mindestens 40 cm über der Dachfläche (landesrechtlich geregelt)',
    ],
    normen: ['DIN EN 13384 (Berechnung)', 'DIN EN 14471 / 1856', 'Feuerungsverordnung', 'DVGW-TRGI G 600'],
    verwandt: ['brennwert', 'gasgeraete', 'kondensat', 'abgasmessung'],
  },
  {
    id: 'abgasmessung',
    begriff: 'Abgasmessung und Einstellung',
    bereich: 'gas',
    kategorie: 'Verfahren',
    synonyme: ['Abgasverlust', 'CO-Messung', 'Verbrennungsanalyse', 'BImSchV', 'Einstellprotokoll'],
    kurz: 'Bei Inbetriebnahme und Wartung werden Verbrennungswerte gemessen, eingestellt und protokolliert.',
    funktion:
      'Das Messgerät bestimmt Sauerstoff- oder Kohlendioxidgehalt, Abgastemperatur, Zuglufttemperatur und Kohlenmonoxidgehalt. Aus Abgas- und Verbrennungslufttemperatur sowie dem Sauerstoffgehalt errechnet sich der Abgasverlust – er beschreibt die mit dem Abgas verlorene Wärme. Der CO-Wert zeigt die Verbrennungsqualität: Er steigt bei Luftmangel, verschmutztem Brenner oder gestörter Abgasführung stark an.',
    aufbau: ['Abgasmessgerät mit Sonde', 'Messöffnung in der Abgasleitung', 'Gasdruckmessung am Geräteanschluss', 'Einstell- und Messprotokoll'],
    einsatz: ['Inbetriebnahme neuer Geräte', 'Jährliche Wartung', 'Störungssuche bei Verbrennungsproblemen', 'Messung durch den Schornsteinfeger nach 1. BImSchV'],
    hinweise: [
      'Gerät vor der Messung ausreichend warmlaufen lassen (Betriebsbereitschaft).',
      'CO-Werte über 1000 ppm im unverdünnten Abgas bedeuten Störung – Ursache suchen, Gerät nicht in Betrieb lassen.',
      'Gasdruck (Fließdruck) am Gerät prüfen; zu geringer Druck führt zu Störabschaltungen.',
      'Messwerte im Wartungsprotokoll dokumentieren und dem Kunden aushändigen.',
    ],
    werte: [
      'Abgasverlust-Grenzwerte nach 1. BImSchV: bis 25 kW 11 % · über 25 bis 50 kW 10 % · über 50 kW 9 %',
      'Brennwertgeräte erreichen typisch 2 bis 5 % Abgasverlust',
      'CO₂ im Abgas Erdgas: etwa 8,5 bis 10 % · O₂ etwa 4 bis 6 %',
      'CO-Richtwert: möglichst unter 100 ppm, Handlungsbedarf ab 400 ppm, Störung über 1000 ppm',
    ],
    normen: ['1. BImSchV', 'DIN EN 50379 (Messgeräte)', 'DVGW-TRGI G 600', 'KÜO'],
    verwandt: ['brennwert', 'abgasanlage', 'gasgeraete', 'inbetriebnahme'],
  },
  {
    id: 'kondensat',
    begriff: 'Kondensat aus Brennwertgeräten',
    bereich: 'gas',
    kategorie: 'Verfahren',
    synonyme: ['Neutralisation', 'Neutralisationsbox', 'Kondensatablauf', 'Kondensatsiphon'],
    kurz: 'Brennwertgeräte erzeugen saures Kondensat, das über einen Siphon abgeleitet und je nach Leistung neutralisiert werden muss.',
    funktion:
      'Beim Unterschreiten des Taupunkts kondensiert Wasserdampf aus dem Abgas. Das Kondensat ist durch gelöstes Kohlendioxid und Spuren anderer Verbrennungsprodukte sauer. Bei Gasgeräten kleiner Leistung darf es in der Regel ohne Behandlung in die Hausentwässerung eingeleitet werden, weil das übrige Abwasser ausreichend puffert. Bei größeren Anlagen und bei Ölbrennwert ist eine Neutralisationseinrichtung mit Granulat (Magnesiumoxid/Kalk) erforderlich.',
    aufbau: ['Kondensatsiphon am Gerät', 'Ablaufleitung aus beständigem Kunststoff (PP, PVC)', 'Neutralisationsbox mit Granulat', 'freier Auslauf bzw. Anschluss nach ATV-Merkblatt'],
    einsatz: ['Gas- und Öl-Brennwertgeräte', 'Abgasleitungen mit Kondensatanfall'],
    hinweise: [
      'Siphon vor der Inbetriebnahme mit Wasser füllen – sonst tritt Abgas aus oder der Druckwächter stört.',
      'Ablaufleitung mit Gefälle und frostfrei verlegen, keine Metallrohre verwenden.',
      'Granulat regelmäßig kontrollieren und tauschen; Verbrauch steigt mit der Betriebszeit.',
      'Örtliche Entwässerungssatzung beachten – Anforderungen können strenger sein.',
    ],
    werte: [
      'Kondensat-pH: Gas etwa 3,5 bis 5,0 · Öl etwa 2 bis 4',
      'Kondensatmenge: etwa 1,5 l je m³ Erdgas bzw. rund 0,14 l je kWh',
      'Neutralisation nach ATV-A 251: bei Gas in der Regel ab 200 kW, bei Öl grundsätzlich',
    ],
    normen: ['ATV-A 251', 'DIN 1986-100', 'DIN EN 12056'],
    verwandt: ['brennwert', 'abgasanlage', 'entwaesserung_grundlagen'],
  },
  {
    id: 'fluessiggas',
    begriff: 'Flüssiggas (Propan/Butan)',
    bereich: 'gas',
    kategorie: 'Anlage',
    synonyme: ['Propan', 'Butan', 'LPG', 'Gastank', 'Flüssiggasflasche'],
    kurz: 'Flüssiggas wird unter Druck flüssig gelagert und ist schwerer als Luft – daraus ergeben sich besondere Sicherheitsanforderungen.',
    funktion:
      'Propan und Butan werden im Behälter als Flüssigkeit gelagert; über der Flüssigkeit steht Gasphase unter ihrem Dampfdruck. Beim Entnehmen verdampft Flüssigkeit nach, was dem Behälter Wärme entzieht. Ein Druckregler reduziert den Behälterdruck auf den Betriebsdruck des Gerätes (meist 50 mbar). Da Flüssiggas schwerer als Luft ist, sammelt es sich bei Undichtigkeiten in Vertiefungen und Kellerräumen – deshalb sind Aufstellung und Lagerung streng geregelt.',
    aufbau: ['Behälter (Flasche, oberirdischer oder erdgedeckter Tank)', 'Druckregler mit Sicherheitsabsperrventil', 'Schlauchleitung bzw. feste Rohrleitung', 'Gaswarngerät in gefährdeten Räumen'],
    einsatz: ['Gebäude ohne Erdgasanschluss', 'Gewerbe, Baustellenheizung, Gastronomie', 'Freizeitbereich (Camping, Grill)'],
    hinweise: [
      'Flüssiggasbehälter dürfen nicht in Räumen unter Erdgleiche aufgestellt werden.',
      'Dampfdruck ist temperaturabhängig – bei Frost liefert Butan praktisch keine Gasphase mehr, Propan schon.',
      'Schlauchleitungen regelmäßig prüfen und nach Herstellerfrist tauschen.',
      'Prüffristen für Tanks (innere und äußere Prüfung) einhalten, Nachweise aufbewahren.',
    ],
    werte: [
      'Dichte: schwerer als Luft (Propan etwa 1,55-fach)',
      'Heizwert Propan: etwa 12,9 kWh je kg bzw. 25,9 kWh je m³',
      'Betriebsdruck Geräte: meist 50 mbar',
      'Zündbereich Propan in Luft: etwa 2,1 bis 9,5 Volumenprozent',
    ],
    normen: ['DVGW-TRF 2021 (Technische Regeln Flüssiggas)', 'BetrSichV', 'DGUV Regel 110-010'],
    verwandt: ['gasinstallation', 'gasgeruch', 'gasgeraete'],
  },
  {
    id: 'gasgeruch',
    begriff: 'Verhalten bei Gasgeruch',
    bereich: 'gas',
    kategorie: 'Sicherheit',
    synonyme: ['Gasaustritt', 'Gasalarm', 'Gasleck', 'es riecht nach Gas'],
    kurz: 'Bei Gasgeruch gilt eine feste Handlungsfolge – jede Zündquelle kann zur Explosion führen.',
    funktion:
      'Erdgas wird odoriert, damit schon geringe Mengen wahrnehmbar sind. Ein zündfähiges Gemisch entsteht bereits bei wenigen Volumenprozent in Luft. Schalthandlungen erzeugen Funken und sind deshalb ebenso gefährlich wie offenes Feuer. Die Leitungsanlage wird abgesperrt, der Bereich belüftet und geräumt, danach übernimmt der Netzbetreiber oder das eingetragene Fachunternehmen.',
    aufbau: [
      'Keine Zündquelle: nicht schalten, kein Licht, kein Telefon im Raum, keine Klingel',
      'Hauptabsperreinrichtung schließen',
      'Fenster und Türen öffnen, gründlich lüften',
      'Gebäude verlassen, andere warnen (nicht klingeln – klopfen)',
      'Von außen Netzbetreiber-Notruf bzw. Feuerwehr 112 anrufen',
    ],
    einsatz: ['Jeder Verdacht auf Gasaustritt in Gebäuden'],
    hinweise: [
      'Bei Flüssiggas zusätzlich tiefliegende Räume und Schächte beachten – das Gas sammelt sich unten.',
      'Anlage erst nach Freigabe durch den Netzbetreiber bzw. das Fachunternehmen wieder in Betrieb nehmen.',
      'Kunden bei jeder Gerätewartung über dieses Verhalten informieren.',
    ],
    werte: ['Zündbereich Erdgas in Luft: etwa 4 bis 17 Volumenprozent', 'Odorierung macht Gas bereits ab etwa 1/5 der unteren Zündgrenze wahrnehmbar'],
    normen: ['DVGW-TRGI G 600', 'DVGW G 465-4', 'DGUV Vorschrift 1'],
    verwandt: ['gasinstallation', 'gaspruefung', 'fluessiggas', 'arbeitssicherheit'],
  },
];
