/**
 * Fachdatenbank – Grundlagen, Werkstoffe, Verbindungstechnik, Berechnungen,
 * Arbeitssicherheit und Ausbildung.
 */

export const GRUNDLAGEN = [
  /* ------------------------------------------------------------ Werkstoffe */
  {
    id: 'kupferrohr',
    begriff: 'Kupferrohr',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['Kupfer', 'Cu-Rohr', 'Cu-DHP', 'Kupferleitung'],
    kurz: 'Kupferrohr nach DIN EN 1057 ist der klassische Werkstoff für Trinkwasser-, Heizungs- und Gasleitungen; es wird gelötet, gepresst oder geklemmt.',
    funktion:
      'Verwendet wird sauerstofffreies, phosphordesoxidiertes Kupfer (Cu-DHP). Das Rohr ist korrosionsbeständig, formbar und diffusionsdicht. Im Trinkwasser bildet sich eine schützende Deckschicht; Voraussetzung ist ein geeignetes Wasser (pH-Wert ab 7,4 bzw. TOC-Grenzwert beachten). Verbunden wird durch Weichlöten, Hartlöten, Pressen oder Klemmen. Die Bezeichnung erfolgt immer mit Außendurchmesser x Wandstärke.',
    aufbau: [
      'Weiche Rohre in Ringen (bis 22 mm) für Biegearbeiten',
      'Halbharte und harte Rohre in Stangen à 5 m',
      'Lötfittings (Kapillarfittings), Pressfittings mit EPDM-O-Ring, Klemmringverschraubungen',
    ],
    einsatz: [
      'Trinkwasserinstallation (kalt und warm) nach DIN 1988-200',
      'Heizungsverteilung und Anbindeleitungen',
      'Gasinstallation nach DVGW-TRGI (nur mit zugelassenen Fittings, hartgelötet oder gepresst)',
      'Solarkreise (dort mit FKM-Dichtungen wegen der Temperaturen)',
    ],
    hinweise: [
      'Fließregel beachten: In Fließrichtung dürfen nach Kupfer keine verzinkten Stahlteile folgen (Lochkorrosion).',
      'Im Trinkwasser weichlöten nur bis einschließlich 28 mm, darüber hartlöten.',
      'Rohr sauber ablängen, innen und außen entgraten, Oberfläche vor dem Löten metallisch blank machen.',
      'Erdverlegt oder im Estrich nur mit Schutzmantel bzw. ummantelt verlegen.',
    ],
    stoerungen: [
      'Lochfraß/Lochkorrosion: ungeeignete Wasserbeschaffenheit, Restfilme vom Ziehprozess, Zinkabtrag aus falscher Werkstoffreihenfolge',
      'Undichte Lötstelle: zu wenig Flussmittel, verzunderte Oberfläche, zu große oder zu kleine Spaltbreite',
    ],
    werte: [
      'Gängige Abmessungen: 12 x 1,0 / 15 x 1,0 / 18 x 1,0 / 22 x 1,0 / 28 x 1,5 / 35 x 1,5 / 42 x 1,5 / 54 x 2,0 mm',
      'Längenausdehnung: 0,0166 mm je Meter und Kelvin',
      'Wärmeleitfähigkeit: etwa 380 W/(m·K)',
      'Schmelzpunkt: 1083 °C – Weichlot schmilzt bei 220–250 °C, Hartlot bei 650–800 °C',
    ],
    normen: ['DIN EN 1057', 'DIN 1988-200', 'DIN EN 806', 'DVGW GW 392'],
    verwandt: ['weichloeten', 'hartloeten', 'pressverbindung', 'korrosion', 'waermedehnung'],
    vertiefungen: [
      {
        frage: 'Warum darf nach Kupfer kein verzinktes Stahlrohr folgen?',
        text: 'Kupfer geht in geringen Mengen in Lösung. Trifft dieses kupferhaltige Wasser auf eine verzinkte Stahloberfläche, scheidet sich das Kupfer dort ab. Zink und Kupfer bilden mit dem Wasser als Elektrolyt ein galvanisches Element, in dem das unedlere Zink als Anode zerstört wird. Die Zinkschicht wird örtlich abgetragen, darunter beginnt der Stahl zu rosten – es entsteht Lochfraß. Deshalb gilt die Fließregel: verzinkte Teile immer vor dem Kupfer, nie danach.',
      },
    ],
  },
  {
    id: 'edelstahlrohr',
    begriff: 'Edelstahlrohr',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['Edelstahl', 'Niro', 'Inox', '1.4401', '1.4521', 'Nirosta'],
    kurz: 'Nichtrostendes Stahlrohr (Werkstoff 1.4401/1.4404 oder 1.4521) für hygienisch anspruchsvolle Trinkwasserinstallationen, nahezu ausschließlich als Pressfittingsystem.',
    funktion:
      'Der Chrom-Nickel-Molybdän-Stahl bildet eine Passivschicht, die ihn gegen Korrosion schützt. Edelstahl ist unabhängig von der Wasserbeschaffenheit einsetzbar und gibt keine Metallionen in nennenswerter Menge ab – deshalb ist er in der Trinkwasserhygiene der universelle Werkstoff. Verarbeitet wird dünnwandiges Rohr mit Pressfittings; Löten und Schweißen sind auf der Baustelle unüblich.',
    aufbau: [
      'Dünnwandrohr, längsnahtgeschweißt, Wandstärke 1,0 bis 1,5 mm',
      'Pressfittings mit EPDM-O-Ring (Trinkwasser/Heizung) oder FKM (Solar, hohe Temperaturen)',
      'Übergänge auf Gewinde aus Rotguss oder Siliziumbronze',
    ],
    einsatz: [
      'Trinkwasserinstallation, besonders bei ungünstiger Wasserbeschaffenheit oder hohen Hygieneanforderungen',
      'Krankenhäuser, Schulen, Lebensmittelbetriebe',
      'Heizungs- und Druckluftleitungen',
    ],
    hinweise: [
      'Niemals mit unlegiertem Stahlwerkzeug bearbeiten (Fremdrost) – eigene Trennscheiben und Bürsten verwenden.',
      'Nicht mit dem Winkelschleifer trennen: Wärmeeinbringung schädigt die Passivschicht; Rohrabschneider verwenden.',
      'Chloridhaltige Umgebung (Schwimmbad, Streusalz) erfordert 1.4404/1.4571 oder 1.4521.',
      'Einstecktiefe markieren und nach dem Pressen kontrollieren.',
    ],
    stoerungen: [
      'Fremdrost auf der Oberfläche: Bearbeitung mit stahlbehaftetem Werkzeug',
      'Spannungsrisskorrosion: Chloridbelastung in Verbindung mit Zugspannung',
    ],
    werte: [
      'Gängige Abmessungen: 15 x 1,0 / 18 x 1,0 / 22 x 1,2 / 28 x 1,2 / 35 x 1,5 / 42 x 1,5 / 54 x 1,5 mm',
      'Längenausdehnung: 0,0165 mm je Meter und Kelvin',
      'Wärmeleitfähigkeit: etwa 15 W/(m·K)',
    ],
    normen: ['DIN EN 10312', 'DIN 1988-200', 'DVGW W 541'],
    verwandt: ['kupferrohr', 'pressverbindung', 'trinkwasserhygiene'],
  },
  {
    id: 'c_stahlrohr',
    begriff: 'C-Stahlrohr (außen verzinkt)',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['C-Stahl', 'Kohlenstoffstahl', 'verzinktes Pressrohr'],
    kurz: 'Unlegiertes Stahlrohr mit äußerer Zinkschicht, das ausschließlich in geschlossenen Heizungs- und Kühlkreisen eingesetzt wird.',
    funktion:
      'Innen ist das Rohr blank. In einem geschlossenen Kreislauf wird der im Füllwasser gelöste Sauerstoff bei der ersten Erwärmung verbraucht; danach ist keine Korrosion mehr möglich. Voraussetzung ist ein dauerhaft sauerstoffdichtes System. Die äußere Zinkschicht schützt vor Korrosion durch Luftfeuchte.',
    aufbau: ['Rohr mit Zinkbeschichtung außen', 'Pressfittings aus C-Stahl mit EPDM-O-Ring', 'Übergangsstücke auf Gewinde'],
    einsatz: ['Geschlossene Heizungsanlagen', 'Kaltwassersätze und Kühlkreise (mit Dampfbremse gedämmt)', 'Druckluft (öl- und wasserfrei)'],
    hinweise: [
      'Nicht für Trinkwasser und nicht für offene Systeme zulässig.',
      'Ständiger Wasserverlust mit Nachspeisung führt zu Sauerstoffeintrag und damit zu Korrosion – Anlage dicht halten.',
      'Schnittstellen und Kratzer im Zinküberzug nachbessern, besonders in feuchten Räumen.',
    ],
    stoerungen: ['Schwarzer Schlamm und Magnetit im Heizwasser: Sauerstoffeintrag durch Undichtigkeit oder diffusionsoffene Rohre'],
    werte: ['Abmessungen 12 bis 108 mm', 'Längenausdehnung 0,012 mm je Meter und Kelvin'],
    normen: ['DIN EN 10305', 'VDI 2035', 'DIN EN 12828'],
    verwandt: ['heizungswasser', 'pressverbindung', 'korrosion'],
  },
  {
    id: 'gewinderohr',
    begriff: 'Gewinderohr und Temperguss-Fittings',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['Stahlrohr', 'schwarzes Rohr', 'Gasrohr', 'Fittings', 'Muffe'],
    kurz: 'Geschweißtes Stahlrohr nach DIN EN 10255, das mit kegeligem Außengewinde (R) und zylindrischem Innengewinde (Rp) über Temperguss-Fittings verbunden wird.',
    funktion:
      'Das Gewinde wird mit der Schneidkluppe geschnitten. Gedichtet wird im Gewindegang mit Hanf und Dichtpaste oder mit PTFE-Band – die Dichtwirkung entsteht durch das kegelige Außengewinde, das sich im zylindrischen Innengewinde verspannt. Die Bezeichnung erfolgt in Zoll, die Nennweite in DN.',
    aufbau: ['Rohr schwarz oder verzinkt', 'Temperguss-Fittings: Muffe, Bogen, T-Stück, Reduzierung, Verschraubung', 'Dichtmittel: Hanf mit Paste, PTFE-Band, anaerober Dichtstoff'],
    einsatz: ['Gasinstallation im Bestand', 'Heizungsleitungen größerer Nennweiten', 'Sprinkler- und Industrieleitungen', 'Anschluss von Armaturen und Zählern'],
    hinweise: [
      'Gewinde vor dem Eindichten entgraten; Hanf gegen die Einschraubrichtung auflegen.',
      'Nach dem Anziehen nicht zurückdrehen – sonst wird die Dichtung undicht.',
      'Verzinktes Rohr nicht schweißen (Zinkdämpfe, Verlust des Korrosionsschutzes).',
    ],
    werte: [
      'Zoll zu DN: 3/8" = DN 10 · 1/2" = DN 15 · 3/4" = DN 20 · 1" = DN 25 · 1 1/4" = DN 32 · 1 1/2" = DN 40 · 2" = DN 50',
      'Gewindearten: R (kegelig außen), Rp (zylindrisch innen), G (zylindrisch, nur mit Flachdichtung)',
    ],
    normen: ['DIN EN 10255', 'DIN EN 10226', 'DVGW-TRGI G 600'],
    verwandt: ['gewindeverbindung', 'dichtstoffe', 'gasinstallation'],
  },
  {
    id: 'mehrschichtverbundrohr',
    begriff: 'Mehrschichtverbundrohr',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['Verbundrohr', 'MSVR', 'Alu-Verbundrohr', 'MLV', 'Alpex'],
    kurz: 'Kunststoffrohr mit eingebetteter, längsnahtgeschweißter Aluminiumschicht – formstabil, sauerstoffdicht und mit geringer Wärmedehnung.',
    funktion:
      'Der Aufbau PE-RT/Kleber/Aluminium/Kleber/PE-RT verbindet die Vorteile beider Werkstoffe: Der Kunststoff ist korrosionsfest und leise, die Aluminiumschicht macht das Rohr biegbar und formstabil, sperrt Sauerstoff aus und senkt die Wärmedehnung gegenüber reinem Kunststoff auf etwa ein Sechstel. Verbunden wird mit Press- oder Schiebehülsenfittings.',
    aufbau: ['Innen- und Außenschicht PE-RT oder PE-X', 'Aluminiumschicht als Sauerstoffsperre', 'Press- oder Schiebehülsenfittings aus Rotguss/PPSU'],
    einsatz: ['Trinkwasser-Stockwerksinstallation', 'Heizkörperanbindung', 'Fußbodenheizung', 'Druckluft in Kleinbetrieben'],
    hinweise: [
      'Nach dem Ablängen zwingend kalibrieren und entgraten, sonst wird der O-Ring beschädigt.',
      'Nur Rohre und Fittings desselben Systems kombinieren.',
      'Mindestbiegeradius einhalten, sonst knickt die Aluminiumschicht.',
      'Nicht dauerhaft UV-Strahlung aussetzen.',
    ],
    werte: [
      'Gängige Abmessungen: 14 x 2,0 / 16 x 2,0 / 20 x 2,0 / 26 x 3,0 / 32 x 3,0 mm',
      'Längenausdehnung: etwa 0,025 mm je Meter und Kelvin',
      'Dauerbetrieb: 70 °C bei 10 bar, kurzzeitig 95 °C',
    ],
    normen: ['DIN 16836', 'DVGW W 542', 'DIN 1988-200'],
    verwandt: ['fussbodenheizung', 'pressverbindung', 'pe_x_rohr'],
  },
  {
    id: 'pe_x_rohr',
    begriff: 'PE-X- und PE-RT-Rohr',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['PEX', 'vernetztes Polyethylen', 'PE-RT', 'Kunststoffrohr Heizung'],
    kurz: 'Flexible Kunststoffrohre für Flächenheizung und Trinkwasser; PE-X ist vernetzt, PE-RT erhöht temperaturbeständig.',
    funktion:
      'Durch die Vernetzung (peroxidisch = PE-Xa, silan = PE-Xb, elektronenstrahl = PE-Xc) entsteht ein räumliches Molekülnetz, das dem Rohr Formstabilität bei höheren Temperaturen und ein Formgedächtnis gibt. PE-RT erreicht die Temperaturbeständigkeit ohne Vernetzung über die Molekülstruktur und ist dadurch schweißbar. Für geschlossene Heizkreise müssen die Rohre eine Sauerstoffsperrschicht (EVOH) besitzen.',
    aufbau: ['Rohrkörper aus PE-X bzw. PE-RT', 'Sauerstoffsperrschicht EVOH nach DIN 4726', 'Press-, Schiebehülsen- oder Klemmringfittings'],
    einsatz: ['Fußboden-, Wand- und Deckenheizung', 'Heizkörperanbindung im Estrich', 'Trinkwasser-Einzelanbindung (Rohr-in-Rohr)'],
    hinweise: [
      'Ohne Sauerstoffsperre nur mit Systemtrennung über Wärmeübertrager betreiben.',
      'Große Wärmedehnung einplanen (ca. 0,15 mm/m·K bei PE-X).',
      'Nicht knicken – geknickte Stellen ersetzen, nicht zurückbiegen.',
    ],
    werte: ['Übliche Abmessungen Flächenheizung: 16 x 2,0 / 17 x 2,0 / 20 x 2,0 mm', 'Dauerbetrieb 70 °C / 10 bar'],
    normen: ['DIN EN ISO 15875', 'DIN 4726', 'DIN EN 1264'],
    verwandt: ['fussbodenheizung', 'mehrschichtverbundrohr', 'heizungswasser'],
  },
  {
    id: 'dichtstoffe',
    begriff: 'Dicht- und Dichtungswerkstoffe',
    bereich: 'grundlagen',
    kategorie: 'Werkstoff',
    synonyme: ['Hanf', 'Teflonband', 'PTFE', 'O-Ring', 'EPDM', 'FKM', 'Dichtung', 'Fermit'],
    kurz: 'Jede Verbindung braucht den zum Medium und zur Temperatur passenden Dichtwerkstoff – falsch gewählt, ist sie früher oder später undicht.',
    funktion:
      'Gewindedichtungen füllen den Gewindegang aus (Hanf mit Dichtpaste, PTFE-Band, anaerobe Dichtstoffe). Elastomerdichtungen dichten durch Verpressung: EPDM ist der Standard für Trinkwasser und Heizung, FKM für hohe Temperaturen und Öl, NBR für Öl und Kraftstoff, HNBR für Gas. Flachdichtungen (AFM/Faserstoff) dichten Flansche und Verschraubungen.',
    aufbau: [
      'Hanf + Dichtpaste: lösbar, für Wasser und Gas zugelassen',
      'PTFE-Band: für Gewinde bis 1 Zoll, mehrlagig in Gewinderichtung',
      'EPDM (schwarz): Wasser, Heizung, Dampf – nicht ölbeständig',
      'FKM (grün/rot): Solar, Öl, hohe Temperaturen',
      'HNBR (gelb): Gasinstallation',
    ],
    einsatz: ['Gewindeverbindungen', 'Pressfittings', 'Flanschverbindungen', 'Armaturen und Verschraubungen'],
    hinweise: [
      'Nur Dichtmittel mit DVGW-Zulassung für Trinkwasser und Gas verwenden.',
      'O-Ringe beim Zusammenbau nicht fetten, sofern der Hersteller es nicht ausdrücklich erlaubt.',
      'Beschädigte O-Ringe immer ersetzen, nie nachjustieren.',
    ],
    werte: ['EPDM: -30 bis +110 °C', 'FKM: -20 bis +180 °C', 'HNBR: -30 bis +140 °C, gasgeeignet'],
    normen: ['DIN EN 751', 'DVGW VP 601', 'DIN 3535'],
    verwandt: ['gewindeverbindung', 'pressverbindung'],
  },

  /* ------------------------------------------------------------ Verbindungstechnik */
  {
    id: 'pressverbindung',
    begriff: 'Pressverbindung (Pressfitting)',
    bereich: 'grundlagen',
    kategorie: 'Verfahren',
    synonyme: ['Pressfitting', 'verpressen', 'Presse', 'Pressbacke', 'Presskontur'],
    kurz: 'Unlösbare, kalt hergestellte Rohrverbindung: Der Fitting wird mit einer Pressmaschine plastisch verformt und presst dabei einen O-Ring in die Dichtzone.',
    funktion:
      'Das entgratete Rohr wird bis zum Endanschlag in den Fitting gesteckt. Die Pressbacke verformt die Fittingschulter form- und kraftschlüssig um das Rohr; der eingelegte Dichtring wird dabei definiert verpresst. Die Verbindung ist sofort belastbar, benötigt keine offene Flamme und ist deshalb auf Baustellen mit Brandlastbeschränkung erste Wahl. Unverpresste Stellen werden durch die Leckageanzeige bei der Dichtheitsprüfung sichtbar.',
    aufbau: [
      'Fittingkörper aus Kupfer, Edelstahl, C-Stahl oder Rotguss',
      'O-Ring: EPDM (Wasser/Heizung), FKM (Solar), HNBR (Gas)',
      'Presskontur M, V, TH oder U – systemabhängig',
      'Akku-Pressmaschine mit Backe oder Kette in passender Nennweite',
    ],
    einsatz: ['Trinkwasser-, Heizungs-, Kühl- und Druckluftleitungen', 'Gasinstallation mit ausdrücklich zugelassenen Systemen', 'Nennweiten 12 bis 108 mm'],
    hinweise: [
      'Rohr, Fitting und Backe müssen aus einem zugelassenen System stammen – nicht mischen.',
      'Einstecktiefe anzeichnen und nach dem Pressen prüfen.',
      'Pressvorgang immer vollständig durchlaufen lassen, nicht unterbrechen.',
      'Backen regelmäßig reinigen und die Maschine nach Herstellerangabe warten lassen (meist jährlich oder alle 40.000 Pressungen).',
      'Mindestabstände zwischen zwei Pressstellen und zu Bögen einhalten.',
    ],
    stoerungen: [
      'Undichtigkeit direkt nach der Prüfung: Fitting nicht verpresst (Leckageanzeige) oder O-Ring beim Einstecken beschädigt',
      'Rohr rutscht heraus: Einstecktiefe nicht erreicht',
      'Verformte Presskontur: falsche Backe oder verschmutzte Presskontur',
    ],
    werte: ['Pressdauer je nach Maschine 3–5 s', 'Einstecktiefe z. B. 22 mm Rohr: etwa 21 mm'],
    normen: ['DIN 1988-200', 'DVGW W 534', 'DVGW-TRGI G 600 (Gas)'],
    verwandt: ['kupferrohr', 'edelstahlrohr', 'dichtstoffe', 'dichtheitspruefung'],
  },
  {
    id: 'weichloeten',
    begriff: 'Weichlöten',
    bereich: 'grundlagen',
    kategorie: 'Verfahren',
    synonyme: ['löten', 'gelötet', 'Lötverbindung', 'Kapillarlöten', 'S-Sn97Cu3'],
    kurz: 'Beim Weichlöten wird ein Lot unter 450 °C in den Kapillarspalt zwischen Rohr und Fitting gezogen; das Grundmaterial schmilzt dabei nicht.',
    funktion:
      'Die metallisch blanke Oberfläche wird mit Flussmittel benetzt, das Oxide löst und die Benetzung ermöglicht. Beim Erwärmen auf Arbeitstemperatur schmilzt das Lot und wird durch die Kapillarwirkung in den engen Spalt (0,02–0,2 mm) gezogen – auch gegen die Schwerkraft. Beim Erstarren entsteht eine feste, dichte Verbindung durch Diffusion an der Grenzfläche.',
    aufbau: [
      'Weichlot S-Sn97Cu3 (bleifrei), Arbeitstemperatur 230–250 °C',
      'Flussmittel für Trinkwasser nach DIN EN 1045 (Typ 3.1.1)',
      'Propan- oder Acetylenbrenner, Lötschutzmatte, Feuerlöscher',
    ],
    einsatz: ['Kupferrohr in Trinkwasser- und Heizungsinstallationen', 'Reparaturen im Bestand'],
    hinweise: [
      'Im Trinkwasser nur bis einschließlich 28 mm zulässig – größere Nennweiten hartlöten.',
      'Rohr innen und außen entgraten, Fitting und Rohrende mit Vlies blank machen (kein Schmirgelpapier mit Eisenanteil).',
      'Flussmittel sparsam und nur außen auf das Rohrende auftragen, Reste nach dem Löten abwischen.',
      'Erlaubnisschein für Heißarbeiten und Brandwache nicht vergessen.',
      'Nach dem Löten gründlich spülen.',
    ],
    stoerungen: [
      'Lot läuft nicht in den Spalt: Temperatur zu niedrig oder Oberfläche oxidiert',
      'Poröse, graue Lötstelle: überhitzt, Flussmittel verbrannt',
      'Undichtigkeit nach Monaten: Flussmittelreste führen zu Korrosion',
    ],
    werte: ['Weichlot bis 450 °C Arbeitstemperatur', 'Kapillarspalt 0,02 bis 0,2 mm', 'Trinkwasser: bis DN 25 bzw. 28 mm'],
    normen: ['DIN EN 1044', 'DIN EN 29453', 'DVGW GW 2', 'DIN 1988-200'],
    verwandt: ['hartloeten', 'kupferrohr', 'arbeitssicherheit'],
  },
  {
    id: 'hartloeten',
    begriff: 'Hartlöten',
    bereich: 'grundlagen',
    kategorie: 'Verfahren',
    synonyme: ['Silberlot', 'CP 203', 'Hartlot', 'hartgelötet'],
    kurz: 'Löten oberhalb von 450 °C mit Kupfer-Phosphor- oder Silberloten; ergibt deutlich höhere Festigkeit als Weichlöten.',
    funktion:
      'Das Bauteil wird auf Rotglut (etwa 700 °C) erwärmt. Kupfer-Phosphor-Lote (CP 203, früher L-CuP6) wirken auf Kupfer selbstfließend, weil der Phosphor die Oxide reduziert – hier ist kein Flussmittel nötig. Bei Mischverbindungen mit Rotguss, Messing oder Stahl wird ein silberhaltiges Lot mit Flussmittel verwendet.',
    aufbau: ['Hartlot CP 203 (Kupfer-Phosphor) für Kupfer auf Kupfer', 'Silberlot mit Flussmittel für Mischverbindungen', 'Acetylen-Sauerstoff- oder Propanbrenner'],
    einsatz: [
      'Trinkwasserleitungen über 28 mm',
      'Gasleitungen aus Kupfer (in der TRGI gefordert)',
      'Kälte- und Klimatechnik (Kältemittelleitungen, unter Schutzgas)',
    ],
    hinweise: [
      'Kupfer-Phosphor-Lot niemals auf Stahl oder Nickellegierungen verwenden – es entstehen spröde Phosphide.',
      'Beim Hartlöten von Kältemittelleitungen mit Formiergas (Stickstoff) spülen, sonst verzundert die Innenoberfläche.',
      'Bauteile mit Dichtungen vorher ausbauen.',
    ],
    werte: ['Arbeitstemperatur 650–800 °C', 'CP 203: 6 % Phosphor, Rest Kupfer', 'Festigkeit deutlich über Weichlot'],
    normen: ['DIN EN ISO 17672', 'DVGW-TRGI G 600', 'DIN 1988-200'],
    verwandt: ['weichloeten', 'kupferrohr', 'arbeitssicherheit'],
  },
  {
    id: 'gewindeverbindung',
    begriff: 'Gewindeverbindung',
    bereich: 'grundlagen',
    kategorie: 'Verfahren',
    synonyme: ['gehanft', 'eindichten', 'Gewinde schneiden', 'Kluppe', 'verschraubt'],
    kurz: 'Lösbare Rohrverbindung über kegeliges Außengewinde (R) und zylindrisches Innengewinde (Rp), im Gewindegang mit Hanf oder PTFE gedichtet.',
    funktion:
      'Beim Einschrauben verspannt sich das kegelige Außengewinde im zylindrischen Innengewinde. Das Dichtmittel füllt die verbleibenden Hohlräume im Gewindegang und verhindert, dass Wasser oder Gas durch die Gewindewendel austritt. Die Dichtwirkung entsteht also im Gewinde, nicht an der Stirnfläche.',
    aufbau: ['Gewindeschneidkluppe mit Schneidbacken und Schneidöl', 'Hanf und Dichtpaste oder PTFE-Band', 'Temperguss-Fittings, Verschraubungen, Übergangsstücke'],
    einsatz: ['Anschluss von Armaturen, Pumpen, Zählern und Geräten', 'Gasinstallation im Bestand', 'Heizungsverteilungen'],
    hinweise: [
      'Gewinde nach dem Schneiden entgraten und Späne entfernen.',
      'Hanf gegen die Einschraubrichtung auflegen, dann Dichtpaste aufbringen.',
      'Nach dem Anziehen nicht zurückdrehen – sonst wird die Dichtung undicht.',
      'Flachdichtende Verschraubungen (G-Gewinde) brauchen eine Flachdichtung, kein Hanf.',
    ],
    stoerungen: ['Undicht trotz Hanf: Gewinde zu tief geschnitten oder zurückgedreht', 'Gerissener Fitting: zu viel Hanf, Sprengwirkung durch Überdehnung'],
    normen: ['DIN EN 10226', 'DIN EN 751-2', 'DVGW-TRGI G 600'],
    verwandt: ['gewinderohr', 'dichtstoffe'],
  },
  {
    id: 'steckmuffe',
    begriff: 'Steckmuffenverbindung',
    bereich: 'grundlagen',
    kategorie: 'Verfahren',
    synonyme: ['zusammengesteckt', 'Muffe', 'Lippendichtring', 'Steckverbindung'],
    kurz: 'Lösbare Verbindung für Abflussrohre: Das Spitzende wird in die Muffe mit Lippendichtring geschoben, die Dichtung liegt radial an.',
    funktion:
      'Der elastische Lippendichtring in der Muffe wird beim Einschieben verformt und liegt unter Vorspannung am Spitzende an. Die Verbindung ist drucklos dicht, nimmt Längsbewegungen auf und lässt sich zerstörungsfrei lösen. Ein Dehnungsspalt von etwa 10 mm bleibt erhalten, damit sich das Rohr bei Temperaturwechsel bewegen kann.',
    aufbau: ['Muffe mit eingelegtem Lippendichtring', 'Spitzende mit angefaster Kante', 'Gleitmittel (kein Fett auf Mineralölbasis)'],
    einsatz: ['HT- und KG-Abflussrohre', 'Lüftungsleitungen der Entwässerung', 'Regenwasserleitungen'],
    hinweise: [
      'Schnittkante anfasen, sonst wird die Dichtung beim Einschieben umgestülpt.',
      'Einstecktiefe markieren und 10 mm Dehnungsspalt zurückziehen.',
      'Dichtring auf Sitz und Sauberkeit prüfen.',
    ],
    normen: ['DIN EN 1451', 'DIN EN 1401', 'DIN EN 12056'],
    verwandt: ['ht_rohr', 'kg_rohr', 'entwaesserung_grundlagen'],
  },
  {
    id: 'rohrbefestigung',
    begriff: 'Rohrbefestigung, Fest- und Gleitpunkte',
    bereich: 'grundlagen',
    kategorie: 'Verfahren',
    synonyme: ['Schelle', 'Rohrschelle', 'aufgehängt', 'Festpunkt', 'Gleitlager', 'Montageschiene'],
    kurz: 'Rohrleitungen werden mit Schellen so befestigt, dass sie Gewicht tragen, Schall entkoppeln und sich trotzdem in Längsrichtung dehnen können.',
    funktion:
      'Ein Festpunkt fixiert das Rohr in alle Richtungen und teilt die Leitung in definierte Dehnungsabschnitte. Alle übrigen Schellen sind Gleitpunkte: Sie tragen das Rohr, lassen aber die Längsbewegung zu. Zwischen zwei Festpunkten muss die Dehnung durch einen Bogen, eine Schleife oder einen Kompensator aufgenommen werden. Schellen mit Gummieinlage unterbrechen die Körperschallübertragung ins Bauwerk.',
    aufbau: [
      'Rohrschelle mit Gummieinlage (Schallschutz)',
      'Gewindestange M8/M10 mit Dübel oder Ankerschiene',
      'Montageschiene (C-Profil) für mehrere Leitungen',
      'Festpunktschelle ohne Einlage, kraftschlüssig',
    ],
    einsatz: ['Alle Rohrleitungen in Gebäuden', 'Fallleitungen mit Festpunkt je Geschoss', 'Vorwandinstallationen und Schächte'],
    hinweise: [
      'Befestigungsabstände nach Werkstoff wählen; im Zweifel Herstellerangabe.',
      'Untergrund prüfen: Dübel nach Zulassung und Baustoff auswählen.',
      'In Fluchtwegen und Decken Brandschutzanforderungen an die Befestigung beachten.',
      'Keine Schelle direkt an einem Bogen – dort entsteht die größte Bewegung.',
    ],
    werte: [
      'Richtwerte Schellenabstand Kupfer: 15 mm ≈ 1,25 m · 22 mm ≈ 2,0 m · 28 mm ≈ 2,25 m · 42 mm ≈ 3,0 m',
      'Kunststoffabflussrohr senkrecht: etwa alle 2 m, waagerecht etwa alle 10 x DN',
    ],
    normen: ['DIN 4109 (Schallschutz)', 'DIN EN 12056', 'VDI 6003'],
    verwandt: ['waermedehnung', 'schallschutz', 'daemmung_geg'],
  },
  {
    id: 'waermedehnung',
    begriff: 'Wärmedehnung von Rohrleitungen',
    bereich: 'grundlagen',
    kategorie: 'Berechnung',
    synonyme: ['Längenausdehnung', 'Dehnungsausgleich', 'Ausdehnung', 'Kompensator'],
    kurz: 'Jedes Rohr wird bei Erwärmung länger; wird diese Bewegung behindert, entstehen Zwängungskräfte, Geräusche und Schäden.',
    funktion:
      'Die Längenänderung berechnet sich aus Länge, Werkstoffkennwert und Temperaturdifferenz. Aufgenommen wird sie durch Richtungsänderungen (Dehnungsschenkel), U-Bögen, Dehnungsschleifen oder Kompensatoren. Der Dehnungsschenkel muss so lang sein, dass die auftretende Biegespannung im zulässigen Bereich bleibt.',
    aufbau: ['Festpunkte begrenzen den Dehnungsabschnitt', 'Gleitlager führen das Rohr', 'Dehnungsschenkel, U-Bogen oder Axialkompensator nimmt die Bewegung auf'],
    einsatz: ['Steigleitungen', 'lange Verteilleitungen im Keller', 'Fernwärme- und Dampfleitungen'],
    hinweise: [
      'Kunststoffrohre dehnen sich etwa zehnmal so stark wie Kupfer – dort ist der Ausgleich besonders wichtig.',
      'Schellen im Dehnungsbereich als Gleitlager ausführen.',
      'Dämmung im Bereich des Dehnungsschenkels weich ausführen, damit die Bewegung möglich bleibt.',
    ],
    formeln: [
      {
        name: 'Längenänderung',
        formel: 'Δl = L · α · ΔT',
        erklaerung: 'Δl in mm, L in m, α in mm/(m·K), ΔT in K. Beispiel: 10 m Kupfer, 50 K → 10 · 0,0166 · 50 = 8,3 mm.',
      },
      {
        name: 'Dehnungsschenkel (Kupfer, Näherung)',
        formel: 'Ls = C · √(d · Δl)',
        erklaerung: 'Ls = Schenkellänge in mm, d = Außendurchmesser in mm, Δl = Längenänderung in mm, C ≈ 33 für Kupfer.',
      },
    ],
    werte: [
      'α in mm/(m·K): Stahl 0,012 · Kupfer 0,0166 · Edelstahl 0,0165 · Verbundrohr 0,025 · PP 0,15 · PE-X 0,15–0,20 · PVC 0,08',
    ],
    normen: ['DIN EN 806-4', 'DIN 1988-200', 'DIN EN 12828'],
    verwandt: ['rohrbefestigung', 'kupferrohr', 'fernwaerme'],
  },
  {
    id: 'korrosion',
    begriff: 'Korrosion in Rohrleitungen',
    bereich: 'grundlagen',
    kategorie: 'Grundlagen',
    synonyme: ['Rost', 'Lochfraß', 'Kontaktkorrosion', 'Elementbildung', 'Fließregel'],
    kurz: 'Korrosion ist die Zerstörung eines metallischen Werkstoffs durch Reaktion mit seiner Umgebung – im Rohrleitungsbau meist elektrochemisch unter Beteiligung von Wasser und Sauerstoff.',
    funktion:
      'Für die elektrochemische Korrosion braucht es Anode, Kathode, Elektrolyt und eine leitende Verbindung. Das unedlere Metall geht als Anode in Lösung. Sauerstoff ist der Treiber: In geschlossenen Heizungsanlagen wird er einmalig verbraucht, danach ruht die Korrosion. In offenen oder undichten Systemen wird er ständig nachgeliefert und der Angriff läuft weiter. Schutz bieten Werkstoffwahl, Beschichtungen, Deckschichten, Trennung unterschiedlicher Metalle und Sauerstoffdichtheit.',
    aufbau: [
      'Flächenkorrosion: gleichmäßiger Abtrag',
      'Lochkorrosion: örtlicher Durchbruch trotz intakter Umgebung',
      'Kontakt-/Elementkorrosion: zwei unterschiedliche Metalle im Elektrolyt',
      'Spaltkorrosion und Spannungsrisskorrosion',
      'Erosionskorrosion: zu hohe Fließgeschwindigkeit trägt die Deckschicht ab',
    ],
    einsatz: ['Werkstoffauswahl bei Trinkwasser', 'Sanierung von Altanlagen', 'Beurteilung von Schadensfällen'],
    hinweise: [
      'Fließregel: in Fließrichtung vom unedleren zum edleren Werkstoff – verzinkter Stahl vor Kupfer, nie danach.',
      'Isolierstücke bzw. Trennstücke zwischen unterschiedlichen Metallen einsetzen.',
      'Fließgeschwindigkeit in Kupferleitungen begrenzen (Dauerbetrieb etwa 2 m/s, Stichleitungen bis 5 m/s).',
      'Heizungsanlagen dicht halten und salzarm befüllen (VDI 2035).',
    ],
    stoerungen: [
      'Braunes Wasser: Rost aus verzinkten Altleitungen',
      'Schwarzer Schlamm in der Heizung: Magnetit durch Sauerstoffeintrag',
      'Grünspan an Kupfer: äußere Feuchtigkeit, meist Kondensat',
    ],
    normen: ['DIN EN 12502', 'DIN 1988-200', 'VDI 2035'],
    verwandt: ['kupferrohr', 'c_stahlrohr', 'heizungswasser', 'trinkwasserhygiene'],
  },

  /* ------------------------------------------------------------ Bauphysik */
  {
    id: 'daemmung_geg',
    begriff: 'Rohrdämmung nach GEG',
    bereich: 'grundlagen',
    kategorie: 'Regelwerk',
    synonyme: ['Isolierung', 'gedämmt', 'Dämmschichtdicke', 'Armaflex', 'Wärmedämmung'],
    kurz: 'Das Gebäudeenergiegesetz schreibt Mindestdämmdicken für wärmeführende Leitungen und Armaturen vor; Kaltwasserleitungen werden gegen Erwärmung und Tauwasser gedämmt.',
    funktion:
      'Die Dämmung begrenzt den Wärmeverlust der Verteilleitungen. Bezugsgröße ist eine Wärmeleitfähigkeit von 0,035 W/(m·K); bei besseren oder schlechteren Dämmstoffen wird die Dicke umgerechnet. Bei Kaltwasser geht es um Hygiene (unter 25 °C halten) und um Tauwasserschutz – dort muss die Dämmung dampfdicht geschlossen sein.',
    aufbau: [
      'Dämmstoffe: PE-Schaum, Mineralwolle, synthetischer Kautschuk (FEF)',
      'Bei Kälte- und Kaltwasserleitungen zusätzlich Dampfsperre, Nähte vollflächig verklebt',
      'Formteile für Bögen, T-Stücke und Armaturen',
    ],
    einsatz: ['Heizungsverteilleitungen', 'Warmwasser- und Zirkulationsleitungen', 'Kaltwasserleitungen', 'Kälteleitungen'],
    hinweise: [
      'Armaturen, Pumpen und Verteiler ebenfalls dämmen (dämmbare Armaturenschalen).',
      'Kalt- und Warmleitungen nicht gemeinsam dämmen und nicht nebeneinander im selben Schacht ungedämmt führen.',
      'Dämmung erst nach bestandener Dichtheitsprüfung schließen.',
    ],
    werte: [
      'Mindestdämmdicke bei λ = 0,035 W/(m·K): bis DN 20 = 20 mm · DN 22 bis 35 = 30 mm · DN 40 bis 100 = gleich dem Innendurchmesser · über DN 100 = 100 mm',
      'In Bauteilen zwischen beheizten Räumen: die Hälfte der Werte',
      'Kaltwasser: Ziel unter 25 °C, in Schächten mit Warmleitungen mindestens 13 mm mit Dampfsperre',
    ],
    formeln: [
      {
        name: 'Umrechnung auf andere Dämmstoffe',
        formel: 'd_neu ≈ d_tab · λ_neu / 0,035',
        erklaerung: 'Näherung für abweichende Wärmeleitfähigkeit; genauer über die Herstellertabelle.',
      },
    ],
    normen: ['GEG Anlage 8', 'DIN 1988-200', 'DIN 4108'],
    verwandt: ['zirkulation', 'trinkwasserhygiene', 'heizungsoptimierung'],
  },
  {
    id: 'brandschutz',
    begriff: 'Brandschutz bei Rohrdurchführungen',
    bereich: 'grundlagen',
    kategorie: 'Sicherheit',
    synonyme: ['Brandschottung', 'Manschette', 'R90', 'Abschottung', 'MLAR'],
    kurz: 'Leitungen, die eine Brandwand oder Geschossdecke durchdringen, müssen so abgeschottet werden, dass Feuer und Rauch nicht übertreten.',
    funktion:
      'Kunststoffrohre schmelzen im Brandfall und hinterlassen eine offene Öffnung. Brandschutzmanschetten enthalten ein Material, das sich unter Hitze stark ausdehnt (intumeszierend) und das Rohr abquetscht. Nicht brennbare Rohre (Guss, Stahl, Kupfer) werden mit Mineralwolle und Brandschutzmasse verschlossen; hier ist zusätzlich die Wärmeleitung zu betrachten.',
    aufbau: ['Brandschutzmanschette R30 bis R120', 'Brandschutzmörtel, -schaum oder -kissen', 'Streckendämmung nach Zulassung', 'Kennzeichnungsschild an jeder Abschottung'],
    einsatz: ['Decken- und Wanddurchbrüche in Treppenhäusern und Fluren', 'Schächte und Installationskanäle', 'Trennwände zwischen Nutzungseinheiten'],
    hinweise: [
      'Nur geprüfte Systeme nach Zulassung einbauen und die Einbauanleitung exakt einhalten.',
      'Abschottung dokumentieren und kennzeichnen (Hersteller, Zulassung, Datum, Firma).',
      'Nachträgliche Leitungen nicht einfach durch eine vorhandene Schottung führen.',
    ],
    normen: ['MLAR (Muster-Leitungsanlagen-Richtlinie)', 'DIN 4102-11', 'DIN EN 1366-3'],
    verwandt: ['rohrbefestigung', 'entwaesserung_grundlagen', 'arbeitssicherheit'],
  },
  {
    id: 'schallschutz',
    begriff: 'Schallschutz in der Sanitärtechnik',
    bereich: 'grundlagen',
    kategorie: 'Regelwerk',
    synonyme: ['DIN 4109', 'Körperschall', 'Geräusche', 'Installationsgeräusch'],
    kurz: 'Geräusche aus Sanitärinstallationen dürfen in fremden schutzbedürftigen Räumen einen Grenzwert nicht überschreiten; entscheidend sind Entkopplung und Masse.',
    funktion:
      'Wasserströmung, Armaturen, Spülkästen und Abflüsse erzeugen Luft- und Körperschall. Körperschall wandert über starre Befestigungen ins Bauwerk und wird in Nachbarräumen wieder als Luftschall abgestrahlt. Wirksam sind: schwere Rohrwerkstoffe (SML, schallgedämmtes PP), elastische Schellen, entkoppelte Vorwandsysteme, geräuscharme Armaturen (Armaturengruppe I) und ausreichende Rohrdurchmesser, damit die Fließgeschwindigkeit sinkt.',
    aufbau: ['Rohrschellen mit Gummieinlage', 'Körperschalldämmende Wandscheiben und Montageelemente', 'Schwere oder mehrschichtige Abflussrohre', 'Vorwandinstallation mit entkoppelten Schienen'],
    einsatz: ['Mehrfamilienhäuser, Hotels, Krankenhäuser', 'Fallleitungen in Wänden zu Aufenthaltsräumen'],
    hinweise: [
      'Fallleitungen nie in einer Wand zum Schlafzimmer führen, wenn es vermeidbar ist.',
      'Mörtelbrücken und starre Kontakte zwischen Rohr und Estrich/Wand vermeiden.',
      'Armaturen der Geräuschgruppe I verwenden; Druckminderer senkt Fließgeräusche.',
    ],
    werte: [
      'DIN 4109: zulässiger Installationsschallpegel in fremden Aufenthaltsräumen 30 dB(A)',
      'Erhöhter Schallschutz (VDI 4100 / DEGA): 25 dB(A) und weniger',
    ],
    normen: ['DIN 4109', 'VDI 4100', 'DIN EN 12056'],
    verwandt: ['sml_rohr', 'rohrbefestigung', 'vorwandinstallation', 'druckminderer'],
  },

  /* ------------------------------------------------------------ Berechnungen */
  {
    id: 'waermeformeln',
    begriff: 'Wärmetechnische Grundformeln',
    bereich: 'grundlagen',
    kategorie: 'Berechnung',
    synonyme: ['Wärmemenge', 'Leistung berechnen', 'Massenstrom', 'Q = m mal c mal delta T', 'Formel Heizung'],
    kurz: 'Mit wenigen Formeln lassen sich Wärmemenge, Leistung, Massenstrom und Aufheizzeit einer Anlage bestimmen.',
    funktion:
      'Grundlage ist die Wärmemenge Q = m · c · ΔT. Daraus folgen Leistung (Wärmemenge je Zeit), der nötige Massenstrom bei gegebener Spreizung und die Aufheizzeit eines Speichers. Für Wasser wird meist mit der spezifischen Wärmekapazität 4,19 kJ/(kg·K) bzw. 1,163 Wh/(kg·K) gerechnet.',
    aufbau: ['Wärmemenge Q', 'Leistung P bzw. Wärmestrom', 'Massenstrom ṁ', 'Temperaturdifferenz (Spreizung) ΔT'],
    einsatz: ['Auslegung von Pumpen und Rohrleitungen', 'Speicherberechnung', 'Kontrolle des hydraulischen Abgleichs', 'Prüfungsaufgaben'],
    formeln: [
      { name: 'Wärmemenge', formel: 'Q = m · c · ΔT', erklaerung: 'Q in kJ, m in kg, c = 4,19 kJ/(kg·K) für Wasser, ΔT in K.' },
      { name: 'Wärmemenge in Wh', formel: 'Q = m · 1,163 · ΔT', erklaerung: 'Ergebnis direkt in Wattstunden – praktischer für Speicher.' },
      { name: 'Leistung', formel: 'P = Q / t', erklaerung: 'P in kW, Q in kJ, t in s. Oder P = ṁ · 1,163 · ΔT mit ṁ in kg/h → P in W.' },
      { name: 'Massenstrom', formel: 'ṁ = P / (1,163 · ΔT)', erklaerung: 'ṁ in kg/h (≈ l/h), P in W, ΔT in K. Beispiel: 10.000 W bei ΔT 15 K → 573 l/h.' },
      { name: 'Aufheizzeit', formel: 't = (m · c · ΔT) / P', erklaerung: 'Zeit in s; für Speicher mit m in kg und P in kW.' },
    ],
    werte: [
      'Wasser: c = 4,19 kJ/(kg·K) = 1,163 Wh/(kg·K)',
      'Dichte Wasser: 1 kg je Liter (bei 4 °C, praktisch gerundet)',
      'Übliche Spreizung: Heizkörper 10–20 K, Fußbodenheizung 5–8 K, Trinkwassererwärmung 30–50 K',
    ],
    normen: ['DIN EN 12831', 'DIN EN 12828', 'VDI 2067'],
    verwandt: ['heizlast', 'hydraulischer_abgleich', 'trinkwassererwaermer'],
  },
  {
    id: 'hydraulikformeln',
    begriff: 'Hydraulische Grundformeln',
    bereich: 'grundlagen',
    kategorie: 'Berechnung',
    synonyme: ['Volumenstrom', 'Fließgeschwindigkeit', 'Druckverlust', 'Rohrreibung', 'Pumpenleistung'],
    kurz: 'Volumenstrom, Fließgeschwindigkeit und Druckverlust hängen über Querschnitt und Rohrreibung zusammen – daraus folgt die Rohrdimension.',
    funktion:
      'Der Volumenstrom ist das Produkt aus Querschnitt und Fließgeschwindigkeit. Der Druckverlust einer Leitung setzt sich aus dem Reibungsanteil in den geraden Strecken (R · l) und den Einzelwiderständen von Formteilen und Armaturen (Z) zusammen. Die Pumpe muss genau diesen Gesamtdruckverlust im ungünstigsten Strang überwinden.',
    aufbau: ['Rohrreibungsdruckgefälle R in Pa/m', 'Einzelwiderstände Z aus Widerstandsbeiwerten ζ', 'Gesamtdruckverlust Δp = Σ(R · l) + Σ Z'],
    einsatz: ['Rohrnetzberechnung Trinkwasser und Heizung', 'Pumpenauswahl', 'Beurteilung von Geräuschen und Unterversorgung'],
    formeln: [
      { name: 'Volumenstrom', formel: 'V̇ = A · v', erklaerung: 'V̇ in m³/s, A = Querschnitt in m², v = Geschwindigkeit in m/s.' },
      { name: 'Querschnitt', formel: 'A = π · d² / 4', erklaerung: 'd = Innendurchmesser in m.' },
      { name: 'Einzelwiderstand', formel: 'Z = ζ · (ρ/2) · v²', erklaerung: 'Z in Pa, ρ = 1000 kg/m³ für Wasser, ζ = Widerstandsbeiwert des Formteils.' },
      { name: 'Gesamtdruckverlust', formel: 'Δp = Σ(R · l) + Σ Z', erklaerung: 'Grundlage für die Förderhöhe der Pumpe.' },
      { name: 'Förderhöhe aus Druck', formel: 'H = Δp / (ρ · g)', erklaerung: '1 bar entspricht etwa 10 m Wassersäule.' },
    ],
    werte: [
      'Empfohlene Fließgeschwindigkeit Trinkwasser: 2 m/s in Verteilleitungen, bis 5 m/s in kurzen Stichleitungen',
      'Heizung: 0,5 bis 1,0 m/s, in Steigleitungen bis 1,5 m/s',
      'Rohrreibungsdruckgefälle Heizung: Richtwert 100 bis 150 Pa/m',
      '1 bar = 100.000 Pa = 10 m Wassersäule',
    ],
    normen: ['DIN 1988-300', 'DIN EN 12828', 'VDI 2073'],
    verwandt: ['rohrnetzberechnung', 'umwaelzpumpe', 'hydraulischer_abgleich'],
  },
  {
    id: 'grundformeln',
    begriff: 'Mathematische Grundlagen im SHK-Handwerk',
    bereich: 'grundlagen',
    kategorie: 'Berechnung',
    synonyme: ['Flächenberechnung', 'Volumen', 'Dreisatz', 'Prozent', 'Wirkungsgrad', 'Steigung'],
    kurz: 'Flächen, Volumen, Gefälle, Prozentrechnung und Wirkungsgrad sind die wiederkehrenden Rechenarten auf der Baustelle und in der Prüfung.',
    funktion:
      'Aus Rohrinnendurchmesser und Länge ergibt sich der Wasserinhalt einer Leitung, aus Raummaßen das Luftvolumen für die Lüftung, aus Höhenunterschied und Länge das Gefälle einer Abwasserleitung. Der Wirkungsgrad setzt Nutzen ins Verhältnis zum Aufwand und zeigt die Verluste einer Anlage.',
    aufbau: ['Kreisfläche und Rohrinhalt', 'Rauminhalt für Luftmengen', 'Gefälle in Prozent und als Verhältnis', 'Wirkungsgrad und Nutzungsgrad'],
    einsatz: ['Wasserinhalt für Ausdehnungsgefäß und Spülung', 'Luftmengen der Wohnungslüftung', 'Gefälle von Grundleitungen', 'Bewertung von Wärmeerzeugern'],
    formeln: [
      { name: 'Rohrinhalt', formel: 'V = π · d² / 4 · l', erklaerung: 'd = Innendurchmesser in m, l = Länge in m, V in m³ (mal 1000 = Liter).' },
      { name: 'Gefälle', formel: 'J = h / l · 100 %', erklaerung: '1 cm je Meter entspricht 1 %; 1:50 entspricht 2 %.' },
      { name: 'Wirkungsgrad', formel: 'η = P_nutz / P_zu', erklaerung: 'Angabe in Prozent; Brennwertgeräte erreichen bezogen auf den Heizwert über 100 %.' },
      { name: 'Prozentrechnung', formel: 'W = G · p / 100', erklaerung: 'Grundwert G, Prozentsatz p, Prozentwert W.' },
    ],
    werte: [
      'Wasserinhalt je Meter (Näherung): 15 x 1,0 mm ≈ 0,13 l · 22 x 1,0 mm ≈ 0,31 l · 28 x 1,5 mm ≈ 0,49 l · 35 x 1,5 mm ≈ 0,80 l',
      'Mindestgefälle Grundleitung: 1:50 (2 %) bei Schmutzwasser üblich, mindestens 0,5 % nach Berechnung',
    ],
    normen: ['DIN 1301 (Einheiten)', 'DIN 1986-100', 'DIN EN 12831'],
    verwandt: ['hydraulikformeln', 'waermeformeln', 'entwaesserung_grundlagen'],
  },
  {
    id: 'elektro_grundlagen',
    begriff: 'Elektrotechnische Grundlagen für SHK',
    bereich: 'grundlagen',
    kategorie: 'Grundlagen',
    synonyme: ['Ohmsches Gesetz', 'Elektro', 'Potentialausgleich', 'FI', 'RCD', 'Schutzleiter'],
    kurz: 'Anlagenmechaniker arbeiten an elektrisch betriebenen Geräten; Grundkenntnisse zu Spannung, Strom, Schutzmaßnahmen und Potentialausgleich sind Pflicht.',
    funktion:
      'Nach dem ohmschen Gesetz hängen Spannung, Strom und Widerstand zusammen; die Leistung ergibt sich aus Spannung mal Strom. Schutz vor gefährlichen Körperströmen bieten Schutzisolierung, Schutzkleinspannung, Schutzleiter mit Überstromschutz und die Fehlerstromschutzeinrichtung (RCD/FI). Metallene Rohrleitungen werden in den Hauptpotentialausgleich einbezogen, damit keine gefährlichen Berührungsspannungen entstehen.',
    aufbau: [
      'Hauptpotentialausgleich an der Haupterdungsschiene',
      'Anschluss von Wasser-, Gas- und Heizungsleitung mit mindestens 6 mm² Kupfer',
      'RCD mit 30 mA für Steckdosenstromkreise und Bäder',
      'Anschluss von Pumpen, Reglern, Heizstäben nach Herstellerplan',
    ],
    einsatz: ['Inbetriebnahme von Kesseln, Wärmepumpen, Pumpen', 'Anschluss von Durchlauferhitzern (durch Elektrofachkraft)', 'Wartung und Störungssuche'],
    hinweise: [
      'Arbeiten an der festen Elektroinstallation sind der Elektrofachkraft vorbehalten; für SHK gilt in der Regel die Berechtigung als elektrotechnisch unterwiesene Person im eigenen Fachbereich.',
      'Fünf Sicherheitsregeln einhalten: freischalten, gegen Wiedereinschalten sichern, Spannungsfreiheit feststellen, erden und kurzschließen, benachbarte Teile abdecken.',
      'Beim Austausch von Metallrohren gegen Kunststoff die Durchgängigkeit des Potentialausgleichs prüfen und wiederherstellen.',
    ],
    formeln: [
      { name: 'Ohmsches Gesetz', formel: 'U = R · I', erklaerung: 'Spannung in V, Widerstand in Ω, Strom in A.' },
      { name: 'Leistung', formel: 'P = U · I', erklaerung: 'Bei Drehstrom: P = √3 · U · I · cos φ.' },
    ],
    werte: ['Netzspannung 230 V / 400 V, 50 Hz', 'RCD-Auslösestrom für Personenschutz: 30 mA', 'Potentialausgleichsleiter mindestens 6 mm² Cu'],
    normen: ['DIN VDE 0100-410', 'DIN VDE 0100-540', 'DGUV Vorschrift 3'],
    verwandt: ['arbeitssicherheit', 'waermepumpe', 'mess_regeltechnik'],
  },

  /* ------------------------------------------------------------ Sicherheit und Beruf */
  {
    id: 'arbeitssicherheit',
    begriff: 'Arbeitssicherheit auf der Baustelle',
    bereich: 'grundlagen',
    kategorie: 'Sicherheit',
    synonyme: ['PSA', 'Unfallverhütung', 'DGUV', 'Gefährdungsbeurteilung', 'Schutzausrüstung'],
    kurz: 'Jede Tätigkeit wird vor Beginn beurteilt; Schutzmaßnahmen und persönliche Schutzausrüstung richten sich nach der Gefährdung.',
    funktion:
      'Grundlage ist die Gefährdungsbeurteilung des Arbeitgebers. Maßnahmen werden nach dem TOP-Prinzip gewählt: zuerst technisch (Absturzsicherung, Absaugung), dann organisatorisch (Unterweisung, Arbeitsfreigabe), zuletzt persönlich (PSA). Auszubildende dürfen gefährliche Arbeiten nur unter Aufsicht ausführen.',
    aufbau: [
      'Grund-PSA: Sicherheitsschuhe S3, Arbeitshandschuhe, Schutzbrille, Gehörschutz',
      'Zusätzlich: Helm, Staubmaske/FFP, Schweißerschutz, Auffanggurt',
      'Erlaubnisschein für Heißarbeiten mit Brandwache und Nachkontrolle',
      'Leitern und Gerüste nach Prüfprotokoll, ab 2 m Absturzhöhe sichern',
    ],
    einsatz: ['Alle Montage-, Trenn-, Löt- und Schweißarbeiten', 'Arbeiten in Schächten und engen Räumen', 'Umgang mit Altanlagen'],
    hinweise: [
      'Vor dem Trennen und Öffnen: Anlagenteil absperren, entleeren, drucklos machen und gegen Wiedereinschalten sichern.',
      'Heißarbeiten: brennbare Stoffe entfernen, Löschmittel bereitstellen, Nachkontrolle nach mehreren Stunden.',
      'Gasgeruch: nicht schalten, keine offene Flamme, Hauptabsperreinrichtung schließen, lüften, Räume verlassen, Netzbetreiber anrufen.',
      'Unfälle und Beinaheunfälle melden, Verbandbuch führen.',
    ],
    normen: ['DGUV Vorschrift 1', 'Arbeitsschutzgesetz', 'Betriebssicherheitsverordnung', 'TRBS'],
    verwandt: ['gefahrstoffe', 'weichloeten', 'gasinstallation'],
  },
  {
    id: 'gefahrstoffe',
    begriff: 'Gefahrstoffe im SHK-Handwerk',
    bereich: 'grundlagen',
    kategorie: 'Sicherheit',
    synonyme: ['Asbest', 'KMF', 'Mineralwolle', 'Lötrauch', 'Gefahrstoffverordnung', 'TRGS'],
    kurz: 'Bei Arbeiten im Bestand treten Asbest, alte Mineralwolle, Lötrauche, Reinigungs- und Kältemittel auf – für jeden Stoff gelten eigene Schutzmaßnahmen.',
    funktion:
      'Vor Arbeiten im Bestand ist zu ermitteln, ob Gefahrstoffe vorliegen. Asbest findet sich in alten Kesseldichtungen, Rohrisolierungen, Flanschdichtungen und Bodenbelägen. Alte künstliche Mineralfasern (vor 1996) gelten als krebsverdächtig. Beim Löten und Schweißen entstehen Rauche, die abgesaugt oder durch Lüftung entfernt werden müssen. Kältemittel unterliegen zusätzlich der F-Gase-Verordnung.',
    aufbau: [
      'Sicherheitsdatenblatt und Betriebsanweisung je Stoff',
      'Persönliche Schutzausrüstung: Atemschutz FFP2/FFP3, Schutzanzug, Handschuhe',
      'Abfallentsorgung getrennt und dokumentiert',
    ],
    einsatz: ['Demontage von Altanlagen', 'Kesseltausch', 'Arbeiten an alten Dämmungen'],
    hinweise: [
      'Asbestverdacht: Arbeiten sofort einstellen, Vorgesetzten informieren; Sanierung nur durch Fachbetriebe nach TRGS 519.',
      'Alte Mineralwolle nicht trocken abreißen – anfeuchten, Staub vermeiden, in dichten Säcken entsorgen.',
      'Beim Löten ausreichend lüften, Lötrauch nicht einatmen.',
      'Kältemittel dürfen nur von zertifizierten Personen abgesaugt werden (Sachkundenachweis Kategorie I–IV).',
    ],
    normen: ['Gefahrstoffverordnung', 'TRGS 519 (Asbest)', 'TRGS 521 (Faserstäube)', 'F-Gase-Verordnung (EU) 517/2014'],
    verwandt: ['arbeitssicherheit', 'kaeltetechnik'],
  },
  {
    id: 'berichtsheft_wissen',
    begriff: 'Berichtsheft (Ausbildungsnachweis)',
    bereich: 'grundlagen',
    kategorie: 'Grundlagen',
    synonyme: ['Ausbildungsnachweis', 'Wochenbericht', 'Berichtsheft führen'],
    kurz: 'Der Ausbildungsnachweis dokumentiert Tätigkeiten, Unterweisungen und Berufsschulinhalte; er ist Zulassungsvoraussetzung zur Gesellenprüfung.',
    funktion:
      'Der Nachweis wird laufend während der Ausbildungszeit geführt – wöchentlich oder täglich, schriftlich oder elektronisch. Er wird vom Auszubildenden und vom Ausbilder regelmäßig unterschrieben. Inhaltlich gehören betriebliche Tätigkeiten, betriebliche Unterweisungen und die Themen des Berufsschulunterrichts hinein. Der Betrieb stellt die Zeit zur Verfügung.',
    aufbau: [
      'Angabe von Woche, Datum und Ausbildungsjahr',
      'Tätigkeiten mit Fachbegriffen, nicht umgangssprachlich',
      'Unterweisungen und Lehrgänge (z. B. überbetriebliche Ausbildung)',
      'Berufsschulthemen der Woche',
      'Unterschriften von Auszubildendem und Ausbilder',
    ],
    einsatz: ['Gesamte Ausbildungszeit', 'Vorlage bei der Kammer zur Prüfungszulassung'],
    hinweise: [
      'Fachsprache verwenden: nicht „Rohre verlegt“, sondern „Montage der Abflussleitung DN 100 aus SML“.',
      'Stichpunkte sind erlaubt, sie müssen aber verständlich und nachvollziehbar sein.',
      'Lücken vermeiden – fehlende Nachweise können die Prüfungszulassung verzögern.',
    ],
    normen: ['Berufsbildungsgesetz § 13 und § 43', 'Ausbildungsordnung Anlagenmechaniker/-in SHK'],
    verwandt: ['gesellenpruefung'],
  },
  {
    id: 'gesellenpruefung',
    begriff: 'Gesellenprüfung Anlagenmechaniker SHK',
    bereich: 'grundlagen',
    kategorie: 'Grundlagen',
    synonyme: ['Abschlussprüfung', 'Prüfung Teil 1', 'Prüfung Teil 2', 'gestreckte Prüfung'],
    kurz: 'Die Ausbildung endet mit einer gestreckten Gesellenprüfung: Teil 1 im zweiten Ausbildungsjahr, Teil 2 am Ende – beide zählen in die Endnote.',
    funktion:
      'Teil 1 prüft die Grundfertigkeiten (Arbeitsaufgabe mit Fertigung und begleitendem Fachgespräch sowie schriftliche Aufgaben) und geht mit einem festgelegten Anteil in das Gesamtergebnis ein. Teil 2 besteht aus einem betrieblichen Auftrag oder einer Arbeitsaufgabe mit Dokumentation und Fachgespräch sowie schriftlichen Prüfungsbereichen wie Anlagenanalyse, Kundenauftrag und Wirtschafts- und Sozialkunde.',
    aufbau: [
      'Teil 1: praktische Arbeitsaufgabe und schriftliche Aufgabenstellung',
      'Teil 2 praktisch: betrieblicher Auftrag mit Dokumentation und Fachgespräch',
      'Teil 2 schriftlich: Anlagenanalyse, Kundenauftrag, Wirtschafts- und Sozialkunde',
    ],
    einsatz: ['Prüfungsvorbereitung', 'Dokumentation des betrieblichen Auftrags', 'Fachberichte als Übung für das Fachgespräch'],
    hinweise: [
      'Der Fachbericht zum betrieblichen Auftrag verlangt Begründungen: warum dieses Material, diese Verbindungstechnik, diese Reihenfolge.',
      'Skizzen und Schemata erhöhen die Nachvollziehbarkeit deutlich.',
      'Auf Normbezug und Arbeitssicherheit achten – beides wird regelmäßig bewertet.',
    ],
    normen: ['Ausbildungsordnung Anlagenmechaniker/-in für Sanitär-, Heizungs- und Klimatechnik', 'Handwerksordnung'],
    verwandt: ['berichtsheft_wissen', 'dichtheitspruefung', 'heizlast'],
  },
];
