/**
 * Fachdatenbank – Heizungstechnik: Wärmeerzeuger, Hydraulik, Wärmeübergabe,
 * Regelung, Wasserqualität und Inbetriebnahme.
 */

export const HEIZUNG = [
  /* ------------------------------------------------------------ Grundlagen */
  {
    id: 'heizungsanlage',
    begriff: 'Aufbau einer Heizungsanlage',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['Heizung', 'Heizsystem', 'Wärmeerzeugung', 'geschlossene Anlage'],
    kurz: 'Eine Warmwasserheizung besteht aus Wärmeerzeugung, Verteilung, Übergabe und Regelung – als geschlossenes System mit Sicherheitseinrichtungen.',
    funktion:
      'Der Wärmeerzeuger erwärmt das Heizwasser, die Umwälzpumpe fördert es durch das Rohrnetz zu den Heizflächen, dort wird Wärme an den Raum abgegeben, und das abgekühlte Wasser fließt zurück. Die Differenz zwischen Vor- und Rücklauftemperatur ist die Spreizung; sie bestimmt zusammen mit der Leistung den nötigen Massenstrom. Geschlossene Anlagen sind gegen Überdruck (Sicherheitsventil), gegen Volumenänderung (Ausdehnungsgefäß) und gegen Übertemperatur (Regel- und Sicherheitstemperaturbegrenzer) abgesichert.',
    aufbau: [
      'Wärmeerzeuger: Brennwertgerät, Wärmepumpe, Pellet-, Öl- oder Fernwärmeübergabestation',
      'Sicherheitstechnik: Sicherheitsventil, Ausdehnungsgefäß, Manometer, Entlüftung, STB',
      'Verteilung: Rohrnetz, Umwälzpumpe, Verteiler, Mischer, Absperr- und Regulierarmaturen',
      'Übergabe: Heizkörper oder Flächenheizung mit Thermostatventilen',
      'Regelung: witterungsgeführt mit Außenfühler, Raumthermostaten, Zeitprogramm',
    ],
    einsatz: ['Wohn-, Gewerbe- und öffentliche Gebäude'],
    hinweise: [
      'Niedrige Systemtemperaturen erhöhen den Wirkungsgrad jedes Erzeugers – besonders bei Brennwert und Wärmepumpe.',
      'Rücklauftemperatur ist die wichtigste Stellgröße für Effizienz: je kälter, desto besser.',
      'Anlage dicht halten – jede Nachspeisung bringt Sauerstoff und Härtebildner ins System.',
    ],
    werte: [
      'Auslegungstemperaturen: Bestand 75/65 °C, saniert 55/45 °C, Wärmepumpe 35/28 °C',
      'Spreizung: Heizkörper 10 bis 20 K, Fußbodenheizung 5 bis 8 K',
      'Anlagendruck Einfamilienhaus: 1,5 bis 2,0 bar kalt',
    ],
    normen: ['DIN EN 12828', 'DIN EN 12831', 'VDI 2035', 'GEG'],
    verwandt: ['heizlast', 'sicherheitsventil', 'ausdehnungsgefaess', 'umwaelzpumpe', 'heizkurve'],
  },
  {
    id: 'heizlast',
    begriff: 'Heizlastberechnung',
    bereich: 'heizung',
    kategorie: 'Berechnung',
    synonyme: ['DIN EN 12831', 'Wärmebedarf', 'Norm-Heizlast', 'Raumheizlast'],
    kurz: 'Die Heizlast ist die Wärmeleistung, die ein Raum bei Norm-Außentemperatur benötigt, um die gewünschte Innentemperatur zu halten.',
    funktion:
      'Die Norm-Heizlast setzt sich aus Transmissionswärmeverlusten durch Bauteile und Lüftungswärmeverlusten durch Luftwechsel zusammen. Für jedes Bauteil wird der U-Wert mit der Fläche und der Temperaturdifferenz multipliziert; Wärmebrücken werden pauschal oder detailliert berücksichtigt. Der Lüftungsanteil ergibt sich aus Raumvolumen, Luftwechselrate und Temperaturdifferenz. Die Summe aller Raumheizlasten ergibt die Gebäudeheizlast und damit die Erzeugerleistung.',
    aufbau: ['Transmissionsanteil je Bauteil (Wand, Fenster, Dach, Boden)', 'Lüftungsanteil aus Luftwechsel', 'Zuschlag für Wärmebrücken', 'ggf. Aufheizzuschlag bei Nachtabsenkung'],
    einsatz: ['Auslegung von Wärmeerzeuger und Heizflächen', 'Grundlage des hydraulischen Abgleichs', 'Förderanträge und Energieberatung'],
    hinweise: [
      'Erzeugerleistung nicht pauschal aufrunden – überdimensionierte Kessel takten und arbeiten ineffizient.',
      'Bei Wärmepumpen zusätzlich die Warmwasserbereitung und Sperrzeiten des Netzbetreibers berücksichtigen.',
      'Raumweise rechnen; nur so lässt sich später abgleichen.',
    ],
    formeln: [
      { name: 'Transmission', formel: 'Φ_T = Σ (U · A) · (θ_i − θ_e)', erklaerung: 'U in W/(m²·K), A in m², Temperaturen in °C.' },
      { name: 'Lüftung', formel: 'Φ_V = 0,34 · n · V · (θ_i − θ_e)', erklaerung: '0,34 Wh/(m³·K) für Luft, n = Luftwechsel je Stunde, V = Raumvolumen in m³.' },
      { name: 'Raumheizlast', formel: 'Φ_HL = Φ_T + Φ_V', erklaerung: 'Ergebnis in Watt.' },
    ],
    werte: [
      'Norm-Außentemperatur in Deutschland: −10 bis −16 °C je nach Region',
      'Norm-Innentemperatur: Wohnraum 20 °C, Bad 24 °C, Schlafzimmer 20 °C, Flur 15 °C',
      'Spezifische Heizlast: Passivhaus 10–15 W/m² · Neubau GEG 30–50 W/m² · Bestand teilsaniert 60–100 W/m² · unsaniert 100–150 W/m²',
      'Luftwechsel: Mindestwert 0,5 1/h, Bad 1,5 1/h',
    ],
    normen: ['DIN EN 12831-1', 'DIN/TS 12831-1 (nationaler Anhang)', 'GEG'],
    verwandt: ['hydraulischer_abgleich', 'heizkoerper', 'waermeformeln', 'fussbodenheizung'],
  },

  /* ------------------------------------------------------------ Wärmeerzeuger */
  {
    id: 'brennwert',
    begriff: 'Gas-Brennwertgerät',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['Brennwertkessel', 'Therme', 'Gastherme', 'Brennwerttechnik', 'Heizkessel'],
    kurz: 'Das Brennwertgerät nutzt zusätzlich zur Verbrennungswärme die Kondensationswärme des im Abgas enthaltenen Wasserdampfs.',
    funktion:
      'Bei der Verbrennung von Erdgas entstehen Kohlendioxid und Wasserdampf. Wird das Abgas im Wärmeübertrager unter den Wasserdampftaupunkt abgekühlt, kondensiert der Dampf und gibt dabei seine latente Wärme (Verdampfungsenthalpie) an das Heizwasser ab. Voraussetzung ist eine niedrige Rücklauftemperatur – deshalb bringt Brennwerttechnik in Verbindung mit Flächenheizung den größten Gewinn. Der Brenner moduliert, passt die Leistung also stufenlos an den Bedarf an.',
    aufbau: [
      'Modulierender Vormischbrenner mit drehzahlgeregeltem Gebläse',
      'Brennwert-Wärmeübertrager aus Edelstahl oder Aluminium-Silizium',
      'Kondensatablauf mit Siphon, ggf. Neutralisation',
      'Konzentrische Abgasleitung (LAS) für raumluftunabhängigen Betrieb',
      'Regelung mit witterungsgeführter Heizkurve, Sicherheitstemperaturbegrenzer, Abgasüberwachung',
    ],
    einsatz: ['Ein- und Mehrfamilienhäuser', 'Modernisierung alter Heizwertkessel', 'Kombination mit Solarthermie'],
    hinweise: [
      'Rücklauftemperatur unter dem Taupunkt halten, sonst bleibt der Brennwertnutzen aus.',
      'Hydraulische Weiche oder Puffer nur einsetzen, wenn nötig – sie heben die Rücklauftemperatur an.',
      'Kondensat über den Siphon ableiten, Siphon vor Inbetriebnahme mit Wasser füllen.',
      'Inbetriebnahme mit Messung von CO, CO₂ bzw. O₂, Abgastemperatur und Gasdruck dokumentieren.',
      'Abgasführung nur mit zugelassenen, feuchteunempfindlichen Systemen; Abnahme durch den Schornsteinfeger.',
    ],
    stoerungen: [
      'Gerät startet nicht: Gasdruck zu niedrig, Kondensatsiphon verstopft (Abgasdruckwächter löst aus), Zündelektrode verschmutzt',
      'Häufiges Takten: Leistung zu groß, Volumenstrom zu klein, Überströmventil falsch eingestellt',
      'Kein Brennwertnutzen: Rücklauf zu heiß, Heizkurve zu steil, Überströmventil offen',
    ],
    werte: [
      'Wasserdampftaupunkt Erdgas etwa 57 °C, Heizöl EL etwa 47 °C',
      'Normnutzungsgrad bezogen auf den Heizwert bis etwa 109 %',
      'Kondensatanfall: etwa 1,5 l je m³ verbranntem Erdgas',
      'Kondensat-pH etwa 3,5 bis 5',
    ],
    normen: ['DVGW-TRGI G 600', 'DIN EN 15502', '1. BImSchV', 'ATV-A 251 (Kondensat)'],
    verwandt: ['abgasanlage', 'kondensat', 'gasinstallation', 'heizkurve', 'heizungsanlage'],
  },
  {
    id: 'waermepumpe',
    begriff: 'Wärmepumpe',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['WP', 'Luftwärmepumpe', 'Sole-Wasser-Wärmepumpe', 'Erdwärme', 'Luft-Wasser'],
    kurz: 'Die Wärmepumpe hebt Umweltwärme mit elektrischer Antriebsenergie auf ein nutzbares Temperaturniveau.',
    funktion:
      'Im Kältekreis verdampft ein Kältemittel bei niedrigem Druck und nimmt dabei Wärme aus Luft, Erdreich oder Grundwasser auf. Der Verdichter erhöht Druck und Temperatur. Im Verflüssiger gibt das Kältemittel die Wärme an das Heizwasser ab und wird flüssig. Das Expansionsventil entspannt es zurück auf Verdampfungsdruck. Die Leistungszahl COP beschreibt das Verhältnis von Heizleistung zu elektrischer Aufnahme im Prüfpunkt, die Jahresarbeitszahl JAZ den realen Jahresdurchschnitt.',
    aufbau: [
      'Verdampfer (Luftregister, Sole- oder Wasserwärmeübertrager)',
      'Verdichter, meist invertergeregelt (Scroll)',
      'Verflüssiger zum Heizkreis',
      'Expansionsventil, Sammler, Filtertrockner',
      'Pufferspeicher bzw. Reihenpuffer, Heizstab für Spitzenlast und Legionellenschaltung',
    ],
    einsatz: [
      'Neubau mit Flächenheizung',
      'Sanierung mit abgesenkten Systemtemperaturen (Heizkörper tauschen oder vergrößern)',
      'Bivalent mit bestehendem Kessel im Bestand',
    ],
    hinweise: [
      'Jedes Kelvin geringere Vorlauftemperatur verbessert die Jahresarbeitszahl um etwa 2 bis 2,5 %.',
      'Mindestvolumenstrom und Mindestwasserinhalt sicherstellen (Pufferspeicher, Überströmventil nur wenn nötig).',
      'Sperrzeiten des Netzbetreibers berücksichtigen (üblich 3 x 2 Stunden am Tag).',
      'Aufstellort der Außeneinheit schalltechnisch prüfen (Nachbarschaft, TA Lärm) und Kondensat frostfrei ableiten.',
      'Arbeiten am Kältekreis nur mit Sachkundenachweis nach F-Gase-Verordnung.',
    ],
    stoerungen: [
      'Hochdruckstörung: Volumenstrom zu klein, Schmutzfänger zu, Luft im System',
      'Vereisung des Verdampfers: Abtauung gestört, Lüfter oder Sensorik defekt',
      'Schlechte JAZ: Vorlauftemperatur zu hoch, Heizstab läuft zu häufig, Hydraulik falsch',
    ],
    werte: [
      'COP Luft/Wasser bei A2/W35: etwa 4,0 bis 5,0',
      'Angestrebte JAZ: 3,5 bis 4,5 (Luft), 4,0 bis 5,0 (Sole)',
      'Sole-Entzugsleistung Erdsonde: etwa 35 bis 55 W je Meter je nach Untergrund',
      'Typische Vorlauftemperatur: 30 bis 40 °C Flächenheizung, bis 55 °C mit Hochtemperaturgeräten',
    ],
    formeln: [
      { name: 'Leistungszahl', formel: 'COP = Q_Heiz / P_el', erklaerung: 'Momentanwert im Prüfpunkt.' },
      { name: 'Jahresarbeitszahl', formel: 'JAZ = Q_Jahr / W_Jahr', erklaerung: 'Nutzwärme geteilt durch Stromverbrauch über das Jahr.' },
    ],
    normen: ['DIN EN 14511', 'VDI 4645', 'VDI 4640 (Erdwärme)', 'GEG', 'F-Gase-Verordnung'],
    verwandt: ['pufferspeicher', 'fussbodenheizung', 'kaeltetechnik', 'hydraulischer_abgleich', 'heizkurve'],
  },
  {
    id: 'oelheizung',
    begriff: 'Öl-Brennwertheizung und Tankanlage',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['Ölheizung', 'Heizöl', 'Öltank', 'Ölbrenner'],
    kurz: 'Ölheizungen verbrennen Heizöl EL im Gebläsebrenner; die Lagerung unterliegt strengen Anforderungen an Auffangraum und Überfüllsicherung.',
    funktion:
      'Die Ölpumpe fördert Heizöl über Filter und Vorwärmer zur Düse, wo es fein zerstäubt und mit Gebläseluft gemischt wird. Die Zündelektroden entzünden das Gemisch, die Flammenüberwachung sichert den Betrieb. Brennwertgeräte kühlen das Abgas unter den Taupunkt von etwa 47 °C ab; dafür ist schwefelarmes Heizöl erforderlich.',
    aufbau: [
      'Öltank mit Auffangwanne oder doppelwandig, Grenzwertgeber, Leckanzeige',
      'Ölleitung als Einstrangsystem mit Filter und Entlüfter',
      'Gebläsebrenner mit Düse, Zündelektroden, Flammenwächter',
      'Brennwert-Wärmeübertrager, Kondensatableitung',
    ],
    einsatz: ['Gebäude ohne Gasanschluss', 'Bestandsmodernisierung, häufig hybrid mit Wärmepumpe oder Solar'],
    hinweise: [
      'Tankanlage: Grenzwertgeber, Überfüllsicherung und Auffangraum sind Pflicht; Prüfpflichten nach AwSV beachten.',
      'Nur schwefelarmes Heizöl EL für Brennwertbetrieb verwenden.',
      'Jährliche Wartung: Düse tauschen, Elektroden einstellen, Filter wechseln, Abgasmessung.',
      'Neuinstallationen unterliegen den Einbaubeschränkungen des GEG – Beratungspflicht beachten.',
    ],
    werte: ['Heizwert Heizöl EL: etwa 10 kWh je Liter', 'Düsenleistung: 1 kg/h Öl ≈ 11,9 kW', 'Abgastaupunkt etwa 47 °C'],
    normen: ['1. BImSchV', 'AwSV', 'DIN EN 267', 'TRÖl'],
    verwandt: ['brennwert', 'abgasanlage', 'heizungsanlage'],
  },
  {
    id: 'biomasse',
    begriff: 'Pellet- und Scheitholzheizung',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['Pelletheizung', 'Holzheizung', 'Scheitholzkessel', 'Biomasse', 'Hackschnitzel'],
    kurz: 'Biomassekessel verbrennen Holzpellets, Scheitholz oder Hackschnitzel; sie brauchen immer einen ausreichend großen Pufferspeicher.',
    funktion:
      'Pelletkessel fördern den Brennstoff automatisch über Schnecke oder Saugsystem in den Brennteller und regeln über Luftklappen und Lambdasonde. Scheitholzkessel arbeiten als Holzvergaser: In der Füllkammer entgast das Holz, die Gase werden in der darunterliegenden Brennkammer mit Sekundärluft verbrannt. Da sich der Abbrand nicht stoppen lässt, muss die freiwerdende Wärme in einen Pufferspeicher abgeführt werden.',
    aufbau: [
      'Brennstofflager mit Förderung (Schnecke, Saugsystem)',
      'Kessel mit Brennkammer, Lambdaregelung und automatischer Entaschung',
      'Pufferspeicher, Rücklaufanhebung, thermische Ablaufsicherung bei Scheitholz',
      'Abgasanlage mit Zugregler und ggf. Staubabscheider',
    ],
    einsatz: ['Ländlicher Raum, Objekte mit Lagerraum', 'Ersatz von Öl- und alten Festbrennstoffkesseln'],
    hinweise: [
      'Pufferspeicher: Richtwert 30 bis 50 l je kW bei Pellets, 55 bis 100 l je kW bei Scheitholz.',
      'Rücklaufanhebung (mindestens 55 bis 60 °C) schützt den Kessel vor Taupunktkorrosion.',
      'Staubgrenzwerte der 1. BImSchV einhalten, Messung durch den Schornsteinfeger.',
      'Brennstofflager trocken halten und Sicherheitsregeln zum CO-Risiko beachten.',
    ],
    werte: ['Heizwert Pellets: etwa 5 kWh je kg (4,8–5,3)', 'Lagerbedarf: etwa 0,9 m³ je 1000 kg Pellets', 'Aschegehalt Pellets unter 0,7 %'],
    normen: ['1. BImSchV', 'DIN EN 303-5', 'ENplus (Pelletqualität)', 'DIN EN ISO 17225'],
    verwandt: ['pufferspeicher', 'abgasanlage', 'heizungsanlage'],
  },
  {
    id: 'solarthermie',
    begriff: 'Solarthermie',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['Solaranlage', 'Kollektor', 'Solarkreis', 'Solarstation'],
    kurz: 'Solarthermie wandelt Sonnenstrahlung in Wärme für Trinkwassererwärmung und Heizungsunterstützung.',
    funktion:
      'Im Kollektor erwärmt die absorbierte Strahlung ein Wasser-Glykol-Gemisch. Die Regelung vergleicht Kollektor- und Speichertemperatur und schaltet die Solarpumpe ein, sobald die Differenz groß genug ist. Über einen Wärmeübertrager im unteren Speicherbereich wird die Wärme abgegeben. Bei Stagnation (Speicher voll, Pumpe aus) verdampft das Medium im Kollektor – die Anlage muss diesen Zustand aushalten.',
    aufbau: [
      'Flach- oder Vakuumröhrenkollektor',
      'Solarkreis aus Kupfer oder Edelstahlwellrohr mit FKM-Dichtungen',
      'Solarstation mit Pumpe, Sicherheitsventil, Manometer, Durchflussmesser, Entlüfter',
      'Solar-Ausdehnungsgefäß mit Vorschaltgefäß',
      'Bivalenter Speicher mit zwei Wärmeübertragern',
    ],
    einsatz: ['Trinkwassererwärmung (Deckungsgrad 50 bis 60 % im Jahr)', 'Heizungsunterstützung', 'Kombianlagen mit Pufferspeicher'],
    hinweise: [
      'Nur temperaturbeständige Werkstoffe verwenden – keine EPDM-Dichtungen, kein Kunststoffrohr im Kollektorkreis.',
      'Wärmeträger regelmäßig prüfen (Frostschutz, pH-Wert), meist alle zwei Jahre.',
      'Anlage so auslegen, dass Stagnation schadlos möglich ist (Dampfvolumen im Ausdehnungsgefäß).',
      'Kollektorfläche Richtwert: 1,2 bis 1,5 m² je Person für Warmwasser.',
    ],
    werte: [
      'Ertrag: etwa 350 bis 500 kWh je m² und Jahr',
      'Stagnationstemperatur Flachkollektor: über 200 °C',
      'Volumenstrom Low-Flow: etwa 15 bis 25 l/(m²·h)',
      'Frostschutz bis etwa −25 °C',
    ],
    normen: ['DIN EN 12975', 'DIN EN 12976', 'VDI 6002', 'DIN 4757'],
    verwandt: ['trinkwassererwaermer', 'pufferspeicher', 'ausdehnungsgefaess', 'dichtstoffe'],
  },

  /* ------------------------------------------------------------ Sicherheitstechnik */
  {
    id: 'sicherheitsventil',
    begriff: 'Sicherheitsventil',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['SV', 'Überdruckventil', 'Sicherheitsarmatur'],
    kurz: 'Das Sicherheitsventil ist die letzte Schutzeinrichtung gegen unzulässigen Überdruck in Heizungsanlagen und Trinkwassererwärmern.',
    funktion:
      'Ein federbelasteter Ventilkegel wird durch den Anlagendruck gegen die Feder gedrückt. Erreicht der Druck den Ansprechdruck, hebt der Kegel vom Sitz ab und lässt so viel Medium ab, dass der Druck nicht weiter steigt. Nach dem Druckabfall schließt die Feder das Ventil wieder. Zwischen Sicherheitsventil und dem zu schützenden Bauteil darf keine Absperrung liegen.',
    aufbau: ['Gehäuse mit Ein- und Austritt', 'Ventilkegel mit Weichdichtung und Sitz', 'Einstellfeder mit festem Ansprechdruck', 'Anlüftvorrichtung zur Funktionsprüfung', 'Abblaseleitung mit freiem, beobachtbarem Auslauf'],
    einsatz: [
      'Geschlossene Heizungsanlage: meist 2,5 oder 3,0 bar',
      'Trinkwassererwärmer: 6 bar (bis 200 l) oder 10 bar',
      'Solarkreis: 6 bar',
    ],
    hinweise: [
      'Abblaseleitung mit Gefälle, frostfrei und offen in einen Trichtersiphon führen; Querschnitt nicht verringern.',
      'Schild anbringen: „Während der Beheizung kann aus Sicherheitsgründen Wasser austreten“.',
      'Funktion mindestens jährlich durch Anlüften prüfen.',
      'Ansprechdruck immer über dem höchsten Betriebsdruck, aber unter dem zulässigen Druck der Bauteile wählen.',
    ],
    stoerungen: [
      'Ventil tropft dauerhaft: Ausdehnungsgefäß defekt oder zu klein, Vordruck falsch, Sitz verschmutzt',
      'Ventil bläst bei jeder Aufheizung ab: Anlagendruck zu hoch eingestellt',
      'Ventil öffnet nicht: verkalkt oder festsitzend – austauschen',
    ],
    werte: ['Heizung bis 50 kW: SV mindestens R 1/2, Abblaseleitung mindestens DN 20', 'Enddruck der Anlage: bei SV ≤ 3 bar gilt p_e = p_SV − 0,5 bar'],
    normen: ['DIN EN 1489', 'DIN EN ISO 4126', 'DIN EN 12828', 'DIN 4753'],
    verwandt: ['ausdehnungsgefaess', 'trinkwassererwaermer', 'heizungsanlage', 'druckminderer'],
  },
  {
    id: 'ausdehnungsgefaess',
    begriff: 'Membran-Ausdehnungsgefäß (MAG)',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['MAG', 'Ausdehnungsgefäss', 'Ausgleichsgefäß', 'Expansionsgefäß'],
    kurz: 'Das MAG nimmt die Volumenänderung des Heizwassers bei Erwärmung auf und hält den Anlagendruck in engen Grenzen.',
    funktion:
      'Eine Membran trennt das Wasser von einem mit Stickstoff vorgespannten Gasraum. Erwärmt sich das Anlagenwasser, dehnt es sich aus, strömt in das Gefäß und komprimiert das Gaspolster. Beim Abkühlen drückt das Gaspolster das Wasser zurück. Die Wasservorlage stellt sicher, dass auch bei Leckverlusten noch Wasser im Gefäß ist und der Mindestdruck nicht unterschritten wird.',
    aufbau: ['Stahlbehälter mit Butylmembran', 'Gasraum mit Ventil zum Einstellen des Vordrucks', 'Wasseranschluss mit Kappenventil (KFE) zur Prüfung', 'bei Trinkwasser: durchströmtes, trinkwassergeeignetes Gefäß'],
    einsatz: ['Geschlossene Heizungsanlagen', 'Trinkwassererwärmer', 'Solar- und Kühlkreise (dort mit Vorschaltgefäß bzw. geeigneter Membran)'],
    hinweise: [
      'Vordruck immer drucklos prüfen: Anlage wasserseitig am KFE entlasten, dann am Gasventil messen.',
      'Vordruck einstellen auf statische Höhe geteilt durch 10 plus 0,3 bar (Mindestdruck).',
      'Fülldruck etwa 0,3 bar über dem Vordruck einstellen.',
      'Gefäß über eine Kappenventil-Verbindung anschließen, damit es prüfbar und tauschbar bleibt.',
      'Bei Wärmepumpen und Solaranlagen größere Gefäße wegen größerer Temperaturspanne.',
    ],
    stoerungen: [
      'Sicherheitsventil bläst beim Aufheizen ab: MAG zu klein, Vordruck zu hoch oder Membran defekt',
      'Druck fällt beim Abkühlen unter den Mindestdruck: zu wenig Wasservorlage oder Leckage',
      'Wasser tritt am Gasventil aus: Membran gerissen – Gefäß tauschen',
    ],
    formeln: [
      { name: 'Vordruck', formel: 'p_0 = h_st / 10 + 0,3 bar', erklaerung: 'h_st = statische Höhe in Metern über dem MAG.' },
      { name: 'Ausdehnungsvolumen', formel: 'V_e = V_A · n', erklaerung: 'V_A = Anlagenwasserinhalt, n = Ausdehnungskoeffizient (bei 70 °C etwa 0,0233).' },
      {
        name: 'Nenninhalt MAG',
        formel: 'V_n = (V_e + V_v) · (p_e + 1) / (p_e − p_0)',
        erklaerung: 'V_v = Wasservorlage (0,5 % des Anlageninhalts, mindestens 3 l), p_e = Enddruck, p_0 = Vordruck – alle Drücke als Überdruck in bar.',
      },
    ],
    werte: [
      'Ausdehnung von Wasser (ab 10 °C): bei 50 °C ≈ 1,2 % · 70 °C ≈ 2,3 % · 90 °C ≈ 3,6 %',
      'Wasservorlage: 0,5 % des Anlagenvolumens, mindestens 3 Liter',
      'Anlagenwasserinhalt Richtwert: 10 bis 15 l je kW bei Heizkörpern',
    ],
    normen: ['DIN EN 12828', 'DIN 4807-2', 'DIN 4753 (Trinkwasser)'],
    verwandt: ['sicherheitsventil', 'heizungsanlage', 'heizungswasser'],
    vertiefungen: [
      {
        frage: 'Wie prüfe ich den Vordruck richtig?',
        text: 'Der Vordruck lässt sich nur im drucklosen Zustand richtig messen. Dazu wird das Kappenventil zwischen Anlage und Gefäß geschlossen und das Gefäß wasserseitig über die Entleerung entlastet, bis kein Wasser mehr austritt. Erst dann zeigt das Manometer am Gasventil den tatsächlichen Vordruck. Sollwert ist die statische Höhe geteilt durch zehn plus 0,3 bar – bei 10 m Höhe also 1,3 bar. Fehlender Stickstoff wird über das Ventil ergänzt, zu hoher Druck abgelassen. Danach Kappenventil öffnen und den Anlagendruck auf etwa 0,3 bar über dem Vordruck bringen. Tritt beim Prüfen Wasser aus dem Gasventil, ist die Membran gerissen und das Gefäß muss getauscht werden.',
      },
    ],
  },

  /* ------------------------------------------------------------ Verteilung */
  {
    id: 'umwaelzpumpe',
    begriff: 'Umwälzpumpe',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['Heizungspumpe', 'Hocheffizienzpumpe', 'Nassläuferpumpe', 'Pumpe'],
    kurz: 'Die Umwälzpumpe fördert das Heizwasser durch das Rohrnetz; moderne Hocheffizienzpumpen regeln ihre Leistung nach dem Bedarf.',
    funktion:
      'Ein Laufrad erzeugt Förderhöhe und Volumenstrom. Bei Nassläufern schmiert und kühlt das Fördermedium den Rotor. Elektronisch geregelte Pumpen mit Permanentmagnetmotor messen Druck und Strom und passen die Drehzahl an: In der Regelart Δp-konstant bleibt die Förderhöhe gleich (gut für Einrohr und alte Anlagen), bei Δp-variabel sinkt sie mit dem Volumenstrom (richtig für Zweirohrnetze mit Thermostatventilen).',
    aufbau: ['Pumpengehäuse mit Laufrad', 'Permanentmagnetmotor mit Elektronik', 'Bedienfeld mit Regelart und Sollwert', 'Absperrungen und Schmutzfänger im Umfeld'],
    einsatz: ['Heizkreise, Kesselkreise, Pufferladung', 'Zirkulation im Trinkwasser (dort trinkwassergeeignete Ausführung)'],
    hinweise: [
      'Richtige Regelart wählen: Δp-variabel für Zweirohrsysteme mit Thermostatventilen, Δp-konstant für Fußbodenheizung mit Einzelraumregelung oder Einrohr.',
      'Förderhöhe nicht zu hoch einstellen – Geräusche und unnötiger Stromverbrauch.',
      'Einbaulage: Motorachse waagerecht, Pfeilrichtung beachten.',
      'Nach dem Füllen entlüften und Laufrad bei Bedarf über die Entlüftungsschraube gangbar machen.',
    ],
    stoerungen: [
      'Pumpe läuft nicht an: festsitzendes Laufrad nach langer Stillstandszeit, Elektronikfehler',
      'Strömungsgeräusche: Förderhöhe zu hoch, Luft im System, Ventile zu weit geschlossen',
      'Anlage wird nicht warm: Pumpe zu klein, Schmutzfänger verstopft, Luftpolster',
    ],
    werte: [
      'Energieeffizienzindex EEI ≤ 0,23 für Hocheffizienzpumpen (ErP)',
      'Übliche Förderhöhe im Einfamilienhaus: 2 bis 4 m',
      'Leistungsaufnahme moderner Pumpen: 5 bis 45 W',
    ],
    formeln: [
      { name: 'Volumenstrom aus Leistung', formel: 'V̇ = Q / (1,163 · ΔT)', erklaerung: 'V̇ in l/h, Q in W, ΔT in K.' },
      { name: 'Hydraulische Leistung', formel: 'P_hyd = V̇ · Δp', erklaerung: 'Mit V̇ in m³/s und Δp in Pa ergibt sich die Leistung in Watt.' },
    ],
    normen: ['ErP-Richtlinie 2009/125/EG', 'DIN EN 16297', 'DIN EN 12828'],
    verwandt: ['hydraulischer_abgleich', 'hydraulikformeln', 'heizungsanlage'],
  },
  {
    id: 'hydraulischer_abgleich',
    begriff: 'Hydraulischer Abgleich',
    bereich: 'heizung',
    kategorie: 'Verfahren',
    synonyme: ['Abgleich', 'abgeglichen', 'Voreinstellung', 'Einregulierung', 'Verfahren B'],
    kurz: 'Beim hydraulischen Abgleich erhält jeder Heizkreis genau den Wassermassenstrom, den er für seine Heizlast braucht.',
    funktion:
      'Wasser nimmt den Weg des geringsten Widerstands: Ohne Abgleich werden pumpennahe Heizflächen überversorgt, entfernte unterversorgt. Über voreinstellbare Ventileinsätze, Strangregulierventile oder Durchflussanzeiger am Verteiler wird jedem Kreis ein definierter Druckverlust aufgeprägt, sodass der berechnete Massenstrom fließt. Beim Verfahren A wird überschlägig gerechnet, beim Verfahren B raumweise mit Heizlast und Rohrnetzberechnung – nur dieses wird für Förderungen anerkannt.',
    aufbau: [
      'Raumweise Heizlastberechnung nach DIN EN 12831',
      'Massenstrom je Heizfläche aus Heizlast und Spreizung',
      'Voreinstellwerte aus dem Ventildiagramm des Herstellers',
      'Einstellung von Pumpenförderhöhe und Regelart',
      'Protokoll (z. B. VdZ-Formular) für Förderung und Dokumentation',
    ],
    einsatz: ['Neuanlagen', 'Heizungsoptimierung im Bestand', 'Voraussetzung für Förderungen und für effizienten Wärmepumpenbetrieb'],
    hinweise: [
      'Ohne Abgleich: Geräusche, Über- und Unterversorgung, zu hohe Rücklauftemperatur, hoher Pumpenstrom.',
      'Nach dem Abgleich Vorlauftemperatur schrittweise absenken – das ist der eigentliche Effizienzgewinn.',
      'Überströmventile möglichst vermeiden; sie heben die Rücklauftemperatur an.',
      'Einstellwerte dokumentieren und am Ventil markieren.',
    ],
    formeln: [
      { name: 'Massenstrom je Heizfläche', formel: 'ṁ = Φ / (1,163 · ΔT)', erklaerung: 'ṁ in l/h, Φ = Raumheizlast in W, ΔT = Spreizung in K.' },
      { name: 'Ventilautorität', formel: 'a = Δp_Ventil / Δp_Kreis', erklaerung: 'Sollwert mindestens 0,3 für gute Regelbarkeit.' },
    ],
    werte: ['Übliche Spreizung: Heizkörper 10–15 K, Fußbodenheizung 5–8 K', 'Restförderhöhe an der ungünstigsten Heizfläche etwa 100 bis 200 mbar'],
    normen: ['DIN EN 12831', 'VOB/C DIN 18380', 'VdZ-Fachregel', 'GEG'],
    verwandt: ['thermostatventil', 'strangregulierventil', 'umwaelzpumpe', 'heizlast', 'heizkurve'],
  },
  {
    id: 'thermostatventil',
    begriff: 'Thermostatventil',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['Thermostat', 'Heizkörperventil', 'Thermostatkopf', 'Ventileinsatz'],
    kurz: 'Das Thermostatventil regelt den Heizwasserdurchfluss eines Heizkörpers abhängig von der Raumtemperatur – ohne Hilfsenergie.',
    funktion:
      'Im Thermostatkopf sitzt ein Fühlerelement mit Flüssigkeit, Gas oder Wachs. Steigt die Raumtemperatur, dehnt sich der Stoff aus und schiebt über den Ventilstift den Kegel in Richtung Sitz – der Durchfluss sinkt. Kühlt der Raum ab, zieht sich das Element zusammen und das Ventil öffnet. Es ist ein Proportionalregler: Eine bleibende Regelabweichung ist systembedingt und wird über die Auslegung (2 K Proportionalbereich) berücksichtigt. Der voreinstellbare Ventileinsatz begrenzt zusätzlich den maximalen Durchfluss für den hydraulischen Abgleich.',
    aufbau: ['Ventilgehäuse mit Sitz und Kegel', 'Voreinstellbarer Ventileinsatz', 'Thermostatkopf mit Fühlerelement, Sollwertskala und Nullstellung', 'optional Fernfühler oder Behördenmodell'],
    einsatz: ['Heizkörper in Zweirohr- und Einrohranlagen', 'Einzelraumregelung nach GEG (Pflicht bei Neuinstallation)'],
    hinweise: [
      'Kopf frei anströmbar montieren – nicht hinter Vorhängen, Möbeln oder Verkleidungen; sonst Fernfühler verwenden.',
      'Voreinstellung aus der Heizlast- und Massenstromberechnung übernehmen und dokumentieren.',
      'Im Sommer Ventile gelegentlich ganz öffnen, damit der Kegel nicht festsitzt.',
      'Skalenwerte: 1 ≈ 12 °C, 2 ≈ 16 °C, 3 ≈ 20 °C, 4 ≈ 24 °C, 5 ≈ 28 °C, Sternsymbol ≈ 6 °C Frostschutz.',
    ],
    stoerungen: [
      'Heizkörper bleibt kalt: Ventilstift festsitzend, Voreinstellung zu klein, Luft im Heizkörper',
      'Heizkörper wird trotz geschlossenem Ventil warm: Fühlerelement defekt oder Schwerkraftzirkulation',
      'Rauschen: Differenzdruck zu hoch – Pumpe zurückregeln oder Differenzdruckregler einsetzen',
    ],
    werte: ['Proportionalbereich üblich 2 K', 'Maximaler Differenzdruck am Ventil etwa 0,2 bar (sonst Geräusche)'],
    normen: ['DIN EN 215', 'GEG', 'VDI 6030'],
    verwandt: ['hydraulischer_abgleich', 'heizkoerper', 'strangregulierventil'],
  },
  {
    id: 'strangregulierventil',
    begriff: 'Strangregulierventil und Differenzdruckregler',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['SRV', 'Regulierventil', 'Strangventil', 'Differenzdruckregler'],
    kurz: 'Strangregulierventile verteilen den Volumenstrom auf die Stränge; Differenzdruckregler halten den Druck vor den Ventilen konstant.',
    funktion:
      'Das Strangregulierventil besitzt eine einstellbare Drosselstelle und zwei Messnippel. Über die Druckdifferenz lässt sich der tatsächliche Volumenstrom bestimmen und auf den Sollwert einstellen. In großen Netzen schwankt der Differenzdruck stark, wenn Thermostatventile schließen; ein Differenzdruckregler hält ihn über eine Impulsleitung und Membransteuerung konstant und verhindert so Geräusche und Überversorgung.',
    aufbau: ['Ventilkörper mit Feineinstellung und Skala', 'Zwei Messnippel für das Messgerät', 'Absperrfunktion und Entleerung', 'Differenzdruckregler mit Impulsleitung'],
    einsatz: ['Steigstränge in Mehrfamilienhäusern', 'Zirkulationsleitungen (thermische Ausführung)', 'Große Netze mit stark schwankender Last'],
    hinweise: [
      'Einstellwerte aus der Rohrnetzberechnung übernehmen und am Ventil ablesbar dokumentieren.',
      'Messung mit Differenzdruckmessgerät nach Herstellerdiagramm.',
      'Im Zirkulationssystem thermische Strangregulierventile verwenden und auf mindestens 55 °C einstellen.',
    ],
    normen: ['DIN EN 12828', 'VDI 6003', 'DVGW W 553'],
    verwandt: ['hydraulischer_abgleich', 'zirkulation', 'umwaelzpumpe'],
  },
  {
    id: 'mischer',
    begriff: 'Mischer und Rücklaufanhebung',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['Dreiwegemischer', 'Vierwegemischer', 'Mischventil', 'Stellantrieb', 'Rücklaufanhebung'],
    kurz: 'Mischer regeln die Vorlauftemperatur eines Heizkreises, indem sie heißes Vorlaufwasser mit kühlerem Rücklaufwasser mischen.',
    funktion:
      'Der Dreiwegemischer hat zwei Eingänge (Kesselvorlauf und Heizkreisrücklauf) und einen Ausgang. Ein motorischer Stellantrieb verändert die Stellung nach dem Signal des Reglers, der Vorlauffühler und Heizkurve auswertet. Bei Festbrennstoff- und älteren Kesseln übernimmt eine Rücklaufanhebung (thermisches Ventil oder Mischer) die umgekehrte Aufgabe: Sie hält den Kesselrücklauf über der Taupunktgrenze und schützt vor Korrosion.',
    aufbau: ['Mischergehäuse mit Drehküken oder Sitz', 'Stellantrieb mit Handverstellung und Skala', 'Regler mit Vorlauffühler und Außenfühler', 'thermisches Rücklaufanhebungsventil (z. B. 60 °C) bei Biomasse'],
    einsatz: ['Fußbodenheizkreise hinter einem Heizkörperkreis', 'Mehrkreisanlagen mit unterschiedlichen Temperaturen', 'Festbrennstoffkessel und Pufferanbindung'],
    hinweise: [
      'Sicherheitsbegrenzer für Flächenheizung vorsehen (Vorlauf maximal 45 bis 55 °C je nach Aufbau).',
      'Stellantrieb-Laufzeit zur Regelstrecke passen, sonst pendelt die Regelung.',
      'Handbetrieb nach Wartung wieder auf Automatik stellen.',
    ],
    normen: ['DIN EN 12828', 'DIN EN 1264', 'VDI 3814'],
    verwandt: ['heizkurve', 'fussbodenheizung', 'pufferspeicher', 'biomasse'],
  },
  {
    id: 'pufferspeicher',
    begriff: 'Pufferspeicher und hydraulische Weiche',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['Puffer', 'Heizungspuffer', 'Trennspeicher', 'hydraulische Weiche', 'Reihenpuffer'],
    kurz: 'Pufferspeicher entkoppeln Erzeugung und Verbrauch zeitlich, hydraulische Weichen entkoppeln die Volumenströme zweier Kreise.',
    funktion:
      'Der Pufferspeicher nimmt Wärme auf, wenn der Erzeuger mehr liefert als gebraucht wird, und gibt sie später ab. Er verlängert Laufzeiten, verhindert Takten und ist bei Festbrennstoff zwingend. Die hydraulische Weiche trennt den Erzeugerkreis vom Verbraucherkreis: Jeder Kreis hat seine eigene Pumpe, und Volumenstromunterschiede führen nicht zu Über- oder Unterversorgung. Beide Bauteile erhöhen jedoch die Rücklauftemperatur, wenn sie falsch eingebunden oder unnötig eingesetzt werden.',
    aufbau: ['Stahlspeicher mit Dämmung', 'Anschlüsse mit Schichtladeeinrichtung oder Prallblech', 'Tauchhülsen für Fühler', 'Entlüftung oben, Entleerung unten'],
    einsatz: ['Wärmepumpen (Abtauung, Mindestwasserinhalt)', 'Festbrennstoff- und Solaranlagen', 'Anlagen mit stark unterschiedlichen Kreisen'],
    hinweise: [
      'Nur einsetzen, wenn er gebraucht wird – bei Brennwert verschlechtert er sonst die Kondensation.',
      'Schichtung erhalten: Einströmung beruhigen, nicht mit hoher Geschwindigkeit einblasen.',
      'Fühlerpositionen sorgfältig wählen; sie bestimmen das Regelverhalten.',
      'Speicher und Anschlussleitungen vollständig dämmen.',
    ],
    werte: [
      'Wärmepumpe: etwa 10 bis 20 l je kW (Reihenpuffer), Mindestumlaufvolumen nach Herstellerangabe',
      'Pellets: 30 bis 50 l je kW · Scheitholz: 55 bis 100 l je kW',
      'Solar: 50 bis 80 l je m² Kollektorfläche',
    ],
    normen: ['DIN EN 12828', 'VDI 4645', 'DIN EN 303-5'],
    verwandt: ['waermepumpe', 'biomasse', 'solarthermie', 'mischer'],
  },

  /* ------------------------------------------------------------ Wärmeübergabe */
  {
    id: 'heizkoerper',
    begriff: 'Heizkörper',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['Radiator', 'Plattenheizkörper', 'Konvektor', 'Handtuchheizkörper', 'Rippe'],
    kurz: 'Heizkörper geben Wärme über Konvektion und Strahlung ab; ihre Leistung hängt stark von der mittleren Übertemperatur ab.',
    funktion:
      'Die Normleistung wird bei einer definierten Auslegung angegeben (früher 75/65/20, heute meist 55/45/20). Wird die Anlage mit niedrigeren Temperaturen gefahren, sinkt die Leistung nach einer Potenzfunktion mit dem Heizkörperexponenten – bei Plattenheizkörpern etwa 1,3. Deshalb bringt eine Absenkung der Vorlauftemperatur nur dann keinen Komfortverlust, wenn die Heizflächen groß genug sind.',
    aufbau: ['Plattenheizkörper Typ 11/22/33 mit Konvektionsblechen', 'Röhren- und Designheizkörper', 'Konvektor und Unterflurkonvektor', 'Anschluss über Thermostatventil und Rücklaufverschraubung'],
    einsatz: ['Alt- und Neubau', 'Sanierung mit Wärmepumpe (dann Niedertemperatur-Heizkörper oder Vergrößerung)'],
    hinweise: [
      'Unter dem Fenster montieren, wenn die Außenwand schlecht gedämmt ist – das verhindert Kaltluftabfall.',
      'Abstände einhalten: etwa 10 cm zur Fensterbank, 10 bis 12 cm zum Boden.',
      'Nicht verkleiden oder zustellen; Verkleidungen senken die Leistung deutlich.',
      'Bei Umstellung auf niedrige Temperaturen die erforderliche Leistung neu prüfen.',
    ],
    formeln: [
      {
        name: 'Leistungsanpassung',
        formel: 'Φ = Φ_N · (ΔT / ΔT_N)^n',
        erklaerung: 'ΔT = mittlere Übertemperatur, n ≈ 1,3 für Plattenheizkörper.',
      },
      {
        name: 'Mittlere Übertemperatur',
        formel: 'ΔT = (t_VL + t_RL) / 2 − t_Raum',
        erklaerung: 'Vereinfachte arithmetische Berechnung; genauer ist die logarithmische Form.',
      },
    ],
    werte: [
      'Normauslegung heute 55/45/20 °C, früher 75/65/20 °C',
      'Beispiel: Heizkörper mit 1000 W bei 75/65/20 leistet bei 55/45/20 nur noch etwa 560 W',
      'Heizkörperexponent n: Plattenheizkörper 1,3 · Konvektor 1,3–1,4 · Fußbodenheizung etwa 1,1',
    ],
    normen: ['DIN EN 442', 'VDI 6030', 'DIN EN 12831'],
    verwandt: ['thermostatventil', 'heizlast', 'hydraulischer_abgleich', 'heizkurve'],
  },
  {
    id: 'fussbodenheizung',
    begriff: 'Fußbodenheizung (Flächenheizung)',
    bereich: 'heizung',
    kategorie: 'Anlage',
    synonyme: ['FBH', 'Flächenheizung', 'Wandheizung', 'Estrichheizung'],
    kurz: 'Die Fußbodenheizung gibt Wärme großflächig mit hohem Strahlungsanteil ab und arbeitet deshalb mit sehr niedrigen Vorlauftemperaturen.',
    funktion:
      'Im Estrich verlegte Rohrschlangen erwärmen die Bodenfläche; von dort geht die Wärme überwiegend als Strahlung in den Raum. Wegen der großen Fläche genügen 30 bis 40 °C Vorlauftemperatur – ideal für Wärmepumpe und Brennwert. Die Auslegung erfolgt über Heizlast, Verlegeabstand, Estrichüberdeckung und den Wärmedurchlasswiderstand des Bodenbelags. Begrenzt wird die Leistung durch die zulässige Oberflächentemperatur.',
    aufbau: [
      'Randdämmstreifen und Wärme-/Trittschalldämmung nach DIN 18560',
      'Systemplatte (Noppen- oder Tackerplatte)',
      'Heizrohr PE-RT oder Mehrschichtverbundrohr 16 x 2,0 mm',
      'Estrich (Zement- oder Calciumsulfatestrich) mit Zusatzmittel',
      'Heizkreisverteiler mit Durchflussanzeigern und Stellantrieben',
    ],
    einsatz: ['Neubau und Sanierung', 'Bäder und Wohnräume', 'Kombination mit Kühlung im Sommer (Flächenkühlung)'],
    hinweise: [
      'Verlegeabstand meist 10 bis 20 cm, im Randbereich und Bad enger.',
      'Heizkreislängen begrenzen (bei 16 mm etwa 100 m), Kreise möglichst gleich lang halten.',
      'Vor dem Estricheinbau Druckprobe herstellen und während des Einbringens unter Druck halten.',
      'Funktionsheizen und Belegreifheizen protokollieren – Grundlage für die Abnahme durch den Bodenleger.',
      'Bodenbelag mit hohem Wärmedurchlasswiderstand (dicker Teppich) reduziert die Leistung deutlich.',
    ],
    werte: [
      'Maximale Oberflächentemperatur: Aufenthaltsbereich 29 °C · Randzone 35 °C · Bad 33 °C',
      'Maximale Wärmestromdichte: etwa 100 W/m² im Aufenthaltsbereich',
      'Estrichüberdeckung über dem Rohr: mindestens 45 mm bei Zementestrich (nach Estrichart und Zusatzmittel)',
      'Auslegungstemperatur typisch 35/28 °C, Spreizung 5 bis 8 K',
      'Wärmedurchlasswiderstand Bodenbelag: möglichst unter 0,15 m²K/W',
    ],
    normen: ['DIN EN 1264', 'DIN 18560', 'VOB/C DIN 18380', 'DIN EN 12831'],
    verwandt: ['heizkreisverteiler', 'estrich_funktionsheizen', 'waermepumpe', 'pe_x_rohr', 'hydraulischer_abgleich'],
  },
  {
    id: 'heizkreisverteiler',
    begriff: 'Heizkreisverteiler',
    bereich: 'heizung',
    kategorie: 'Bauteil',
    synonyme: ['Verteiler', 'Fußbodenheizungsverteiler', 'Verteilerschrank', 'Durchflussmesser'],
    kurz: 'Der Heizkreisverteiler verteilt den Volumenstrom auf die einzelnen Heizkreise und ermöglicht deren Abgleich und Absperrung.',
    funktion:
      'Im Vorlaufbalken sitzen Durchflussanzeiger (Topmeter), mit denen der Volumenstrom je Kreis auf den berechneten Wert eingestellt wird. Im Rücklaufbalken sitzen die Ventileinsätze mit Stellantrieben der Einzelraumregelung. Absperrhähne, Entlüfter und Füll-/Entleerhähne erlauben das Spülen und Entlüften jedes Kreises einzeln.',
    aufbau: ['Vorlaufbalken mit Durchflussanzeigern', 'Rücklaufbalken mit Ventileinsätzen und Stellantrieben', 'Kugelhähne, Entlüfter, KFE-Hähne, Thermometer', 'Verteilerschrank, Anschlussverschraubungen (Eurokonus)'],
    einsatz: ['Fußboden-, Wand- und Deckenheizung', 'Verteilung mehrerer Heizkreise je Geschoss'],
    hinweise: [
      'Kreise beschriften – Raumzuordnung dokumentieren.',
      'Jeden Kreis einzeln spülen und entlüften, bevor die Anlage in Betrieb geht.',
      'Durchflusswerte aus der Auslegung einstellen und protokollieren.',
      'Verteiler zugänglich einbauen und Stellantriebe auf Funktion prüfen (stromlos geschlossen oder offen beachten).',
    ],
    werte: ['Übliche Durchflussanzeige: 0 bis 5 l/min je Kreis', 'Anschluss meist 3/4 Zoll Eurokonus'],
    normen: ['DIN EN 1264', 'DIN EN 215'],
    verwandt: ['fussbodenheizung', 'hydraulischer_abgleich', 'estrich_funktionsheizen'],
  },
  {
    id: 'estrich_funktionsheizen',
    begriff: 'Funktionsheizen und Belegreifheizen',
    bereich: 'heizung',
    kategorie: 'Verfahren',
    synonyme: ['Aufheizprotokoll', 'Estrich aufheizen', 'Belegreife', 'Funktionsheizen'],
    kurz: 'Vor der Abnahme einer Flächenheizung wird der Estrich nach festem Programm aufgeheizt und das Ergebnis protokolliert.',
    funktion:
      'Das Funktionsheizen weist die Funktionsfähigkeit der Heizung nach und ist Sache des Heizungsbauers. Es beginnt frühestens nach der Aushärtezeit des Estrichs: bei Zementestrich in der Regel 21 Tage, bei Calciumsulfatestrich 7 Tage nach Einbringen. Gestartet wird mit etwa 25 °C Vorlauftemperatur für drei Tage, anschließend wird die maximale Auslegungstemperatur für mindestens vier Tage gehalten. Das Belegreifheizen dient dem Austrocknen bis zur Belegreife und ist Leistung des Bodenlegers bzw. Bauherrn.',
    aufbau: ['Aufheizprotokoll mit Datum, Vorlauftemperaturen, Außentemperatur, Unterschrift', 'Feuchtemessung (CM-Messung) durch den Bodenleger', 'Abstimmung mit den anderen Gewerken'],
    einsatz: ['Alle beheizten Estriche vor dem Belegen'],
    hinweise: [
      'Funktionsheizen ersetzt nicht das Belegreifheizen – die Restfeuchte muss separat nachgewiesen werden.',
      'Zugluft und schnelles Abkühlen vermeiden, Fenster geschlossen halten.',
      'Protokoll ist Teil der Abnahmedokumentation und schützt bei Streitfällen.',
    ],
    werte: [
      'Zementestrich: Start frühestens 21 Tage nach Einbau · Calciumsulfatestrich: 7 Tage',
      'Ablauf: 3 Tage bei etwa 25 °C, danach mindestens 4 Tage maximale Auslegungstemperatur',
      'Belegreife CM-Wert: Zementestrich ≤ 1,8 % · Calciumsulfatestrich ≤ 0,3 % (beheizt)',
    ],
    normen: ['DIN EN 1264-4', 'DIN 18560-2', 'VOB/C DIN 18380 und DIN 18365'],
    verwandt: ['fussbodenheizung', 'heizkreisverteiler', 'inbetriebnahme'],
  },

  /* ------------------------------------------------------------ Regelung und Betrieb */
  {
    id: 'heizkurve',
    begriff: 'Heizkurve und witterungsgeführte Regelung',
    bereich: 'heizung',
    kategorie: 'Verfahren',
    synonyme: ['Heizkennlinie', 'Steilheit', 'Parallelverschiebung', 'Außenfühler', 'Regelung'],
    kurz: 'Die witterungsgeführte Regelung bestimmt die Vorlauftemperatur aus der Außentemperatur; die Heizkurve beschreibt diesen Zusammenhang.',
    funktion:
      'Der Außenfühler misst die Außentemperatur, der Regler berechnet daraus über die eingestellte Kennlinie die Soll-Vorlauftemperatur und steuert Brenner oder Mischer. Die Steilheit gibt an, wie stark der Vorlauf bei sinkender Außentemperatur ansteigt; die Parallelverschiebung hebt oder senkt die gesamte Kurve. Ziel ist, die Vorlauftemperatur so niedrig wie möglich zu halten, ohne dass Räume auskühlen.',
    aufbau: ['Außenfühler an der Nordseite, verschattet, nicht über Fenstern oder Abluft', 'Vorlauffühler bzw. Kesselfühler', 'Zeitprogramm mit Absenkbetrieb', 'optional Raumfühler mit Raumeinfluss'],
    einsatz: ['Alle geregelten Heizungsanlagen', 'Optimierung im Bestand'],
    hinweise: [
      'Einstellhilfe: Ist es in der Übergangszeit zu kalt, aber im Winter passend, Parallelverschiebung erhöhen; ist es nur im Winter zu kalt, Steilheit erhöhen.',
      'Nach jedem Schritt zwei bis drei Tage beobachten – die Gebäudeträgheit ist groß.',
      'Absenkung bei Wärmepumpen und Flächenheizungen nur maßvoll; das Wiederaufheizen kostet mehr, als die Absenkung spart.',
      'Thermostatventile müssen ganz geöffnet sein, wenn die Heizkurve eingestellt wird.',
    ],
    werte: [
      'Steilheit Richtwerte: Fußbodenheizung 0,3 bis 0,6 · Heizkörper saniert 1,0 bis 1,2 · Altbau 1,4 bis 1,8',
      'Typische Absenkung im Nachtbetrieb: 3 bis 5 K',
    ],
    normen: ['GEG', 'DIN EN 12831', 'VDI 3814'],
    verwandt: ['heizungsanlage', 'mischer', 'hydraulischer_abgleich', 'waermepumpe'],
  },
  {
    id: 'heizungswasser',
    begriff: 'Heizungswasser nach VDI 2035',
    bereich: 'heizung',
    kategorie: 'Regelwerk',
    synonyme: ['Füllwasser', 'VDI 2035', 'Enthärtung Heizung', 'Salzarm', 'Steinbildung'],
    kurz: 'Füll- und Ergänzungswasser muss aufbereitet werden, damit weder Steinbildung noch Korrosion auftreten.',
    funktion:
      'VDI 2035 Blatt 1 begrenzt die Härte des Füllwassers abhängig von Gesamtleistung und spezifischem Anlagenvolumen – je kleiner der Wasserinhalt je Kilowatt und je größer die Leistung, desto weicher muss das Wasser sein. Blatt 2 behandelt die wasserseitige Korrosion: Entscheidend sind Sauerstoffarmut, der richtige pH-Wert und eine geringe elektrische Leitfähigkeit. Salzarme Fahrweise (Vollentsalzung) ist heute Stand der Technik, weil sie beide Probleme zugleich löst.',
    aufbau: ['Enthärtungs- oder Vollentsalzungspatrone für die Befüllung', 'Systemtrenner an der Füllarmatur', 'Mikroblasen- und Schlammabscheider', 'Protokoll mit Wassermenge, Härte, pH-Wert und Leitfähigkeit'],
    einsatz: ['Jede Neubefüllung und jede größere Nachspeisung', 'Sanierung mit neuen Heizflächen'],
    hinweise: [
      'Anlage nicht dauerhaft mit dem Trinkwassernetz verbunden lassen – nach dem Füllen trennen.',
      'Häufiges Nachspeisen ist ein Alarmzeichen: erst die Leckage suchen, nicht nachfüllen.',
      'Füllwasser dokumentieren – die Herstellergarantie verlangt das in der Regel.',
      'Keine Frostschutzmittel ohne Freigabe des Herstellers einsetzen; sie verändern Viskosität und Wärmekapazität.',
    ],
    werte: [
      'Salzarme Fahrweise: Leitfähigkeit unter 100 µS/cm, pH-Wert 8,2 bis 10,0',
      'Salzhaltige Fahrweise: Leitfähigkeit 100 bis 1500 µS/cm, pH-Wert 8,2 bis 10,0',
      'Bei Aluminiumwerkstoffen: pH-Wert 8,0 bis 8,5',
      'Spezifisches Anlagenvolumen als Grenzwert: 20 l je kW Kesselleistung',
    ],
    normen: ['VDI 2035 Blatt 1 und 2', 'DIN EN 14868', 'ÖNORM H 5195'],
    verwandt: ['korrosion', 'ausdehnungsgefaess', 'entlueftung', 'systemtrenner'],
  },
  {
    id: 'entlueftung',
    begriff: 'Luft in der Heizungsanlage',
    bereich: 'heizung',
    kategorie: 'Verfahren',
    synonyme: ['entlüften', 'Luft im System', 'Mikroblasenabscheider', 'Schnellentlüfter', 'gluckern'],
    kurz: 'Luft im Heizsystem verursacht Geräusche, kalte Heizflächen und Korrosion; sie wird an den Hochpunkten und über Abscheider entfernt.',
    funktion:
      'Luft gelangt beim Füllen, über Nachspeisung, durch Unterdruck oder Diffusion ins System. Freie Luft sammelt sich an Hochpunkten, gelöste Luft wird erst bei Erwärmung frei. Mikroblasenabscheider arbeiten mit einem Drahtgeflecht, an dem sich kleinste Blasen zu größeren vereinigen und aufsteigen; sie werden im heißesten Punkt eingebaut, meist im Vorlauf direkt nach dem Erzeuger. Schlammabscheider mit Magnet entfernen gleichzeitig Magnetit.',
    aufbau: ['Handentlüfter an Heizkörpern und Hochpunkten', 'Schnellentlüfter mit Absperrung', 'Mikroblasen- und Schlammabscheider', 'ausreichender Anlagendruck'],
    einsatz: ['Nach jedem Füllen und nach Arbeiten am System', 'Bei Geräuschen und kalten Heizkörpern', 'Bestandteil der Wartung'],
    hinweise: [
      'Erst den Anlagendruck kontrollieren, dann entlüften – bei zu geringem Druck zieht die Anlage an Hochpunkten Luft.',
      'Von unten nach oben entlüften, Pumpe vorher abschalten und einige Minuten warten.',
      'Nach dem Entlüften Druck prüfen und ggf. aufbauen.',
      'Wiederkehrende Luft deutet auf Undichtigkeit, Unterdruck oder diffusionsoffene Rohre hin.',
    ],
    stoerungen: ['Heizkörper oben kalt: Luftpolster', 'Gluckern in der Leitung: Luft in Verbindung mit hoher Fließgeschwindigkeit', 'Pumpe läuft trocken und brummt: Luft im Pumpenkopf'],
    normen: ['VDI 2035', 'DIN EN 12828'],
    verwandt: ['heizungswasser', 'umwaelzpumpe', 'inbetriebnahme'],
  },
  {
    id: 'inbetriebnahme',
    begriff: 'Inbetriebnahme und Übergabe',
    bereich: 'heizung',
    kategorie: 'Verfahren',
    synonyme: ['in Betrieb genommen', 'Einregulierung', 'Einweisung', 'Übergabeprotokoll', 'Abnahme'],
    kurz: 'Zur Inbetriebnahme gehören Dichtheitsprüfung, Spülung, Befüllung, Einstellung, Messung, Einweisung und Dokumentation.',
    funktion:
      'Nach der Montage wird die Anlage geprüft und gespült, mit aufbereitetem Wasser gefüllt und entlüftet. Anschließend werden Sicherheitseinrichtungen kontrolliert, Regelparameter eingestellt, der hydraulische Abgleich umgesetzt und die Verbrennungswerte gemessen. Zum Schluss wird der Betreiber eingewiesen und die Dokumentation übergeben – erst damit ist die Leistung vollständig erbracht.',
    aufbau: [
      'Dichtheits- und Druckprüfung mit Protokoll',
      'Spülung und Befüllung mit dokumentierter Wasserqualität',
      'Prüfung von Sicherheitsventil, MAG-Vordruck, STB',
      'Einstellung von Heizkurve, Pumpe, Voreinstellungen',
      'Abgasmessung und Einstellprotokoll',
      'Einweisung des Betreibers und Übergabe der Unterlagen',
    ],
    einsatz: ['Jede Neuanlage', 'Nach größeren Umbauten und Erzeugertausch'],
    hinweise: [
      'Betreiber über Anlagendruck, Nachspeisen, Wartungsintervalle und Störmeldungen informieren.',
      'Alle Protokolle (Druckprobe, Spülung, Wasseranalyse, Abgasmessung, Abgleich) übergeben und im Betrieb archivieren.',
      'Bei Gasgeräten die Inbetriebnahme nur mit gültiger Fachbetriebseintragung und nach Anzeige beim Netzbetreiber.',
    ],
    normen: ['VOB/C DIN 18380', 'DIN EN 12828', 'DIN EN 806-4', 'DVGW-TRGI G 600'],
    verwandt: ['dichtheitspruefung', 'heizungswasser', 'hydraulischer_abgleich', 'abgasmessung'],
  },
  {
    id: 'heizungsoptimierung',
    begriff: 'Heizungsoptimierung und Effizienz',
    bereich: 'heizung',
    kategorie: 'Verfahren',
    synonyme: ['Optimierung', 'Energieeinsparung', 'Betriebsoptimierung', 'Effizienz'],
    kurz: 'Mit Abgleich, abgesenkten Temperaturen, Dämmung und geregelter Pumpe lässt sich der Verbrauch ohne Erzeugertausch deutlich senken.',
    funktion:
      'Die größten Hebel sind: hydraulischer Abgleich, Absenkung der Vorlauftemperatur über die Heizkurve, Austausch ungeregelter Pumpen durch Hocheffizienzpumpen, Dämmung von Verteilleitungen und Armaturen in unbeheizten Räumen sowie die Anpassung der Zirkulationszeiten. Jede Absenkung der Rücklauftemperatur verbessert zusätzlich den Brennwert- oder Wärmepumpennutzen.',
    aufbau: ['Bestandsaufnahme: Verbräuche, Temperaturen, Pumpeneinstellung', 'Raumweise Heizlast und Abgleich', 'Einstellung von Heizkurve und Zeitprogrammen', 'Dämmung und Armaturenisolierung', 'Erfolgskontrolle über Verbrauchsdaten'],
    einsatz: ['Bestandsanlagen jeder Größe', 'Pflichtprüfungen für Gasheizungen in größeren Gebäuden', 'Vorbereitung eines späteren Wärmepumpeneinsatzes'],
    hinweise: [
      'Erst optimieren, dann tauschen – so wird der neue Erzeuger nicht zu groß ausgelegt.',
      'Absenkung der Vorlauftemperatur um 5 K spart je nach Anlage etwa 3 bis 5 % Energie.',
      'Alte ungeregelte Pumpen brauchen oft das Fünf- bis Zehnfache einer Hocheffizienzpumpe.',
      'Maßnahmen dokumentieren – viele sind förderfähig.',
    ],
    werte: [
      'Hydraulischer Abgleich: Einsparung typisch 5 bis 15 %',
      'Pumpentausch: 80 bis 90 % weniger Pumpenstrom',
      'Dämmung ungedämmter Verteilleitungen: 3 bis 8 % Einsparung',
    ],
    normen: ['GEG', 'VdZ-Fachregel', 'DIN EN 15378 (Inspektion)'],
    verwandt: ['hydraulischer_abgleich', 'heizkurve', 'umwaelzpumpe', 'daemmung_geg'],
  },
];
