/**
 * Fachdatenbank – Lüftung, Klima und Kältetechnik.
 */

export const LUEFTUNG = [
  {
    id: 'wohnungslueftung',
    begriff: 'Wohnungslüftung nach DIN 1946-6',
    bereich: 'lueftung',
    kategorie: 'Anlage',
    synonyme: ['kontrollierte Wohnraumlüftung', 'KWL', 'Lüftungskonzept', 'Lüftungsanlage Wohnung'],
    kurz: 'Für jedes neue oder wesentlich sanierte Gebäude ist ein Lüftungskonzept zu erstellen; reicht die Infiltration nicht aus, sind lüftungstechnische Maßnahmen erforderlich.',
    funktion:
      'Dichte Gebäudehüllen lassen kaum noch Luft durch Fugen nachströmen. Deshalb wird geprüft, ob der Feuchteschutz allein durch Infiltration sichergestellt ist. Ist das nicht der Fall, muss eine lüftungstechnische Maßnahme geplant werden – von der Außenwandluftdurchlass-Lösung bis zur zentralen Anlage mit Wärmerückgewinnung. Die Norm definiert vier Lüftungsstufen: Feuchteschutz, reduzierte Lüftung, Nennlüftung und Intensivlüftung.',
    aufbau: [
      'Zentrale Zu-/Abluftanlage mit Wärmerückgewinnung',
      'Dezentrale Einzelraumgeräte mit Regenerativ-Wärmeübertrager',
      'Reine Abluftanlage mit Außenluftdurchlässen (ALD)',
      'Luftführung: Zuluft in Aufenthaltsräume, Abluft aus Küche, Bad, WC, Überströmung über Türspalt',
    ],
    einsatz: ['Neubau mit dichter Hülle', 'Sanierung mit Fenstertausch', 'Passivhaus und KfW-Effizienzhaus'],
    hinweise: [
      'Überströmöffnungen einplanen – ohne sie funktioniert die Luftführung nicht (Türkürzung oder Überströmgitter).',
      'Anlagen bedarfsgerecht regeln (CO₂-, Feuchte- oder Präsenzsteuerung) statt dauerhaft auf Nennlüftung.',
      'Filterwechsel in die Einweisung aufnehmen – häufigster Grund für Beschwerden ist ein zugesetzter Filter.',
      'Bei Feuerstätten im selben Bereich Unterdruckproblematik prüfen.',
    ],
    werte: [
      'Außenluftrate Richtwert: etwa 30 m³/h je Person',
      'Abluftvolumenströme nach DIN 18017-3: Bad 40 m³/h · WC 25 m³/h · Küche 45 bis 60 m³/h (Intensivstufe höher)',
      'Luftwechsel Nennlüftung Wohnung: etwa 0,4 bis 0,6 1/h',
      'Zulässige Luftgeschwindigkeit im Aufenthaltsbereich: unter 0,2 m/s',
    ],
    formeln: [
      { name: 'Luftwechsel', formel: 'n = V̇ / V_Raum', erklaerung: 'n in 1/h, V̇ in m³/h, Raumvolumen in m³.' },
      { name: 'Volumenstrom', formel: 'V̇ = A · v · 3600', erklaerung: 'A = Kanalquerschnitt in m², v = Luftgeschwindigkeit in m/s, Ergebnis in m³/h.' },
    ],
    normen: ['DIN 1946-6', 'DIN 18017-3', 'GEG', 'DIN EN 16798'],
    verwandt: ['waermerueckgewinnung', 'luftkanal', 'luftfilter', 'rlt_hygiene', 'verbrennungsluft'],
  },
  {
    id: 'rlt_anlage',
    begriff: 'Raumlufttechnische Anlage (RLT)',
    bereich: 'lueftung',
    kategorie: 'Anlage',
    synonyme: ['RLT', 'Klimaanlage', 'Lüftungszentrale', 'Klimagerät', 'Zuluftanlage'],
    kurz: 'Eine RLT-Anlage behandelt Luft – sie kann lüften, heizen, kühlen, befeuchten, entfeuchten und filtern.',
    funktion:
      'Die Außenluft wird angesaugt, gefiltert und über Wärmeübertrager auf die gewünschte Temperatur gebracht; bei Bedarf wird sie befeuchtet oder durch Unterschreiten des Taupunkts entfeuchtet. Ventilatoren fördern die Luft über das Kanalnetz in die Räume, die Abluft wird abgesaugt und – meist nach Wärmerückgewinnung – als Fortluft ins Freie geführt. Welche dieser Funktionen vorhanden sind, bestimmt die Bezeichnung nach DIN EN 13779: von der reinen Lüftungsanlage bis zur Klimaanlage mit allen vier Thermodynamikfunktionen.',
    aufbau: [
      'Außenluftklappe mit Wetterschutzgitter und Filter',
      'Wärmerückgewinnung (Platten-, Rotations- oder Kreislaufverbundsystem)',
      'Erhitzer (PWW oder elektrisch), Kühler mit Tropfenabscheider und Kondensatablauf',
      'Befeuchter (Dampf oder adiabat)',
      'Zu- und Abluftventilator mit Frequenzumrichter',
      'Schalldämpfer, Brandschutzklappen, Volumenstromregler',
    ],
    einsatz: ['Büro-, Versammlungs- und Verkaufsstätten', 'Krankenhaus, Labor, Reinraum', 'Schwimmbad (dort mit Entfeuchtung)', 'Gewerbliche Küchen'],
    hinweise: [
      'Luftführung von „rein nach unrein“ planen – Zuluft in Aufenthaltsbereiche, Abluft aus belasteten Zonen.',
      'Zugänglichkeit für Wartung und Filterwechsel schon in der Planung berücksichtigen.',
      'Volumenströme einregulieren und protokollieren; ohne Messung keine funktionierende Anlage.',
      'Kondensatablauf mit ausreichender Siphonhöhe für den Unterdruck des Gerätes ausführen.',
    ],
    werte: [
      'Luftgeschwindigkeit: Hauptkanal 4 bis 8 m/s · Nebenkanal 2 bis 4 m/s · Auslass 1,5 bis 2,5 m/s',
      'Spezifische Ventilatorleistung SFP: Kategorie SFP 2 bis SFP 4 je nach Anlage',
      'Temperaturdifferenz Zuluft zu Raum beim Kühlen: maximal 8 bis 10 K, sonst Zugerscheinungen',
    ],
    normen: ['DIN EN 16798', 'DIN EN 13779 (abgelöst, noch gebräuchlich)', 'VDI 3803', 'VDI 6022'],
    verwandt: ['waermerueckgewinnung', 'luftkanal', 'luftfilter', 'kuehllast', 'rlt_hygiene'],
  },
  {
    id: 'waermerueckgewinnung',
    begriff: 'Wärmerückgewinnung (WRG)',
    bereich: 'lueftung',
    kategorie: 'Bauteil',
    synonyme: ['WRG', 'Kreuzstromwärmetauscher', 'Gegenstromwärmetauscher', 'Rotationswärmetauscher', 'Enthalpietauscher'],
    kurz: 'Die Wärmerückgewinnung überträgt Wärme aus der Abluft auf die Außenluft und senkt damit den Heizwärmebedarf der Lüftung erheblich.',
    funktion:
      'Im Plattenwärmeübertrager strömen Ab- und Außenluft in getrennten Kanälen aneinander vorbei; im Gegenstrom wird die höchste Rückwärmzahl erreicht. Der Rotationswärmeübertrager dreht eine Speichermasse abwechselnd durch beide Luftströme und kann – als Enthalpierad mit hygroskopischer Beschichtung – auch Feuchte übertragen. Das Kreislaufverbundsystem koppelt zwei Register über einen Solekreis und erlaubt räumlich getrennte Geräte.',
    aufbau: ['Plattenwärmeübertrager (Kreuz- oder Gegenstrom) mit Bypass und Kondensatablauf', 'Rotationswärmeübertrager mit Antrieb und Spülzone', 'Kreislaufverbundsystem mit Pumpe und Register'],
    einsatz: ['Wohnungslüftung', 'Bürogebäude', 'Industrie und Schwimmbäder'],
    hinweise: [
      'Sommerbypass vorsehen, damit im Sommer nicht unnötig vorgewärmt wird.',
      'Vereisungsschutz sicherstellen: Vorheizregister, Bypass oder Volumenstromreduzierung.',
      'Bei Rotationswärmeübertragern Leckage beachten – nicht in Bereichen mit Geruchs- oder Keimübertragung einsetzen.',
      'Kondensat aus dem Plattenwärmeübertrager sicher abführen.',
    ],
    werte: [
      'Rückwärmzahl: Kreuzstrom 50 bis 65 % · Gegenstrom 80 bis 95 % · Rotation 70 bis 85 %',
      'Enthalpietauscher überträgt zusätzlich Feuchte (Rückfeuchtzahl 50 bis 70 %)',
    ],
    formeln: [
      { name: 'Rückwärmzahl', formel: 'Φ = (t_Zuluft − t_Außen) / (t_Abluft − t_Außen)', erklaerung: 'Alle Temperaturen in °C; Ergebnis als Anteil bzw. Prozent.' },
      { name: 'Wärmeleistung Luft', formel: 'Q = V̇ · 0,34 · ΔT', erklaerung: 'Q in W, V̇ in m³/h, 0,34 Wh/(m³·K) für Luft, ΔT in K.' },
    ],
    normen: ['DIN EN 308', 'GEG', 'VDI 2071', 'DIN 1946-6'],
    verwandt: ['rlt_anlage', 'wohnungslueftung', 'luftfilter'],
  },
  {
    id: 'luftkanal',
    begriff: 'Luftkanalnetz',
    bereich: 'lueftung',
    kategorie: 'Werkstoff',
    synonyme: ['Lüftungskanal', 'Wickelfalzrohr', 'Blechkanal', 'Flexrohr', 'Luftleitung'],
    kurz: 'Luftleitungen werden als Wickelfalzrohr oder Rechteckkanal ausgeführt; Dichtheit, Reinigbarkeit und Schallschutz bestimmen die Qualität.',
    funktion:
      'Runde Wickelfalzrohre haben bei gleichem Querschnitt weniger Druckverlust und sind dichter als Rechteckkanäle; sie werden mit Muffen, Lippendichtung und Blechschrauben oder Nieten verbunden. Rechteckkanäle kommen bei geringer Bauhöhe zum Einsatz. Die Luftdichtheit wird in Klassen von A bis D eingeteilt – jede Klasse bedeutet etwa eine Drittelung der Leckluftrate. Undichte Kanäle kosten unmittelbar Ventilatorenergie.',
    aufbau: ['Wickelfalzrohr mit Formteilen und Dichtlippenmuffen', 'Rechteckkanal mit Flanschverbindung und Dichtband', 'Flexible Anschlussschläuche (kurz halten)', 'Revisionsöffnungen, Brandschutzklappen, Volumenstromregler, Schalldämpfer'],
    einsatz: ['Alle RLT- und Wohnungslüftungsanlagen'],
    hinweise: [
      'Revisionsöffnungen in ausreichender Zahl vorsehen – die Anlage muss nach VDI 6022 reinigbar sein.',
      'Flexible Rohre nur für kurze Anbindungen und immer gestreckt verlegen; gestaucht vervielfacht sich der Druckverlust.',
      'Kanäle während der Bauzeit verschließen, damit kein Bauschutt und Staub eindringt.',
      'Brandschutzklappen an Brandabschnittsgrenzen, revisionierbar und mit Kennzeichnung.',
      'Kanäle in unbeheizten Bereichen dämmen, Kaltluftkanäle zusätzlich mit Dampfsperre.',
    ],
    werte: [
      'Dichtheitsklassen nach DIN EN 12237/1507: A, B, C, D – für RLT üblich mindestens Klasse B, besser C',
      'Wickelfalzrohr-Durchmesser: 80 bis 1250 mm',
      'Empfohlene Geschwindigkeit: Hauptkanal 4 bis 8 m/s, Wohnungslüftung 2 bis 3 m/s',
    ],
    normen: ['DIN EN 1505/1506', 'DIN EN 12237', 'DIN EN 13779', 'VDI 6022'],
    verwandt: ['rlt_anlage', 'rlt_hygiene', 'schalldaempfer', 'brandschutz'],
  },
  {
    id: 'luftfilter',
    begriff: 'Luftfilter',
    bereich: 'lueftung',
    kategorie: 'Bauteil',
    synonyme: ['Filterklasse', 'ISO 16890', 'F7', 'Pollenfilter', 'Taschenfilter'],
    kurz: 'Filter halten Staub, Pollen und Feinstaub zurück; die Klassifizierung erfolgt heute nach ISO 16890 über die Abscheidung von Feinstaubfraktionen.',
    funktion:
      'Die Filterwirkung beruht auf Sperreffekt, Trägheit, Diffusion und elektrostatischer Anziehung. ISO 16890 gibt an, welchen Anteil der Partikel eines Größenbereichs ein Filter abscheidet: ePM1, ePM2,5 und ePM10 stehen für Partikel bis 1, 2,5 und 10 Mikrometer. Mit zunehmender Beladung steigt der Druckverlust – und damit der Stromverbrauch des Ventilators.',
    aufbau: ['Vorfilter (ISO Coarse) zum Schutz der Feinfilter', 'Feinfilter ePM1 bzw. ePM2,5 als Taschen- oder Kompaktfilter', 'Schwebstofffilter H13/H14 in Reinräumen und Krankenhausbereichen', 'Differenzdruckanzeige je Filterstufe'],
    einsatz: ['Außenluftfilterung in RLT-Anlagen', 'Abluftfilterung zum Schutz der Wärmerückgewinnung', 'Wohnungslüftung (oft G4 plus F7 Pollenfilter)'],
    hinweise: [
      'Filterwechsel nach Enddruckdifferenz oder Standzeit – nach VDI 6022 spätestens nach 12 Monaten (Außenluftfilter) bzw. 24 Monaten (zweite Stufe).',
      'Filter nie ausklopfen oder waschen; beim Wechsel Atemschutz tragen und das Altmaterial sofort einpacken.',
      'Rahmen dicht einsetzen – Bypassluft macht jeden guten Filter wirkungslos.',
      'Wechseldatum am Filter und im Anlagenbuch dokumentieren.',
    ],
    werte: [
      'Empfehlung Außenluft: mindestens ePM1 ≥ 50 % (entspricht etwa früherem F7)',
      'Typische Enddruckdifferenz: 150 bis 250 Pa je Stufe',
      'Frühere Klassen: G4 → ISO Coarse · M5/F7 → ePM10/ePM1',
    ],
    normen: ['DIN EN ISO 16890', 'DIN EN 1822 (Schwebstofffilter)', 'VDI 6022'],
    verwandt: ['rlt_anlage', 'rlt_hygiene', 'waermerueckgewinnung'],
  },
  {
    id: 'rlt_hygiene',
    begriff: 'Hygiene in RLT-Anlagen (VDI 6022)',
    bereich: 'lueftung',
    kategorie: 'Regelwerk',
    synonyme: ['VDI 6022', 'Hygieneinspektion', 'Lüftungshygiene', 'Anlagenreinigung'],
    kurz: 'Raumlufttechnische Anlagen dürfen die Raumluftqualität nicht verschlechtern; VDI 6022 regelt Planung, Betrieb, Wartung und Hygieneinspektion.',
    funktion:
      'Feuchte, Staub und Nährstoffe sind die Grundlage für mikrobielles Wachstum. Deshalb müssen Bauteile reinigbar und zugänglich sein, stehendes Wasser muss vermieden werden und Filter sind rechtzeitig zu wechseln. Regelmäßige Hygieneinspektionen prüfen den Zustand durch Sichtkontrolle, Messungen und gegebenenfalls Probenahme.',
    aufbau: ['Zugängliche Revisionsöffnungen', 'Kondensatwannen mit Gefälle und Siphon', 'Filterstufen mit Differenzdrucküberwachung', 'Anlagenbuch mit Wartungs- und Inspektionsnachweisen'],
    einsatz: ['Alle RLT-Anlagen, die Aufenthaltsräume versorgen', 'Besonders Krankenhaus, Pflege, Lebensmittelbereiche, Schwimmbäder'],
    hinweise: [
      'Hygieneinspektion: Anlagen mit Befeuchter alle 2 Jahre, ohne Befeuchter alle 3 Jahre.',
      'Hygienekontrolle (kleiner Umfang) je nach Anlage jährlich oder halbjährlich.',
      'Personal muss nach VDI 6022 Kategorie A oder B geschult sein.',
      'Nach Baumaßnahmen Kanäle auf Verschmutzung prüfen und gegebenenfalls reinigen lassen.',
    ],
    normen: ['VDI 6022 Blatt 1', 'DIN EN 16798-3', 'ArbStättV'],
    verwandt: ['luftfilter', 'rlt_anlage', 'luftkanal'],
  },
  {
    id: 'schalldaempfer',
    begriff: 'Schalldämpfer und Schallschutz in der Lüftung',
    bereich: 'lueftung',
    kategorie: 'Bauteil',
    synonyme: ['Kulissenschalldämpfer', 'Rohrschalldämpfer', 'Telefonieschalldämpfer', 'Lüftungsgeräusch'],
    kurz: 'Ventilatoren und strömende Luft erzeugen Geräusche; Schalldämpfer, Querschnittswahl und Entkopplung halten die Raumpegel niedrig.',
    funktion:
      'Absorptionsschalldämpfer wandeln Schallenergie in Wärme um, indem die Luft an Mineralwollkulissen vorbeiströmt. Je länger der Dämpfer und je enger die Spalte, desto größer die Dämpfung – vor allem bei höheren Frequenzen. Telefonieschalldämpfer verhindern zusätzlich die Schallübertragung zwischen benachbarten Räumen über das Kanalnetz. Wichtig ist außerdem die Körperschallentkopplung des Gerätes über elastische Stutzen und Dämpferlager.',
    aufbau: ['Kulissenschalldämpfer im Rechteckkanal', 'Rohrschalldämpfer bei Wickelfalzrohren', 'Elastische Stutzen am Ventilator', 'Körperschallentkopplung des Gerätes'],
    einsatz: ['Hinter Ventilatoren und Volumenstromreglern', 'Zwischen Räumen unterschiedlicher Nutzung', 'Wohnungslüftung in Schlafräumen'],
    hinweise: [
      'Luftgeschwindigkeit begrenzen – das ist die wirksamste und billigste Schallschutzmaßnahme.',
      'Schalldämpfer nicht direkt nach einem Bogen setzen; Beruhigungsstrecke einhalten.',
      'Abriebfeste Oberflächen verwenden, damit keine Fasern in die Luft gelangen.',
    ],
    werte: ['Zielwert Schalldruckpegel: Schlafraum 25 dB(A), Wohnraum 30 dB(A), Büro 35 bis 40 dB(A)', 'Dämpfung typischer Rohrschalldämpfer: 10 bis 25 dB je nach Länge und Frequenz'],
    normen: ['DIN 4109', 'VDI 2081', 'DIN EN ISO 5135'],
    verwandt: ['luftkanal', 'rlt_anlage', 'schallschutz'],
  },
  {
    id: 'kuehllast',
    begriff: 'Kühllastberechnung',
    bereich: 'lueftung',
    kategorie: 'Berechnung',
    synonyme: ['VDI 2078', 'Kältebedarf', 'Kühllast', 'innere Lasten'],
    kurz: 'Die Kühllast ist die Wärmemenge, die abgeführt werden muss, damit die Raumtemperatur den Sollwert nicht überschreitet.',
    funktion:
      'Sie setzt sich aus äußeren Lasten (Sonneneinstrahlung durch Fenster, Transmission durch Bauteile) und inneren Lasten (Personen, Beleuchtung, Geräte) zusammen. Die Speicherfähigkeit des Gebäudes verzögert und dämpft die Lastspitzen, weshalb die Berechnung zeitabhängig erfolgt. Zusätzlich ist die Entfeuchtungsleistung zu berücksichtigen – Personen und Außenluft bringen Feuchte ein.',
    aufbau: ['Äußere Lasten: Strahlung, Transmission, Außenluft', 'Innere Lasten: Personen, Beleuchtung, Maschinen', 'Speicherwirkung des Bauwerks', 'latente Last aus Feuchteeintrag'],
    einsatz: ['Auslegung von Klimaanlagen und Kältemaschinen', 'Serverräume und Technikräume', 'Nachweise bei Sommerlichem Wärmeschutz'],
    hinweise: [
      'Verschattung und Sonnenschutz zuerst planen – jede eingesparte Last muss nicht gekühlt werden.',
      'Innere Lasten realistisch ansetzen; LED-Beleuchtung und moderne Rechner bringen deutlich weniger Wärme als alte Annahmen.',
      'Bei Flächenkühlung Taupunkt überwachen, sonst schlägt sich Feuchte auf der Oberfläche nieder.',
    ],
    werte: [
      'Personenwärme: etwa 70 bis 120 W je Person (sitzend bis leichte Tätigkeit)',
      'Bürogerät: Arbeitsplatzrechner 60 bis 150 W',
      'Sonneneintrag durch Fenster: bis 500 W/m² ohne Sonnenschutz',
      'Spezifische Kühllast Büro: 40 bis 80 W/m²',
    ],
    formeln: [
      { name: 'Kühlleistung Luft (sensibel)', formel: 'Q = V̇ · 0,34 · ΔT', erklaerung: 'Q in W, V̇ in m³/h, ΔT in K.' },
      { name: 'Gesamtkühlleistung mit Entfeuchtung', formel: 'Q = ṁ_Luft · Δh', erklaerung: 'Δh = Enthalpiedifferenz aus dem h,x-Diagramm in kJ/kg.' },
    ],
    normen: ['VDI 2078', 'DIN EN 16798', 'DIN 4108-2 (sommerlicher Wärmeschutz)'],
    verwandt: ['kaeltetechnik', 'klimageraet', 'luftzustand', 'rlt_anlage'],
  },
  {
    id: 'kaeltetechnik',
    begriff: 'Kältekreislauf und Kältemittel',
    bereich: 'lueftung',
    kategorie: 'Grundlagen',
    synonyme: ['Kältekreis', 'Kältemittel', 'Verdichter', 'Verdampfer', 'F-Gase', 'R32', 'R290'],
    kurz: 'Der Kompressionskältekreis transportiert Wärme von einem kalten auf ein wärmeres Niveau – er arbeitet in Kühlgeräten, Klimaanlagen und Wärmepumpen gleichermaßen.',
    funktion:
      'Im Verdampfer verdampft das Kältemittel bei niedrigem Druck und nimmt dabei Wärme auf. Der Verdichter hebt Druck und Temperatur an. Im Verflüssiger kondensiert das Kältemittel und gibt die Wärme ab. Das Expansionsventil entspannt es auf Verdampfungsdruck, wobei es abkühlt. Unterkühlung und Überhitzung sind die wichtigsten Betriebsgrößen: Überhitzung schützt den Verdichter vor Flüssigkeitsschlägen, Unterkühlung sichert die Flüssigkeitszufuhr zum Expansionsventil.',
    aufbau: ['Verdichter (Scroll, Rollkolben, Kolben)', 'Verflüssiger und Verdampfer', 'Thermostatisches oder elektronisches Expansionsventil', 'Sammler, Filtertrockner, Schauglas, Serviceventile'],
    einsatz: ['Klimageräte und Kaltwassersätze', 'Wärmepumpen', 'Gewerbekälte'],
    hinweise: [
      'Arbeiten am Kältekreis erfordern den Sachkundenachweis nach F-Gase-Verordnung (Kategorie I bis IV).',
      'Dichtheitskontrollen sind abhängig vom CO₂-Äquivalent der Füllmenge vorgeschrieben und zu dokumentieren.',
      'Brennbare Kältemittel wie R290 (Propan) erfordern besondere Aufstellungs- und Schutzmaßnahmen.',
      'Kältemittel niemals in die Atmosphäre ablassen – abgesaugt und fachgerecht entsorgt.',
      'Beim Löten von Kältemittelleitungen mit Stickstoff spülen, damit keine Zunderbildung entsteht.',
    ],
    werte: [
      'GWP-Werte: R290 (Propan) 3 · R32 675 · R134a 1430 · R410A 2088 · R744 (CO₂) 1',
      'Typische Überhitzung 5 bis 8 K, Unterkühlung 3 bis 8 K',
      'Leistungszahl Kälte: EER = Kälteleistung / elektrische Leistung',
    ],
    normen: ['F-Gase-Verordnung (EU) 517/2014', 'DIN EN 378', 'DIN EN 14511', 'BetrSichV'],
    verwandt: ['waermepumpe', 'klimageraet', 'kuehllast', 'gefahrstoffe'],
  },
  {
    id: 'klimageraet',
    begriff: 'Klimageräte und Splitanlagen',
    bereich: 'lueftung',
    kategorie: 'Anlage',
    synonyme: ['Splitgerät', 'Multisplit', 'VRF', 'Klimasplit', 'Innengerät'],
    kurz: 'Splitanlagen bestehen aus Außen- und Innengerät, die über Kältemittelleitungen verbunden sind; sie kühlen, heizen und entfeuchten.',
    funktion:
      'Im Kühlbetrieb arbeitet das Innengerät als Verdampfer: Raumluft wird über das Register geführt, abgekühlt und dabei entfeuchtet. Das Außengerät gibt die Wärme ab. Über ein Vierwegeventil lässt sich der Kreis umkehren, sodass das Gerät heizt. VRF-Systeme versorgen viele Innengeräte mit variablem Kältemittelstrom und können gleichzeitig kühlen und heizen.',
    aufbau: ['Außengerät mit Verdichter, Verflüssiger, Ventilator', 'Innengerät (Wand, Kassette, Kanal, Truhe) mit Wärmeübertrager und Filter', 'Kältemittelleitungen mit Bördel- oder Lötverbindungen, gedämmt', 'Kondensatablauf mit Gefälle oder Pumpe', 'Steuerleitung und Fernbedienung'],
    einsatz: ['Büros, Ladengeschäfte, Serverräume', 'Wohnräume und Schlafzimmer', 'Nachrüstung ohne Kanalnetz'],
    hinweise: [
      'Kondensatablauf ist die häufigste Störungsquelle – Gefälle sicherstellen, Siphon und Pumpe warten.',
      'Innengerät nicht direkt auf Personen ausrichten (Zugerscheinungen).',
      'Regelmäßige Reinigung von Filter und Verdampfer; Verkeimung im Kondensatbereich vermeiden.',
      'Leitungen vor dem Befüllen evakuieren und auf Dichtheit prüfen; Bördelverbindungen mit Drehmomentschlüssel anziehen.',
      'Außengerät schalltechnisch platzieren (Nachbarschaft, TA Lärm) und Kondensat im Heizbetrieb frostfrei ableiten.',
    ],
    werte: ['Übliche Leistung Innengerät: 2 bis 7 kW', 'SEER moderner Geräte: 6 bis 9', 'Zulässige Leitungslängen je nach Gerät 15 bis 75 m'],
    normen: ['DIN EN 378', 'DIN EN 14511', 'F-Gase-Verordnung', 'VDI 6022'],
    verwandt: ['kaeltetechnik', 'kuehllast', 'luftzustand'],
  },
  {
    id: 'luftzustand',
    begriff: 'Luftzustände und h,x-Diagramm',
    bereich: 'lueftung',
    kategorie: 'Grundlagen',
    synonyme: ['Mollier-Diagramm', 'relative Feuchte', 'Taupunkt', 'absolute Feuchte', 'Enthalpie'],
    kurz: 'Das h,x-Diagramm zeigt die Zusammenhänge zwischen Temperatur, Feuchte und Enthalpie feuchter Luft und erklärt Vorgänge wie Kühlen, Heizen, Befeuchten und Entfeuchten.',
    funktion:
      'Luft kann abhängig von ihrer Temperatur eine bestimmte Menge Wasserdampf aufnehmen. Die relative Feuchte gibt an, wie weit dieser Sättigungszustand erreicht ist. Kühlt Luft ab, steigt ihre relative Feuchte; beim Erreichen von 100 % ist der Taupunkt erreicht und Wasser fällt aus. Beim Erwärmen ohne Feuchtezufuhr bleibt die absolute Feuchte konstant, die relative Feuchte sinkt. Im h,x-Diagramm lassen sich diese Zustandsänderungen als Linien ablesen.',
    aufbau: ['Temperatur (Abszisse schräg)', 'Absolute Feuchte x in g Wasser je kg trockener Luft', 'Relative Feuchte φ als Kurvenschar', 'Enthalpie h in kJ/kg als Schräglinien', 'Taupunkt- und Feuchtkugeltemperatur'],
    einsatz: ['Auslegung von Klimaanlagen', 'Beurteilung von Tauwasserproblemen', 'Schwimmbad- und Trocknungstechnik', 'Kondensatvermeidung an Kaltwasserleitungen'],
    hinweise: [
      'Behaglichkeitsbereich: etwa 20 bis 26 °C bei 30 bis 65 % relativer Feuchte.',
      'Kaltwasserleitungen und Kältekanäle immer mit dampfdichter Dämmung versehen, sonst Tauwasser.',
      'Beim Entfeuchten über Kühlen muss die Luft unter den Taupunkt abgekühlt und danach wieder erwärmt werden.',
    ],
    werte: [
      'Sättigungsfeuchte: 20 °C ≈ 14,7 g/kg · 25 °C ≈ 20 g/kg · 10 °C ≈ 7,6 g/kg',
      'Enthalpie feuchter Luft bei 20 °C und 50 % rF: etwa 38 kJ/kg',
      'Spezifische Wärmekapazität Luft: etwa 1,0 kJ/(kg·K) bzw. 0,34 Wh/(m³·K)',
    ],
    formeln: [
      { name: 'Relative Feuchte', formel: 'φ = p_D / p_S · 100 %', erklaerung: 'Verhältnis von Wasserdampf-Partialdruck zu Sättigungsdruck.' },
      { name: 'Entfeuchtungsleistung', formel: 'ṁ_W = ṁ_L · (x1 − x2)', erklaerung: 'Wasserausfall in kg/h aus Luftmassenstrom und Feuchtedifferenz.' },
    ],
    normen: ['DIN EN 16798', 'VDI 2078', 'DIN 4108-3 (Tauwasser)'],
    verwandt: ['kuehllast', 'klimageraet', 'daemmung_geg', 'rlt_anlage'],
  },
  {
    id: 'kuechenlueftung',
    begriff: 'Küchen- und Bad-Entlüftung',
    bereich: 'lueftung',
    kategorie: 'Anlage',
    synonyme: ['Dunstabzug', 'Abluftanlage', 'DIN 18017-3', 'Badlüfter', 'Innenliegendes Bad'],
    kurz: 'Innenliegende Bäder und WCs werden mechanisch entlüftet; gewerbliche Küchen brauchen leistungsfähige Hauben mit Fettabscheidern.',
    funktion:
      'Nach DIN 18017-3 werden fensterlose Bäder und WCs über Einzel- oder Zentralventilatoren entlüftet, mit Nachlauf und definiertem Volumenstrom. In gewerblichen Küchen erfasst die Haube Wrasen und Fett; Aerosolabscheider und Fettfilter halten Fett zurück, das sonst im Kanal zur Brandlast wird. Bei gleichzeitigem Betrieb von Abluftanlage und raumluftabhängiger Feuerstätte ist eine Sicherheitseinrichtung erforderlich.',
    aufbau: ['Abluftventilator mit Rückschlagklappe und Nachlauf', 'Abluftleitung mit Brandschutzanforderungen', 'Küchenhaube mit Fettfiltern und Beleuchtung', 'Zuluftnachströmung über Überströmelemente'],
    einsatz: ['Innenliegende Sanitärräume', 'Wohnküchen mit Dunstabzug', 'Gewerbliche Küchen nach VDI 2052'],
    hinweise: [
      'Dunstabzug im Abluftbetrieb erzeugt Unterdruck – bei Feuerstätten Fensterkontaktschalter oder Unterdruckwächter vorsehen.',
      'Fettfilter regelmäßig reinigen; in gewerblichen Küchen ist die Reinigung des Kanals Pflicht.',
      'Abluft nicht in Schächte oder Dachräume blasen, sondern ins Freie führen.',
    ],
    werte: [
      'DIN 18017-3: Bad 40 m³/h, WC 25 m³/h Dauerbetrieb; Intensivlüftung Bad 60 m³/h, WC 50 m³/h',
      'Wohnungsdunstabzug: 150 bis 700 m³/h je nach Gerät',
      'Erfassungsgeschwindigkeit an der Haube: etwa 0,25 m/s',
    ],
    normen: ['DIN 18017-3', 'VDI 2052 (Küchen)', 'DIN 1946-6', 'DVGW-TRGI G 600'],
    verwandt: ['wohnungslueftung', 'verbrennungsluft', 'luftkanal'],
  },
];
