/**
 * Fachdatenbank – Sanitär: Trinkwasser, Entwässerung, Sanitärobjekte.
 */

export const SANITAER = [
  /* ------------------------------------------------------------ Trinkwasser */
  {
    id: 'trinkwasserhygiene',
    begriff: 'Trinkwasserhygiene',
    bereich: 'sanitaer',
    kategorie: 'Grundlagen',
    synonyme: ['Trinkwasserverordnung', 'TrinkwV', 'Stagnation', 'bestimmungsgemäßer Betrieb', 'Hygiene'],
    kurz: 'Trinkwasser ist ein Lebensmittel; die Installation muss so geplant, gebaut und betrieben werden, dass die Qualität bis zur Entnahmestelle erhalten bleibt.',
    funktion:
      'Die drei Stellschrauben sind Temperatur, Verweilzeit und Werkstoff. Kaltwasser soll dauerhaft unter 25 °C bleiben, Warmwasser am Speicheraustritt mindestens 60 °C erreichen. Wasser darf nicht stehen: Der bestimmungsgemäße Betrieb verlangt einen vollständigen Wasseraustausch spätestens alle 72 Stunden. Es dürfen nur Werkstoffe und Bauteile mit Eignungsnachweis (UBA-Bewertungsgrundlagen, DVGW-Zertifikat) eingebaut werden.',
    aufbau: [
      'Kurze Leitungswege, kleine Rohrinhalte, Reihen- oder Ringleitung statt langer Stichleitungen',
      'Getrennte Führung und Dämmung von Kalt- und Warmwasser',
      'Spülstationen für selten genutzte Entnahmestellen',
      'Probenahmestellen an definierten Punkten',
    ],
    einsatz: ['Neubau und Sanierung aller Trinkwasseranlagen', 'Objekte mit Nutzungsunterbrechung (Schulen, Ferienwohnungen, Sportstätten)'],
    hinweise: [
      'Tote Leitungsstränge zurückbauen, nicht nur absperren – abgesperrte Strecken sind hygienisch das größere Problem.',
      'Leitungen erst kurz vor Inbetriebnahme mit Wasser füllen; sonst mit ölfreier Druckluft prüfen.',
      'Bei Bauunterbrechung nicht gefüllt stehen lassen oder regelmäßig spülen und dokumentieren.',
      'Nach Arbeiten am Netz gründlich spülen und Inbetriebnahme protokollieren.',
    ],
    stoerungen: [
      'Erhöhte Koloniezahl oder Legionellenbefund: Stagnation, zu niedrige Warmwassertemperatur, Erwärmung des Kaltwassers',
      'Kaltwasser wird warm: gemeinsame Schachtführung mit Warmleitungen, fehlende Dämmung, Zirkulation falsch eingebunden',
    ],
    werte: [
      'Kaltwasser: unter 25 °C, Zielwert unter 20 °C',
      'Warmwasser: Speicheraustritt mindestens 60 °C, Zirkulationsrücklauf mindestens 55 °C',
      'Wasseraustausch spätestens alle 72 Stunden',
    ],
    normen: ['Trinkwasserverordnung', 'DIN EN 806', 'DIN 1988-200', 'DVGW W 551', 'VDI/DVGW 6023'],
    verwandt: ['legionellen', 'zirkulation', 'spuelung', 'daemmung_geg', 'rohrnetzberechnung'],
  },
  {
    id: 'legionellen',
    begriff: 'Legionellen und Legionellenschutz',
    bereich: 'sanitaer',
    kategorie: 'Grundlagen',
    synonyme: ['Legionelle', 'W 551', 'Legionellenprüfung', 'Legionellenschaltung'],
    kurz: 'Legionellen sind Bakterien, die sich in lauwarmem, stagnierendem Trinkwasser vermehren und beim Einatmen von Aerosolen eine schwere Lungenentzündung auslösen können.',
    funktion:
      'Das Wachstumsoptimum liegt zwischen 25 °C und 45 °C. Ab etwa 55 °C stagniert die Vermehrung, ab 60 °C sterben die Keime in kurzer Zeit ab. Deshalb arbeitet der Schutz über Temperaturhaltung (60/55 °C), kurze Leitungsinhalte und regelmäßigen Wasseraustausch. Gefährlich wird es beim Vernebeln – Duschen, Whirlpools, Rückkühlwerke.',
    aufbau: [
      'Trinkwassererwärmer mit 60 °C Austrittstemperatur',
      'Zirkulation mit Strangregulierventilen, Rücklauf mindestens 55 °C',
      'Kaltwasser konsequent unter 25 °C',
      'Probenahmestellen und Untersuchungsplan',
    ],
    einsatz: [
      'Großanlagen: Speicher über 400 Liter oder mehr als 3 Liter Inhalt zwischen Erwärmer und Entnahmestelle',
      'Vermietete Wohngebäude mit zentraler Erwärmung: Untersuchungspflicht',
      'Öffentliche Gebäude, Krankenhäuser, Pflegeheime',
    ],
    hinweise: [
      'Untersuchungsintervall bei Großanlagen in vermieteten Gebäuden: in der Regel alle drei Jahre, in öffentlichen Gebäuden jährlich.',
      'Technischer Maßnahmenwert: 100 KBE je 100 ml – bei Überschreitung Gefährdungsanalyse und Maßnahmen.',
      'Thermische Desinfektion: mindestens 70 °C an jeder Entnahmestelle für mindestens 3 Minuten – Verbrühungsgefahr, Anlage vorher sichern.',
      'Nach Stagnation (Urlaub, Leerstand) gründlich spülen, Duschkopf abnehmen und separat reinigen.',
    ],
    werte: ['Wachstum 25–45 °C', 'Absterben ab 60 °C', 'Maßnahmenwert 100 KBE/100 ml', 'Zirkulationsrücklauf ≥ 55 °C'],
    normen: ['DVGW W 551', 'DVGW W 557 (Reinigung/Desinfektion)', 'Trinkwasserverordnung', 'VDI 6023'],
    verwandt: ['trinkwasserhygiene', 'zirkulation', 'trinkwassererwaermer', 'spuelung'],
    vertiefungen: [
      {
        frage: 'Was passiert bei einer thermischen Desinfektion genau?',
        text: 'Bei der thermischen Desinfektion wird der gesamte Warmwasserkreis einschließlich aller Entnahmestellen auf mindestens 70 °C gebracht und diese Temperatur an jeder Zapfstelle für mindestens drei Minuten gehalten. Die Eiweißstrukturen der Legionellen denaturieren dabei. Entscheidend ist, dass jede Entnahmestelle einzeln durchgespült wird, denn in den Stichleitungen sitzt der Biofilm. Vorher sind Verbrühungsschutz und Information der Nutzer zu organisieren, thermostatische Mischer sind zu überbrücken oder auf Desinfektionsbetrieb zu stellen. Nach der Desinfektion ist die Ursache zu beheben – sonst ist der Befund nach wenigen Wochen zurück.',
      },
    ],
  },
  {
    id: 'hauswasserstation',
    begriff: 'Hausanschluss und Hauswasserstation',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Wasseranschluss', 'Hausanschlussraum', 'Übergabestelle', 'Wasserverteilung'],
    kurz: 'Die Hauswasserstation ist der Übergabepunkt zwischen Versorgungsnetz und Hausinstallation; die Einbaureihenfolge der Armaturen ist festgelegt.',
    funktion:
      'Vom Versorgungsnetz kommt die Anschlussleitung in den Hausanschlussraum. Dort folgen in Fließrichtung: Hauptabsperreinrichtung, Filter, Wasserzähler mit Absperrung, Rückflussverhinderer, Entleerung und Druckminderer. Der Filter schützt Zähler und Armaturen vor Partikeln, der Rückflussverhinderer verhindert das Zurückdrücken von Hauswasser ins Netz, der Druckminderer senkt den Netzdruck auf einen für die Installation verträglichen Wert.',
    aufbau: [
      'Hauptabsperreinrichtung (HAE)',
      'Filter (rückspülbar oder mit Wechselkerze)',
      'Wasserzähler mit Absperrungen vor und nach dem Zähler',
      'Rückflussverhinderer mit Entleerung',
      'Druckminderer mit Manometer',
      'Verteilung auf Steigstränge, Hausgartenzapfstelle mit eigener Sicherung',
    ],
    einsatz: ['Jedes an ein Versorgungsnetz angeschlossene Gebäude'],
    hinweise: [
      'Der Hausanschlussraum muss frostfrei, trocken, zugänglich und beleuchtbar sein.',
      'Filter spätestens alle sechs Monate rückspülen, Filterkerzen alle sechs Monate wechseln.',
      'Metallene Leitungen in den Hauptpotentialausgleich einbeziehen.',
      'Vor dem Zähler darf ohne Zustimmung des Versorgers nichts eingebaut werden.',
    ],
    werte: ['Ruhedruck über 5 bar: Druckminderer erforderlich', 'Üblicher eingestellter Hinterdruck: 3 bis 4 bar'],
    normen: ['DIN 1988-200', 'DIN EN 806', 'AVBWasserV', 'DVGW W 400'],
    verwandt: ['druckminderer', 'wasserzaehler', 'rueckflussverhinderer', 'filter_trinkwasser', 'sicherungsarmaturen'],
  },
  {
    id: 'druckminderer',
    begriff: 'Druckminderer',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Druckreduzierer', 'DRV', 'Druckminderventil'],
    kurz: 'Ein Druckminderer reduziert einen schwankenden, hohen Vordruck auf einen einstellbaren, konstanten Hinterdruck.',
    funktion:
      'Der Druckminderer ist ein federbelastetes Membranventil ohne Fremdenergie. Der Hinterdruck wirkt auf eine Membran, die gegen eine einstellbare Feder arbeitet. Steigt der Hinterdruck über den Sollwert, drückt die Membran den Ventilkegel in Richtung Sitz und drosselt – der Druck sinkt. Fällt der Hinterdruck beim Zapfen, öffnet die Feder das Ventil wieder. So bleibt der Ausgangsdruck weitgehend unabhängig vom Eingangsdruck (Proportionalregelung).',
    aufbau: [
      'Gehäuse aus Rotguss oder Messing mit Ein- und Ausgang',
      'Ventilsitz und Ventilkegel mit Weichdichtung',
      'Steuermembran, die den Hinterdruck abtastet',
      'Einstellfeder mit Sollwertverstellung',
      'integriertes Sieb, Manometeranschluss G 1/4',
    ],
    einsatz: [
      'Hauswasserstation hinter Filter und Zähler',
      'Druckabsenkung bei Ruhedruck über 5 bar (DIN 1988-200)',
      'Reduzierung von Fließgeräuschen, Wasserverbrauch und Armaturenverschleiß',
      'Etagenweise Druckanpassung in Hochhäusern',
    ],
    hinweise: [
      'In Fließrichtung einbauen, Sollwertfeder nach oben, gut zugänglich.',
      'Vordruck sollte mindestens 1 bar über dem Hinterdruck liegen, sonst regelt das Ventil nicht stabil.',
      'Einstellung drucklos vornehmen und am Manometer kontrollieren.',
      'Wartung: Sieb und Ventileinsatz nach Herstellerangabe prüfen, üblicherweise jährlich.',
    ],
    stoerungen: [
      'Hinterdruck steigt bei Nullentnahme langsam an: Ventilsitz verschmutzt oder Dichtung verschlissen',
      'Pfeifen und Druckschwankungen: Membran defekt, Feder falsch eingestellt oder Vordruck zu niedrig',
      'Zu wenig Durchfluss: Sieb zugesetzt',
    ],
    werte: ['Üblicher Hinterdruck 3 bis 4 bar', 'Einstellbereich meist 1,5 bis 6 bar', 'Mindestdifferenz Vor-/Hinterdruck etwa 1 bar'],
    normen: ['DIN EN 1567', 'DIN 1988-200', 'DIN EN 806'],
    verwandt: ['hauswasserstation', 'sicherheitsventil', 'ausdehnungsgefaess', 'schallschutz'],
    vertiefungen: [
      {
        frage: 'Was passiert, wenn zu viel Druck kommt?',
        text: 'Bleibt der Druckminderer defekt offen – etwa weil ein Fremdkörper auf dem Ventilsitz liegt oder die Membran gerissen ist – steigt der Hinterdruck bis auf Vordruckniveau an. Kommt erwärmtes Wasser dazu, erhöht die Wärmeausdehnung den Druck zusätzlich, weil das Wasser im geschlossenen Netz nicht ausweichen kann. Dann greift die nächste Sicherheitsstufe: Das Sicherheitsventil am Trinkwassererwärmer öffnet bei seinem Ansprechdruck (üblich 6 oder 10 bar) und bläst über die Ablaufleitung offen und sichtbar in den Trichtersiphon ab. Fehlt diese Absicherung oder ist sie verkalkt, wirkt der volle Druck auf die Installation: Armaturen tropfen, Schläuche und Verschraubungen werden undicht, Geräusche und Druckschläge nehmen zu, und im Extremfall wird der zulässige Betriebsdruck der Bauteile (PN 10 bzw. PN 16) überschritten – bis zum Rohr- oder Speicherschaden. Die richtige Vorgehensweise: Druck am Manometer prüfen, Ursache am Druckminderer beheben (Sieb, Ventileinsatz, Membran), Funktion des Sicherheitsventils durch Anlüften kontrollieren und den Vordruck des Ausdehnungsgefäßes prüfen.',
      },
    ],
  },
  {
    id: 'rueckflussverhinderer',
    begriff: 'Rückflussverhinderer',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Rückschlagventil', 'Rückschlagklappe', 'RV'],
    kurz: 'Ein Rückflussverhinderer lässt das Medium nur in eine Richtung strömen und sichert gegen Rückfließen in das vorgelagerte Netz.',
    funktion:
      'Ein federbelasteter Ventilteller oder eine Klappe wird von der Strömung geöffnet. Lässt die Strömung nach oder kehrt sie sich um, schließt die Feder beziehungsweise der Rückdruck das Ventil selbsttätig auf dem Sitz. Der Rückflussverhinderer sichert nur gegen Rückfließen und Rückdrücken – gegen Rücksaugen mit gefährlichen Stoffen ist er allein nicht ausreichend.',
    aufbau: ['Gehäuse aus Rotguss/Messing', 'Ventilteller oder Klappe mit Weichdichtung', 'Schließfeder', 'bei prüfbarer Ausführung zusätzliche Prüfstopfen'],
    einsatz: [
      'Hauswasserstation hinter dem Wasserzähler',
      'Vor Trinkwassererwärmern (zusammen mit Sicherheitsgruppe)',
      'In Zirkulations- und Pumpenleitungen',
      'In Druckleitungen von Hebeanlagen',
    ],
    hinweise: [
      'Einbaurichtung nach Pfeil beachten.',
      'Regelmäßig auf Funktion prüfen; prüfbare Ausführung erleichtert das.',
      'Nach dem Rückflussverhinderer steigt bei Erwärmung der Druck – Ausdehnungsgefäß oder Sicherheitsventil erforderlich.',
    ],
    stoerungen: ['Rauschen oder Schlagen: verschlissene Feder, Druckstöße', 'Rückfluss trotz Einbau: Dichtfläche verschmutzt oder verkalkt'],
    normen: ['DIN EN 13959', 'DIN EN 1717', 'DIN 1988-200'],
    verwandt: ['sicherungsarmaturen', 'systemtrenner', 'hauswasserstation', 'sicherheitsventil'],
  },
  {
    id: 'sicherungsarmaturen',
    begriff: 'Sicherungsarmaturen nach DIN EN 1717',
    bereich: 'sanitaer',
    kategorie: 'Regelwerk',
    synonyme: ['Flüssigkeitskategorien', 'EN 1717', 'Rohrtrenner', 'Rohrbelüfter', 'freier Auslauf'],
    kurz: 'Trinkwasser muss gegen jede Rückwirkung aus der Anlage gesichert werden; welche Armatur nötig ist, richtet sich nach der Gefährdung des angeschlossenen Mediums.',
    funktion:
      'DIN EN 1717 teilt Flüssigkeiten in fünf Kategorien ein – von Kategorie 1 (Trinkwasser) bis Kategorie 5 (mikrobiell oder toxisch besonders gefährlich). Zu jeder Kategorie gehört eine Mindestsicherung. Die Kennbuchstaben beschreiben das Wirkprinzip: A für freien Auslauf, B für Rohrunterbrecher, C für Rohrbelüfter, D für Rohrtrenner, E für Rückflussverhinderer, G für Systemtrenner.',
    aufbau: [
      'Kategorie 1: Trinkwasser – keine Sicherung nötig',
      'Kategorie 2: Beeinträchtigung nur durch Temperatur/Geschmack – Rückflussverhinderer (EA/EB)',
      'Kategorie 3: gesundheitsgefährdend durch weniger giftige Stoffe – Rohrbelüfter oder Systemtrenner CA',
      'Kategorie 4: giftige Stoffe – Systemtrenner BA',
      'Kategorie 5: mikrobiologisch/viral – freier Auslauf AA/AB',
    ],
    einsatz: [
      'Heizungsfüllung: Kategorie 3 bis 4 je nach Zusatz – Systemtrenner',
      'Gartenbewässerung mit Schlauch: Rohrbelüfter oder Systemtrenner',
      'Gewerbliche Anlagen, Labore, Waschanlagen: Kategorie 4 oder 5',
      'Feuerlöschanlagen: freier Auslauf AB',
    ],
    hinweise: [
      'Sicherungsarmatur immer so hoch bzw. so einbauen, dass ein freier Ablauf möglich ist.',
      'Sicherungsarmaturen sind wartungspflichtig – jährliche Prüfung dokumentieren.',
      'Schlauchanschlüsse an Zapfstellen brauchen mindestens einen Rohrbelüfter.',
    ],
    normen: ['DIN EN 1717', 'DIN 1988-100', 'DVGW W 570'],
    verwandt: ['systemtrenner', 'rueckflussverhinderer', 'trinkwasserhygiene'],
  },
  {
    id: 'systemtrenner',
    begriff: 'Systemtrenner BA',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['BA-Ventil', 'Systemtrennung', 'Rohrtrenner'],
    kurz: 'Der Systemtrenner BA trennt Trinkwasser sicher von einem nachgeschalteten System, indem er bei Rückwirkung eine Mittelzone zur Atmosphäre öffnet.',
    funktion:
      'Im Gehäuse liegen drei Druckzonen: Eingangszone, Mittelzone und Ausgangszone, getrennt durch zwei Rückflussverhinderer. Im Normalbetrieb ist der Druck in der Mittelzone um einen definierten Betrag niedriger als am Eingang. Sinkt diese Differenz – etwa beim Rückdrücken, Rückfließen oder Rücksaugen – öffnet ein membrangesteuertes Ablassventil und entleert die Mittelzone nach außen. Damit ist eine durchgehende Verbindung zum Trinkwasser physikalisch unterbrochen.',
    aufbau: ['Eingangs- und Ausgangs-Rückflussverhinderer', 'Mittelzone mit Ablassventil', 'Prüfstutzen für die Funktionsprüfung', 'vorgeschalteter Filter', 'Ablauftrichter mit freiem Auslauf'],
    einsatz: ['Heizungsfüll- und Ergänzungsleitungen', 'Gartenbewässerung und gewerbliche Anschlüsse', 'Alle Anwendungen der Flüssigkeitskategorie 4'],
    hinweise: [
      'Ablauf niemals fest an die Entwässerung anschließen – freier Auslauf über Trichtersiphon.',
      'Waagerecht einbauen, Prüfstutzen zugänglich halten.',
      'Jährliche Wartung mit Prüfset; Ablassen von Wasser im Betrieb ist ein Hinweis auf verschmutzte Rückflussverhinderer.',
      'Nach dem Füllen der Heizung die Verbindung trennen – ein dauerhafter Anschluss ist nur mit Systemtrenner zulässig.',
    ],
    stoerungen: ['Ständiges Tropfen aus dem Ablass: Schmutz auf dem Eingangsrückflussverhinderer oder zu geringer Vordruck'],
    normen: ['DIN EN 1717', 'DIN EN 12729', 'DIN 1988-100'],
    verwandt: ['sicherungsarmaturen', 'rueckflussverhinderer', 'heizungswasser'],
  },
  {
    id: 'wasserzaehler',
    begriff: 'Wasserzähler',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Wasseruhr', 'Zähler', 'Hauptzähler', 'Wohnungswasserzähler'],
    kurz: 'Der Wasserzähler erfasst die entnommene Wassermenge; der Hauptzähler gehört dem Versorger, Unterzähler dienen der Verbrauchsabrechnung.',
    funktion:
      'Flügelrad- und Mehrstrahlzähler nutzen die Strömung, um ein Flügelrad anzutreiben; die Umdrehungen werden mechanisch oder magnetisch auf das Zählwerk übertragen. Moderne Geräte arbeiten mit Ultraschall und messen die Laufzeitdifferenz zwischen zwei Signalen mit und gegen die Strömung – sie sind verschleißfrei und fernauslesbar.',
    aufbau: ['Zählergehäuse mit Messeinsatz', 'Zählerbügel mit Absperrung vor und nach dem Zähler', 'Rückflussverhinderer nach dem Zähler', 'Plombierung durch den Versorger'],
    einsatz: ['Hausanschluss', 'Wohnungsweise Erfassung', 'Gartenzähler für abzugsfähiges Wasser'],
    hinweise: [
      'Eichfrist beachten: Kaltwasserzähler in der Regel 6 Jahre, Warmwasserzähler 5 Jahre.',
      'Einbaulage nach Herstellerangabe (waagerecht/senkrecht), Beruhigungsstrecken einhalten.',
      'Am Hauptzähler nichts ohne Zustimmung des Versorgers verändern – Plombe.',
    ],
    stoerungen: ['Zähler läuft ohne Entnahme: Leckage in der Installation', 'Zähler zählt nicht: Messeinsatz blockiert oder verkalkt'],
    werte: ['Eichfrist Kaltwasser 6 Jahre, Warmwasser 5 Jahre', 'Übliche Nenngrößen im Wohnbau: Qn 2,5 bzw. Q3 4'],
    normen: ['DIN EN 14154', 'Mess- und Eichgesetz', 'AVBWasserV'],
    verwandt: ['hauswasserstation', 'leckage'],
  },
  {
    id: 'filter_trinkwasser',
    begriff: 'Trinkwasserfilter',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Feinfilter', 'Rückspülfilter', 'Schmutzfänger', 'Filter'],
    kurz: 'Der Filter hält Partikel wie Rost, Sand und Späne zurück und schützt Zähler, Armaturen und Geräte.',
    funktion:
      'Ein Siebeinsatz mit definierter Maschenweite trennt Feststoffe ab. Beim Rückspülfilter wird das Sieb durch Umkehr der Strömung gereinigt und der Schmutz in den Ablauf gespült; beim Wechselfilter wird die Kerze getauscht. Ein Differenzdruckmanometer zeigt die Verschmutzung an.',
    aufbau: ['Filtertasse mit Siebeinsatz (80–100 µm)', 'Rückspülvorrichtung mit Ablaufanschluss', 'Absperrung und Manometer'],
    einsatz: ['Direkt hinter der Hauptabsperreinrichtung', 'Vor empfindlichen Geräten und Enthärtungsanlagen'],
    hinweise: [
      'Rückspülfilter alle zwei Monate rückspülen, mindestens jedoch halbjährlich.',
      'Filterkerzen spätestens alle sechs Monate wechseln (Verkeimungsgefahr).',
      'Ablauf mit freiem Auslauf ausführen.',
    ],
    werte: ['Maschenweite üblich 80 bis 100 µm', 'Rückspülintervall: 2 Monate empfohlen, 6 Monate Maximum'],
    normen: ['DIN EN 13443-1', 'DIN 1988-200', 'DVGW W 512'],
    verwandt: ['hauswasserstation', 'wasserzaehler', 'enthaertung'],
  },
  {
    id: 'trinkwassererwaermer',
    begriff: 'Trinkwassererwärmer',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Warmwasserspeicher', 'Boiler', 'Speicher', 'Brauchwasserspeicher', 'Trinkwasserspeicher'],
    kurz: 'Anlage zur Erwärmung von Trinkwasser – als Speicher, Speicherladesystem oder Durchflusssystem ausgeführt.',
    funktion:
      'Beim indirekt beheizten Speicher überträgt ein Glattrohr- oder Rippenrohrwärmetauscher die Wärme aus dem Heizkreis an das Trinkwasser. Das kalte Wasser tritt unten ein, das warme oben aus; die Temperaturschichtung sorgt für gute Ausnutzung. Speicherladesysteme laden über einen externen Plattenwärmeübertrager mit hoher Leistung nach. Durchflusssysteme (Frischwasserstationen, Durchlauferhitzer) erwärmen nur die tatsächlich entnommene Menge und halten kein Warmwasser vor – hygienisch der beste Weg.',
    aufbau: [
      'Speicherbehälter, emailliert mit Magnesium-Schutzanode oder aus Edelstahl',
      'Wärmetauscher (Glattrohr, Rippenrohr) und Anschlüsse für Vor-/Rücklauf',
      'Sicherheitsgruppe: Sicherheitsventil, Rückflussverhinderer, Absperrung, Manometeranschluss',
      'Thermometer, Entleerung, Zirkulationsanschluss',
      'Wärmedämmung',
    ],
    einsatz: ['Ein- und Mehrfamilienhäuser', 'Kombination mit Solarthermie oder Wärmepumpe (dann bivalent mit zwei Wärmetauschern)'],
    hinweise: [
      'Betriebstemperatur mindestens 60 °C am Austritt (DVGW W 551).',
      'Schutzanode jährlich prüfen, spätestens bei 60 % Abtrag wechseln; Fremdstromanode ist wartungsärmer.',
      'Sicherheitsventil regelmäßig anlüften und Ablauf beobachtbar führen.',
      'Speicher bei Wärmepumpen größer und mit größerer Wärmetauscherfläche wählen, damit niedrige Vorlauftemperaturen reichen.',
      'Entkalkung und Reinigung nach Wasserhärte planen.',
    ],
    stoerungen: [
      'Warmwasser wird schnell kalt: Schichtung zerstört, Zirkulation zu stark oder falsch eingebunden',
      'Sicherheitsventil tropft bei Aufheizung: fehlendes oder defektes Ausdehnungsgefäß, zu hoher Vordruck',
      'Speicher rostet durch: Anode verbraucht',
    ],
    werte: [
      'Speichertemperatur: 60 °C Austritt, Zirkulationsrücklauf ≥ 55 °C',
      'Bedarf Wohnung: etwa 30 bis 50 Liter Warmwasser (60 °C) je Person und Tag',
      'Sicherheitsventil: 6 bar bis 200 l Inhalt, 10 bar bei höherem zulässigem Druck',
      'Aufheizung 200 l von 10 auf 60 °C: Q = 200 · 1,163 · 50 ≈ 11,6 kWh',
    ],
    formeln: [
      { name: 'Speicherwärme', formel: 'Q = V · 1,163 · ΔT', erklaerung: 'Q in Wh, V in Liter, ΔT in Kelvin.' },
      { name: 'Aufheizzeit', formel: 't = Q / P', erklaerung: 'Q in kWh, P in kW – ergibt die Zeit in Stunden.' },
    ],
    normen: ['DIN 4753', 'DVGW W 551', 'DIN EN 12897', 'DIN 1988-200'],
    verwandt: ['sicherheitsventil', 'zirkulation', 'legionellen', 'frischwasserstation', 'solarthermie'],
  },
  {
    id: 'frischwasserstation',
    begriff: 'Frischwasserstation',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Wohnungsstation', 'Durchflusssystem', 'FWS', 'Frischwassermodul'],
    kurz: 'Die Frischwasserstation erwärmt Trinkwasser im Durchflussprinzip über einen Plattenwärmeübertrager aus einem Pufferspeicher – ohne Warmwasservorrat.',
    funktion:
      'Wird gezapft, erkennt ein Strömungssensor die Entnahme und startet die drehzahlgeregelte Primärpumpe. Heizungswasser aus dem Puffer strömt durch den Plattenwärmeübertrager und erwärmt das durchströmende Trinkwasser. Die Regelung hält die Zapftemperatur konstant. Da nur wenige Liter Trinkwasser im Gerät stehen, ist das Legionellenrisiko sehr gering und eine Speicheruntersuchung entfällt meist.',
    aufbau: ['Plattenwärmeübertrager', 'drehzahlgeregelte Primärpumpe', 'Temperatur- und Volumenstromsensor', 'Regelung mit Zapftemperatur-Sollwert', 'optional Zirkulationsanschluss'],
    einsatz: ['Mehrfamilienhäuser mit zentralem Puffer', 'Wohnungsstationen je Nutzeinheit', 'Wärmepumpen- und Solaranlagen'],
    hinweise: [
      'Leistung nach Zapfprofil auslegen (z. B. gleichzeitiges Duschen in mehreren Wohnungen).',
      'Kalkbildung steigt mit der Primärtemperatur – Puffer nicht unnötig heiß fahren.',
      'Bei harten Wässern Enthärtung vorsehen oder Wärmeübertrager spülbar ausführen.',
    ],
    werte: ['Übliche Zapfleistung 30 bis 100 l/min je nach Gerät', 'Primärtemperatur typisch 60 bis 70 °C', 'Trinkwasserinhalt meist unter 3 Liter'],
    normen: ['DVGW W 551', 'DIN 1988-200', 'VDI 2072'],
    verwandt: ['trinkwassererwaermer', 'pufferspeicher', 'legionellen', 'enthaertung'],
  },
  {
    id: 'durchlauferhitzer',
    begriff: 'Durchlauferhitzer',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['E-Durchlauferhitzer', 'Gasdurchlauferhitzer', 'DLE'],
    kurz: 'Dezentrales Gerät, das Trinkwasser erst bei der Entnahme erwärmt – elektrisch oder gasbeheizt.',
    funktion:
      'Beim elektronischen Durchlauferhitzer misst die Regelung Zulauftemperatur und Volumenstrom und schaltet die Heizwendeln stufenlos so, dass die gewünschte Auslauftemperatur entsteht. Gasgeräte modulieren den Brenner. Weil kein Wasser bevorratet wird, entstehen keine Bereitschaftsverluste und kaum Legionellenrisiko; dafür ist die elektrische Anschlussleistung hoch.',
    aufbau: ['Heizblock mit Blankdraht- oder Rohrheizkörper bzw. Gasbrenner', 'Strömungssensor und Temperaturfühler', 'Sicherheitstemperaturbegrenzer', 'Druckfest (mehrere Zapfstellen) oder drucklos (eine Zapfstelle)'],
    einsatz: ['Einzelne Entnahmestellen weit vom Erwärmer', 'Gäste-WC, Werkstatt, Ferienwohnung', 'Sanierung ohne Warmwasserleitung'],
    hinweise: [
      'Elektroanschluss durch Elektrofachkraft; typisch 18 bis 27 kW Drehstrom, Zustimmung des Netzbetreibers erforderlich.',
      'Drucklose Geräte nur mit passender Niederdruckarmatur betreiben.',
      'Gasgeräte brauchen raumluftunabhängige Abgasführung oder ausreichende Verbrennungsluft.',
      'Mindestfließdruck und Mindestdurchfluss beachten, sonst schaltet das Gerät nicht ein.',
    ],
    werte: ['Elektrisch üblich 18 / 21 / 24 / 27 kW', 'Temperaturerhöhung: etwa 2 l/min je kW bei ΔT 30 K'],
    formeln: [
      { name: 'Leistungsbedarf', formel: 'P = V̇ · 1,163 · ΔT / 60', erklaerung: 'P in kW, V̇ in l/min, ΔT in K. Beispiel: 8 l/min, 35 K → 5,4 kW · 60/60 ≈ 19,5 kW.' },
    ],
    normen: ['DIN EN 60335-2-35', 'DIN 1988-200', 'DVGW-TRGI G 600 (Gasgeräte)'],
    verwandt: ['trinkwassererwaermer', 'elektro_grundlagen', 'gasgeraete'],
  },
  {
    id: 'zirkulation',
    begriff: 'Zirkulationssystem',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Zirkulationsleitung', 'Zirkulationspumpe', 'Zirku', 'Warmwasserzirkulation'],
    kurz: 'Die Zirkulation hält warmes Trinkwasser in Bewegung, damit an jeder Zapfstelle sofort warmes Wasser ansteht und die Temperatur hygienisch bleibt.',
    funktion:
      'Eine Pumpe fördert Warmwasser vom Speicher über die Steigleitungen und zurück in den Speicher. Strangregulierventile – meist mit Thermostatfunktion – verteilen den Volumenstrom so, dass jeder Strang mindestens 55 °C Rücklauftemperatur erreicht. Ohne Abgleich fließt das Wasser nur über den geringsten Widerstand und entfernte Stränge kühlen aus.',
    aufbau: ['Zirkulationspumpe mit Zeit- und/oder Temperatursteuerung', 'Rückflussverhinderer', 'Strangregulierventile (thermisch oder statisch)', 'Dämmung nach GEG', 'Einbindung in den Speicher unterhalb des Warmwasseraustritts'],
    einsatz: ['Erforderlich, wenn das Leitungsvolumen zwischen Erwärmer und entferntester Entnahmestelle 3 Liter übersteigt', 'Mehrfamilienhäuser, Hotels, Pflegeeinrichtungen'],
    hinweise: [
      'Abschaltung von maximal 8 Stunden am Tag ist zulässig – längere Stillstände sind hygienisch kritisch.',
      'Zirkulation nie in die Kaltwasserleitung einbinden.',
      'Zirkulationsleitung immer dämmen, sonst wird der Schacht zur Heizung des Kaltwassers.',
      'Nach dem Abgleich Temperaturen an den Strängen messen und protokollieren.',
    ],
    stoerungen: [
      'Ein Strang bleibt kalt: Strangregulierventil zu, Luft in der Leitung oder Rückflussverhinderer blockiert',
      'Kaltwasser wird warm: Zirkulation falsch eingebunden oder ungedämmt neben der Kaltleitung geführt',
    ],
    werte: ['Rücklauftemperatur ≥ 55 °C', 'maximal 5 K Temperaturgefälle im Zirkulationskreis', 'Abschaltzeit höchstens 8 h/Tag'],
    normen: ['DVGW W 551', 'DVGW W 553 (Bemessung)', 'DIN 1988-200', 'GEG'],
    verwandt: ['legionellen', 'trinkwassererwaermer', 'daemmung_geg', 'strangregulierventil'],
  },
  {
    id: 'rohrnetzberechnung',
    begriff: 'Rohrnetzberechnung Trinkwasser',
    bereich: 'sanitaer',
    kategorie: 'Berechnung',
    synonyme: ['DIN 1988-300', 'Spitzenvolumenstrom', 'Berechnungsdurchfluss', 'Dimensionierung', 'Rohrweite'],
    kurz: 'Die Rohrweiten werden aus dem Spitzenvolumenstrom, dem verfügbaren Druck und den zulässigen Fließgeschwindigkeiten berechnet.',
    funktion:
      'Für jede Entnahmestelle ist ein Berechnungsdurchfluss festgelegt. Aus der Summe der Berechnungsdurchflüsse eines Leitungsabschnitts wird über eine gebäudetypabhängige Funktion der Spitzenvolumenstrom ermittelt – denn nie laufen alle Zapfstellen gleichzeitig. Anschließend wird geprüft, ob der verfügbare Druck ausreicht: Versorgungsdruck minus geodätische Höhe, minus Druckverluste in Leitungen, Armaturen und Geräten, minus Mindestfließdruck an der ungünstigsten Entnahmestelle.',
    aufbau: [
      'Berechnungsdurchflüsse der Entnahmestellen aufnehmen',
      'Spitzenvolumenstrom je Abschnitt bestimmen',
      'Rohrweiten nach zulässiger Fließgeschwindigkeit wählen',
      'Druckbilanz für den ungünstigsten Fließweg aufstellen',
    ],
    einsatz: ['Neubauplanung', 'Sanierung und Nutzungsänderung', 'Nachweis für Hygiene (kleine Rohrinhalte)'],
    hinweise: [
      'Kleiner dimensionieren als früher: kleine Rohrinhalte sind hygienisch besser und tauschen das Wasser schneller aus.',
      'Fließgeschwindigkeit begrenzen, sonst Geräusche und Erosionskorrosion.',
      'Einzelzuleitungen zu Entnahmestellen möglichst kurz halten.',
    ],
    werte: [
      'Berechnungsdurchflüsse (l/s): Waschtisch 0,07 · Spültisch 0,07 · Geschirrspüler 0,07 · WC-Spülkasten 0,13 · Dusche 0,15 · Badewanne 0,15 · Waschmaschine 0,25 · Ausgussbecken 0,3 · WC-Druckspüler 1,0',
      'Mindestfließdruck an der Entnahmestelle: 1,0 bar (Geräte nach Herstellerangabe mehr)',
      'Zulässige Fließgeschwindigkeit: bis 2 m/s in durchströmten Leitungen, kurzzeitig bis 5 m/s in Stichleitungen',
      'Druckverlust je Meter: Richtwert 1 bis 3 mbar/m',
    ],
    formeln: [
      {
        name: 'Spitzenvolumenstrom (Wohngebäude)',
        formel: 'V̇s = a · (ΣV̇R)^b − c',
        erklaerung: 'Beiwerte nach Gebäudeart aus DIN 1988-300; für Wohngebäude a = 1,48, b = 0,19, c = 0,94 im Bereich bis 20 l/s.',
      },
      { name: 'Druckbilanz', formel: 'p_verf = p_Vers − p_geo − Σ(R·l + Z) − p_Arm − p_minFl', erklaerung: 'Alle Anteile in bar oder mbar; das Ergebnis muss größer null sein.' },
      { name: 'Geodätischer Druck', formel: 'p_geo = ρ · g · h', erklaerung: '10 m Höhenunterschied entsprechen etwa 1 bar.' },
    ],
    normen: ['DIN 1988-300', 'DIN EN 806-3', 'DIN 1988-200'],
    verwandt: ['hydraulikformeln', 'trinkwasserhygiene', 'druckminderer', 'druckerhoehungsanlage'],
  },
  {
    id: 'sanitaerarmaturen',
    begriff: 'Sanitärarmaturen',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Mischbatterie', 'Einhebelmischer', 'Thermostatarmatur', 'Eckventil', 'Auslaufarmatur'],
    kurz: 'Armaturen entnehmen, mischen und begrenzen Trinkwasser; entscheidend sind Geräuschverhalten, Verbrühschutz und Hygiene.',
    funktion:
      'Einhebelmischer regeln Menge und Temperatur über eine Keramikkartusche. Thermostatarmaturen halten die eingestellte Mischtemperatur über ein Dehnstoffelement konstant: Ändert sich Druck oder Temperatur einer Zulaufseite, verschiebt das Element den Regelkolben und passt das Mischverhältnis an. Eckventile trennen Gerät und Armatur von der Installation.',
    aufbau: ['Keramikkartusche oder Thermostatpatrone', 'Rückflussverhinderer in den Anschlüssen', 'Strahlregler (Perlator)', 'Eckventil mit Rosette und Anschlussschlauch'],
    einsatz: ['Waschtisch, Dusche, Wanne, Spüle', 'Geräteanschluss für Waschmaschine und Geschirrspüler', 'Öffentliche Sanitärräume (Selbstschluss- oder berührungslose Armaturen)'],
    hinweise: [
      'Armaturengruppe I für schutzbedürftige Räume verwenden (Schallschutz nach DIN 4109).',
      'Verbrühschutz: Thermostat mit 38-°C-Sperre, in Pflegebereichen zusätzlich begrenzen.',
      'Strahlregler regelmäßig reinigen oder tauschen – sie sind Hygieneschwachstellen.',
      'Vor der Montage Leitung spülen, damit keine Späne die Kartusche zerstören.',
    ],
    stoerungen: ['Tropfen: Kartusche oder Dichtung verschlissen', 'Schwankende Temperatur: Rückflussverhinderer verschmutzt oder Thermostatpatrone verkalkt', 'Geräusche: zu hoher Druck, Druckminderer prüfen'],
    werte: ['Mindestfließdruck 1,0 bar', 'Verbrühschutz-Sperre üblich bei 38 °C', 'Durchfluss Waschtischarmatur etwa 6 l/min mit Sparstrahlregler'],
    normen: ['DIN EN 200', 'DIN EN 1111 (Thermostate)', 'DIN 4109', 'DIN EN 1717'],
    verwandt: ['schallschutz', 'sanitaerobjekte', 'trinkwasserhygiene'],
  },
  {
    id: 'enthaertung',
    begriff: 'Wasserhärte und Enthärtung',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Wasserhärte', 'Kalk', 'Enthärtungsanlage', 'Weichwasseranlage', 'Ionenaustauscher'],
    kurz: 'Die Härte beschreibt den Gehalt an Calcium- und Magnesiumionen; ab etwa 14 °dH lohnt eine Enthärtung zum Schutz von Geräten und Leitungen.',
    funktion:
      'In der Enthärtungsanlage strömt das Wasser durch ein Harzbett aus Ionenaustauscherharz. Die Härtebildner Calcium und Magnesium werden gegen Natriumionen getauscht. Ist das Harz erschöpft, wird es mit Kochsalzlösung regeneriert und der Härteabtrag in den Abwasseranschluss gespült. Über eine Verschneideeinrichtung wird die gewünschte Resthärte eingestellt.',
    aufbau: ['Harzbehälter (oft doppelt für unterbrechungsfreien Betrieb)', 'Salzbehälter mit Soletank', 'Steuerventil mit Mengen- oder Zeitsteuerung', 'Verschneidung und Abwasseranschluss mit freiem Auslauf'],
    einsatz: ['Ab etwa 14 °dH sinnvoll', 'Vor Trinkwassererwärmern, Frischwasserstationen, Dampferzeugern', 'Gewerbliche Spülmaschinen und Kaffeetechnik'],
    hinweise: [
      'Resthärte nicht unter 6 °dH einstellen – zu weiches Wasser ist korrosiv und schmeckt fad.',
      'Anlage ist trinkwasserführend: Wartung nach DIN 19636 bzw. Herstellerangabe, in der Regel jährlich.',
      'Salzvorrat regelmäßig prüfen; nur Regeneriersalz nach DIN EN 973 verwenden.',
      'Bei Stagnation über Wochen Anlage spülen und desinfizieren.',
    ],
    werte: [
      'Härtebereiche: weich unter 8,4 °dH · mittel 8,4–14 °dH · hart über 14 °dH',
      '1 °dH entspricht 0,1783 mmol/l Erdalkaliionen',
      'Kalkablagerung: je 10 K höhere Speichertemperatur steigt die Ausfällung deutlich; ab 60 °C nimmt sie stark zu',
    ],
    normen: ['DIN 19636-100', 'DIN EN 14743', 'Trinkwasserverordnung', 'DVGW W 512'],
    verwandt: ['trinkwassererwaermer', 'filter_trinkwasser', 'trinkwasserhygiene'],
  },
  {
    id: 'dichtheitspruefung',
    begriff: 'Dichtheits- und Druckprüfung Trinkwasser',
    bereich: 'sanitaer',
    kategorie: 'Verfahren',
    synonyme: ['Druckprobe', 'abgedrückt', 'abdrücken', 'Dichtheitsprüfung', 'Belastungsprüfung'],
    kurz: 'Vor dem Verschließen wird das Leitungsnetz auf Dichtheit und Festigkeit geprüft und das Ergebnis protokolliert.',
    funktion:
      'Bevorzugt wird mit ölfreier Druckluft oder Inertgas geprüft, weil stehendes Wasser in noch nicht genutzten Leitungen hygienisch problematisch ist. Zuerst läuft die Dichtheitsprüfung mit niedrigem Druck, anschließend die Belastungsprüfung mit höherem Druck. Wird mit Wasser geprüft, muss die Anlage anschließend in Betrieb gehen oder regelmäßig gespült werden. Während der Prüfzeit darf der Druck nicht abfallen; Temperaturänderungen verfälschen das Ergebnis und müssen abgewartet werden.',
    aufbau: ['Prüfgerät bzw. Druckprüfpumpe mit geeichtem Manometer', 'Absperrungen, Endstopfen, Entlüftung', 'Prüfprotokoll mit Datum, Medium, Druck, Zeit und Unterschrift'],
    einsatz: ['Neuinstallation vor dem Verschließen von Wänden und Schächten', 'Nach Reparaturen und Erweiterungen', 'Abnahme durch Bauherr oder Planer'],
    hinweise: [
      'Bauteile mit geringerem zulässigem Druck (Geräte, Armaturen, Sicherheitsventile) abtrennen.',
      'Temperaturausgleich abwarten – 10 K Unterschied ändern den Druck deutlich.',
      'Bei Prüfung mit Wasser gefiltertes Trinkwasser verwenden und die Anlage danach nicht stehen lassen.',
      'Protokoll ist Teil der Dokumentation und wird vom Kunden gegengezeichnet.',
    ],
    werte: [
      'Luft-Dichtheitsprüfung: 150 mbar, Prüfzeit je nach Leitungsvolumen mindestens 120 Minuten',
      'Luft-Belastungsprüfung: 3 bar bis DN 50, 1 bar über DN 50, je 10 Minuten',
      'Wasserprüfung: 1,1-facher zulässiger Betriebsdruck nach ZVSHK-Merkblatt, Prüfzeit je nach Werkstoff',
      'Heizung: 1,3-facher Betriebsdruck (DIN EN 14336)',
    ],
    normen: ['DIN EN 806-4', 'ZVSHK-Merkblatt „Dichtheitsprüfung von Trinkwasser-Installationen“', 'DIN 18380 (VOB/C)'],
    verwandt: ['spuelung', 'pressverbindung', 'inbetriebnahme'],
  },
  {
    id: 'spuelung',
    begriff: 'Spülen und Inbetriebnahme der Trinkwasseranlage',
    bereich: 'sanitaer',
    kategorie: 'Verfahren',
    synonyme: ['gespült', 'Spülung', 'Spülprotokoll', 'Inbetriebnahme Trinkwasser'],
    kurz: 'Nach der Montage wird das Netz gespült, um Partikel, Montagerückstände und Keime auszutragen; erst danach geht die Anlage in Betrieb.',
    funktion:
      'Gespült wird mit filtriertem Trinkwasser abschnittsweise, stockwerksweise und von der Entnahmestelle aus nahe zum Erzeuger hin. Bei der Spülung mit Wasser/Luft-Gemisch werden zusätzlich Impulse eingebracht, die Ablagerungen mobilisieren. Alle Entnahmestellen werden geöffnet, die Mindestfließgeschwindigkeit muss erreicht werden. Anschließend folgen Inbetriebnahme, Einweisung des Betreibers und Übergabe der Dokumentation.',
    aufbau: ['Feinfilter vor der Spülung', 'Spülplan mit Abschnitten', 'Spülkompressor für Wasser-Luft-Spülung', 'Spül- und Übergabeprotokoll'],
    einsatz: ['Jede neue oder erweiterte Trinkwasserinstallation', 'Nach Stagnation oder Verunreinigung'],
    hinweise: [
      'Spülen unmittelbar vor der Inbetriebnahme; nicht Monate vorher.',
      'Strahlregler, Duschschläuche und Filtereinsätze vorher entfernen.',
      'Mindestens 2 Minuten je Entnahmestelle spülen, mindestens bis klares Wasser kommt und die Fließgeschwindigkeit erreicht ist.',
      'Übergabe mit Einweisung und Hinweis auf bestimmungsgemäßen Betrieb dokumentieren.',
    ],
    werte: ['Mindestfließgeschwindigkeit beim Spülen: 0,5 m/s in allen Teilstrecken', 'Anzahl gleichzeitig geöffneter Entnahmestellen nach DIN EN 806-4 abhängig von der Nennweite'],
    normen: ['DIN EN 806-4', 'DIN 1988-200', 'ZVSHK-Merkblatt Spülen', 'VDI/DVGW 6023'],
    verwandt: ['dichtheitspruefung', 'trinkwasserhygiene', 'inbetriebnahme'],
  },

  /* ------------------------------------------------------------ Entwässerung */
  {
    id: 'entwaesserung_grundlagen',
    begriff: 'Entwässerungstechnik – Grundlagen',
    bereich: 'sanitaer',
    kategorie: 'Grundlagen',
    synonyme: ['Abwasser', 'Entwässerung', 'DIN 1986-100', 'Schmutzwasser', 'Abflusssystem'],
    kurz: 'Gebäudeentwässerung führt Schmutz- und Regenwasser sicher, geruchsfrei und selbstreinigend ab; die Bemessung erfolgt über Anschlusswerte und Abflusskennzahlen.',
    funktion:
      'Das Abwasser fließt im Freispiegel, also nur durch Gefälle. Damit die Leitungen sich selbst reinigen, braucht es eine Mindestfließgeschwindigkeit; damit die Geruchverschlüsse nicht leergesaugt werden, braucht es Belüftung. Der Schmutzwasserabfluss wird aus den Anschlusswerten der Objekte und der Abflusskennzahl des Gebäudetyps berechnet. In Deutschland wird überwiegend System I (Einzelanschlussleitungen mit Teilfüllung 0,5) angewendet.',
    aufbau: [
      'Anschlussleitung vom Objekt zur Fallleitung',
      'Fallleitung mit Lüftungsleitung über Dach',
      'Sammelleitung im Keller oder abgehängt',
      'Grundleitung im Erdreich bis zum Anschlusskanal',
    ],
    einsatz: ['Alle Gebäude', 'Trenn- und Mischsystem je nach Kanalnetz'],
    hinweise: [
      'Richtungsänderungen mit 45°-Bögen ausführen, keine 90°-Abzweige liegend.',
      'Reinigungsöffnungen an Richtungsänderungen und in Fallleitungen vorsehen.',
      'Unterhalb der Rückstauebene liegende Ablaufstellen brauchen Rückstausicherung oder Hebeanlage.',
      'Gefälle konstant halten – Gegengefälle führt zu Ablagerungen.',
    ],
    werte: [
      'Anschlusswerte DU (l/s): Waschtisch 0,5 · Bidet 0,5 · Dusche 0,6–0,8 · Badewanne 0,8 · Spüle 0,8 · Geschirrspüler 0,8 · Waschmaschine 0,8 · WC mit 6-l-Spülkasten 2,0 · Bodenablauf DN 100 2,0',
      'Abflusskennzahl K: Wohngebäude 0,5 · Hotel/Krankenhaus 0,7 · öffentliche Toiletten 1,0 · Labor 1,2',
      'Mindestgefälle Sammel- und Grundleitungen: 0,5 % nach Berechnung, üblich 1 bis 2 %',
      'Unbelüftete Anschlussleitung: Richtwert maximal 4 m Länge, höchstens 3 Bögen, Gefälle 1 bis 5 %',
    ],
    formeln: [
      { name: 'Schmutzwasserabfluss', formel: 'Qww = K · √(Σ DU)', erklaerung: 'Qww in l/s, K = Abflusskennzahl, DU = Anschlusswerte in l/s.' },
      { name: 'Gesamtabfluss', formel: 'Qtot = Qww + Qc + Qp', erklaerung: 'Qc = Dauerabfluss, Qp = Pumpenzufluss.' },
    ],
    normen: ['DIN 1986-100', 'DIN EN 12056', 'DIN EN 752'],
    verwandt: ['fallleitung', 'geruchsverschluss', 'rueckstau', 'sml_rohr', 'ht_rohr', 'regenentwaesserung'],
  },
  {
    id: 'sml_rohr',
    begriff: 'SML-Abflussrohr (Gussrohr)',
    bereich: 'sanitaer',
    kategorie: 'Werkstoff',
    synonyme: ['SML', 'Gussrohr', 'Gussabflussrohr', 'muffenloses Gussrohr'],
    kurz: 'Gusseisernes Abflussrohr ohne Muffe nach DIN EN 877, das mit Verbindungsschellen gefügt wird – schwer, schalldämmend und sehr widerstandsfähig.',
    funktion:
      'Die Rohre werden stumpf gestoßen und mit einer Verbindungsschelle aus Edelstahlmantel und Elastomerdichtung kraft- und formschlüssig verbunden. Die hohe Masse dämpft Körper- und Luftschall wirksam, weshalb SML in Fallleitungen von Wohn- und Hotelgebäuden bevorzugt wird. Innen- und Außenbeschichtung schützen vor Korrosion; das Material ist nicht brennbar und beständig gegen heiße Abwässer.',
    aufbau: [
      'Rohr mit Innen- und Außenbeschichtung (Epoxid)',
      'Verbindungsschelle: CV-/Rapid-Verbinder mit Edelstahlmantel und EPDM-Manschette',
      'Formteile: Bogen, Abzweig, Reduzierung, Reinigungsstück',
    ],
    einsatz: ['Fall- und Sammelleitungen in Gebäuden', 'Schallschutzkritische Bereiche', 'Gewerbliche Küchen (heißes Abwasser)', 'Nennweiten DN 50 bis DN 300, üblich DN 70 / DN 100 / DN 125'],
    hinweise: [
      'Trennen mit Winkelschleifer und Trennscheibe oder mit Trennkette; Schnittkante entgraten und Korrosionsschutz nachbessern.',
      'Verbinderschrauben mit dem vorgegebenen Drehmoment anziehen (meist etwa 8 Nm) – nicht überdrehen.',
      'Fallleitung je Geschoss mit Festpunkt sichern, dazwischen Führungsschellen.',
      'Gewicht beachten: Montage zu zweit oder mit Hebehilfe.',
    ],
    werte: ['Wanddicke je nach Nennweite 3 bis 5 mm', 'Schalldämmung deutlich besser als bei Standard-PP', 'Verbinder mit Edelstahlmantel, Dichtung EPDM'],
    normen: ['DIN EN 877', 'DIN EN 12056', 'DIN 1986-100', 'DIN 4109'],
    verwandt: ['entwaesserung_grundlagen', 'fallleitung', 'schallschutz', 'rohrbefestigung'],
  },
  {
    id: 'ht_rohr',
    begriff: 'HT-Rohr (Innenentwässerung)',
    bereich: 'sanitaer',
    kategorie: 'Werkstoff',
    synonyme: ['HT', 'Hochtemperaturrohr', 'PP-Abflussrohr', 'graues Abflussrohr'],
    kurz: 'Abflussrohr aus Polypropylen für die Entwässerung innerhalb von Gebäuden, mit Steckmuffe und Lippendichtring verbunden.',
    funktion:
      'Das Rohr ist leicht, korrosionsfest und beständig gegen haushaltsübliche Abwässer. Die Steckmuffe erlaubt schnelle Montage und nimmt Längenänderungen auf. Wegen der geringen Masse ist der Schallschutz schwächer als bei Guss – dafür gibt es mehrschichtige, mineralisch gefüllte Varianten mit deutlich besseren Werten.',
    aufbau: ['Rohr aus PP, teils mehrschichtig', 'Steckmuffe mit Lippendichtring', 'Formteile: Bogen 15/30/45/87°, Abzweig, Reduzierung, Reinigungsrohr'],
    einsatz: ['Anschluss-, Sammel- und Fallleitungen im Gebäude', 'Nennweiten DN 32 bis DN 160, üblich DN 40 / 50 / 75 / 100 / 110'],
    hinweise: [
      'Schnittkante anfasen, Einstecktiefe markieren und 10 mm Dehnungsspalt lassen.',
      'Temperaturbeständig kurzzeitig bis etwa 95 °C – nicht für dauerhaft heiße Industrieabwässer.',
      'Nicht im Erdreich außerhalb des Gebäudes verwenden – dort KG-Rohr.',
      'Wärmedehnung von PP ist hoch (0,15 mm/m·K) – Schellen als Gleitlager setzen.',
    ],
    werte: ['Übliche Nennweiten: DN 40 (Waschtisch), DN 50 (Dusche/Spüle), DN 70/75 (Sammelleitung), DN 100/110 (WC, Fallleitung)'],
    normen: ['DIN EN 1451', 'DIN EN 12056', 'DIN 1986-100'],
    verwandt: ['steckmuffe', 'kg_rohr', 'sml_rohr', 'entwaesserung_grundlagen'],
  },
  {
    id: 'kg_rohr',
    begriff: 'KG-Rohr (Grundleitung im Erdreich)',
    bereich: 'sanitaer',
    kategorie: 'Werkstoff',
    synonyme: ['KG', 'Kanalgrundrohr', 'oranges Rohr', 'PVC-Rohr'],
    kurz: 'Orangebraunes PVC-U-Rohr für erdverlegte Grund- und Anschlussleitungen außerhalb und unterhalb des Gebäudes.',
    funktion:
      'Das Rohr ist druckfest genug für die Erdüberdeckung und beständig gegen Abwasser und Bodenfeuchte. Verbunden wird mit Steckmuffe und Lippendichtring unter Verwendung von Gleitmittel. Die Bettung im Sandbett ist entscheidend: Eine punktuelle Auflage führt zu Brüchen und Rissen.',
    aufbau: ['Rohr aus PVC-U, Ringsteifigkeitsklasse SN 4 oder SN 8', 'Steckmuffe mit Dichtring', 'Formteile, Übergänge auf Guss oder Steinzeug'],
    einsatz: ['Grundleitungen unter der Bodenplatte', 'Anschlusskanal zum öffentlichen Netz', 'Regenwasserleitungen im Erdreich'],
    hinweise: [
      'Sandbett mindestens 10 cm, seitlich und oberhalb lagenweise verdichten.',
      'Gefälle gleichmäßig herstellen und mit Laser oder Schlauchwaage kontrollieren.',
      'Reinigungsrohre und Schächte an Richtungsänderungen vorsehen.',
      'Vor dem Verfüllen Dichtheitsprüfung nach DIN EN 1610 durchführen und dokumentieren.',
    ],
    werte: ['Nennweiten DN 100 bis DN 500, üblich DN 110/125/160', 'Übliches Gefälle 1 bis 2 %', 'Mindestüberdeckung meist 0,8 m (frostfrei)'],
    normen: ['DIN EN 1401', 'DIN EN 1610', 'DIN 1986-100'],
    verwandt: ['entwaesserung_grundlagen', 'rueckstau', 'regenentwaesserung'],
  },
  {
    id: 'fallleitung',
    begriff: 'Fallleitung und Lüftung der Entwässerung',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Fall-Leitung', 'Hauptlüftung', 'Nebenlüftung', 'Lüftungsleitung', 'Sammelleitung'],
    kurz: 'Die Fallleitung führt das Abwasser der Stockwerke nach unten; die über Dach geführte Hauptlüftung verhindert Über- und Unterdruck.',
    funktion:
      'Fallendes Abwasser reißt Luft mit. Ohne Belüftung entsteht hinter dem Wasserpfropfen Unterdruck, der die Geruchverschlüsse leersaugt, und vor ihm Überdruck, der Sperrwasser herausdrückt. Die Hauptlüftung über Dach in voller Nennweite gleicht die Drücke aus. Zusätzlich gibt es Nebenlüftungen (parallele Lüftungsleitung), Sekundärlüftung und – als Ersatz im Gebäudeinneren – Rohrbelüfter, die nur Luft einlassen.',
    aufbau: ['Fallleitung in gleichbleibender Nennweite', 'Hauptlüftung über Dach, mindestens 100 mm über Dachfläche', 'Übergang zur Sammelleitung mit zwei 45°-Bögen', 'Reinigungsöffnung am Fuß der Fallleitung'],
    einsatz: ['Mehrgeschossige Gebäude', 'Anschluss mehrerer Objekte an einen Strang'],
    hinweise: [
      'Fallleitung nicht verziehen; wo unvermeidbar, mit 45°-Bögen und Belüftung ausführen.',
      'Lüftung nicht in Fensternähe ausmünden lassen (Geruch).',
      'Reinigungsöffnungen zugänglich halten, nicht zumauern.',
      'Am Fuß der Fallleitung entstehen die höchsten Drücke – dort keine Anschlussleitung unmittelbar anschließen (Abstandsregel beachten).',
    ],
    werte: [
      'Abflussvermögen Fallleitung mit Hauptlüftung (Füllungsgrad 0,33): DN 70 ≈ 1,5 l/s · DN 90 ≈ 2,7 l/s · DN 100 ≈ 4,0 l/s · DN 125 ≈ 5,8 l/s · DN 150 ≈ 9,5 l/s',
      'Lüftungsleitung in voller Nennweite über Dach führen',
    ],
    normen: ['DIN EN 12056-2', 'DIN 1986-100'],
    verwandt: ['entwaesserung_grundlagen', 'geruchsverschluss', 'rohrbelueftungsventil', 'sml_rohr'],
  },
  {
    id: 'geruchsverschluss',
    begriff: 'Geruchsverschluss (Siphon)',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Siphon', 'Geruchverschluss', 'Sifon', 'Tauchbogen'],
    kurz: 'Der Geruchsverschluss hält mit einer stehenden Wassersäule die Kanalgase aus dem Raum.',
    funktion:
      'Das ablaufende Wasser füllt eine U-förmige Kammer. Die Sperrwasserhöhe von mindestens 50 mm verschließt die Leitung gasdicht. Bei jedem Ablauf wird das Sperrwasser ausgetauscht. Verliert der Verschluss sein Wasser – durch Verdunstung, Unterdruck oder Heberwirkung – dringt Kanalgeruch in den Raum.',
    aufbau: ['Tauchrohr und Ablaufbogen', 'Reinigungsöffnung oder abschraubbare Tasse', 'teilweise Geräteanschluss für Waschmaschine/Geschirrspüler'],
    einsatz: ['Alle Entwässerungsgegenstände: Waschtisch, Dusche, Wanne, Spüle, Bodenablauf', 'Trichtersiphon für Sicherheitsventil- und Systemtrennerabläufe'],
    hinweise: [
      'Sperrwasserhöhe mindestens 50 mm (Bodenabläufe mit Rückstauverschluss teils mehr).',
      'Bei selten genutzten Abläufen Verdunstung beachten – Nachfüllen oder Trockenverschluss (Membran) verwenden.',
      'Wird Sperrwasser abgesaugt, liegt ein Belüftungsproblem vor – nicht mit größerem Siphon kaschieren.',
      'Waschmaschinen nicht über einen ungeeigneten Geräteanschluss ohne Belüftung anschließen.',
    ],
    stoerungen: [
      'Gluckern und Geruch: Unterdruck in der Fallleitung durch fehlende oder zu kleine Lüftung',
      'Ablauf zieht langsam: Siphon verstopft oder Gefälle zu gering',
    ],
    werte: ['Sperrwasserhöhe ≥ 50 mm', 'Anschlusswert Waschtisch 0,5 l/s'],
    normen: ['DIN EN 274', 'DIN EN 12056-2', 'DIN 1986-100'],
    verwandt: ['fallleitung', 'entwaesserung_grundlagen', 'bodenablauf'],
  },
  {
    id: 'rohrbelueftungsventil',
    begriff: 'Rohrbelüfter (Belüftungsventil)',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Belüftungsventil', 'Lüftungsventil', 'Rohrbelüfter', 'Rohrentlüfter'],
    kurz: 'Ein Rohrbelüfter lässt bei Unterdruck Luft in die Entwässerungsleitung einströmen, verhindert aber den Austritt von Kanalgas.',
    funktion:
      'Im Gehäuse sitzt eine leichte Membran oder ein Teller, der durch sein Eigengewicht auf dem Sitz liegt. Entsteht in der Leitung Unterdruck, hebt der Teller ab und Luft strömt nach – die Geruchverschlüsse bleiben gefüllt. Bei Überdruck presst der Teller dichter auf den Sitz, sodass keine Luft nach außen gelangt. Ein Rohrbelüfter ersetzt deshalb keine Hauptlüftung über Dach, sondern ergänzt sie.',
    aufbau: ['Gehäuse mit Membran/Teller', 'Anschlussmuffe passend zur Leitung', 'teils mit Revisionsdeckel'],
    einsatz: ['Anschlussleitungen ohne eigene Lüftung', 'Nachrüstung im Bestand', 'Dachgeschossausbau ohne Lüftungsdurchführung'],
    hinweise: [
      'Immer frostfrei, zugänglich und über dem höchsten Wasserstand einbauen.',
      'Nicht in Hohlräume einbauen, die keine Luft nachliefern können.',
      'Mindestens eine Hauptlüftung über Dach je Gebäude bleibt erforderlich.',
    ],
    normen: ['DIN EN 12380', 'DIN 1986-100'],
    verwandt: ['fallleitung', 'geruchsverschluss', 'entwaesserung_grundlagen'],
  },
  {
    id: 'rueckstau',
    begriff: 'Rückstau und Rückstausicherung',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Rückstauebene', 'Rückstauverschluss', 'Rückstauklappe', 'Kellerüberflutung'],
    kurz: 'Staut sich der Kanal, kann Abwasser in tiefliegende Räume zurückdrücken; Ablaufstellen unterhalb der Rückstauebene müssen gesichert werden.',
    funktion:
      'Als Rückstauebene gilt in der Regel die Straßenoberkante am Anschlusspunkt. Alle Ablaufstellen darunter sind gefährdet. Sicher ist nur die Hebeanlage mit Rückstauschleife über die Rückstauebene. Rückstauverschlüsse sind nur unter engen Voraussetzungen zulässig: kein WC-Anschluss über einen einfachen Verschluss, Gefälle zum Kanal, untergeordnete Nutzung und Verzicht während des Rückstaus möglich.',
    aufbau: ['Rückstauverschluss Typ 2/3 für fäkalienfreies, Typ 3F für fäkalienhaltiges Abwasser', 'Hebeanlage mit Druckleitung und Rückstauschleife', 'Zugänglicher Einbauort, Revisionsschacht'],
    einsatz: ['Kellerbäder, Waschküchen, Garagen, Souterrainwohnungen', 'Lichtschächte und Kellereingänge'],
    hinweise: [
      'Rückstauverschlüsse sind wartungspflichtig – halbjährliche Prüfung, Betriebsverschluss geschlossen halten.',
      'Ablaufstellen oberhalb der Rückstauebene niemals über eine Sicherung führen, sonst staut sich das Wasser dort.',
      'Versicherungsschutz hängt oft am ordnungsgemäßen Rückstauschutz – Nachweis dokumentieren.',
    ],
    normen: ['DIN EN 13564', 'DIN 1986-100', 'DIN EN 12056-4'],
    verwandt: ['hebeanlage', 'entwaesserung_grundlagen', 'kg_rohr'],
  },
  {
    id: 'hebeanlage',
    begriff: 'Abwasserhebeanlage',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Hebeanlage', 'Fäkalienhebeanlage', 'Pumpstation', 'Schmutzwasserpumpe'],
    kurz: 'Eine Hebeanlage fördert Abwasser aus Räumen unterhalb der Rückstauebene über eine Schleife oberhalb dieser Ebene in die Grundleitung.',
    funktion:
      'Das Abwasser läuft in einen geschlossenen, geruchsdichten Sammelbehälter. Erreicht der Füllstand den Einschaltpunkt, startet die Pumpe und fördert das Wasser über die Druckleitung. Diese wird über die Rückstauebene geführt (Rückstauschleife) und erst danach mit Gefälle in die Grundleitung eingebunden. Damit kann Rückstau aus dem Kanal nicht in die Räume gelangen.',
    aufbau: [
      'Sammelbehälter, geruchs- und druckdicht',
      'Pumpe mit Schneidwerk (fäkalienhaltig) oder Freistromrad',
      'Rückflussverhinderer und Absperrschieber in der Druckleitung',
      'Niveausteuerung mit optischem und akustischem Alarm',
      'Entlüftung über Dach',
    ],
    einsatz: ['Kellerbäder und Waschküchen', 'Tiefgaragen (dort fäkalienfrei mit Abscheider)', 'Nachträglicher Einbau von Sanitärräumen im Untergeschoss'],
    hinweise: [
      'Rückstauschleife ist zwingend – ohne sie ist die Anlage wirkungslos.',
      'Wartung nach DIN EN 12056-4: Einfamilienhaus jährlich, Mehrfamilienhaus halbjährlich, Gewerbe vierteljährlich.',
      'Keine Hygieneartikel, Tücher oder Fette einleiten – häufigste Störungsursache.',
      'Alarmgeber an einer Stelle anbringen, an der er gehört wird.',
    ],
    stoerungen: ['Pumpe läuft, fördert aber nicht: Laufrad blockiert oder Rückflussverhinderer klemmt', 'Ständiges Ein- und Ausschalten: Rückflussverhinderer undicht, Wasser läuft zurück'],
    normen: ['DIN EN 12050', 'DIN EN 12056-4', 'DIN 1986-100'],
    verwandt: ['rueckstau', 'entwaesserung_grundlagen', 'instandhaltung'],
  },
  {
    id: 'regenentwaesserung',
    begriff: 'Regenentwässerung',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Dachentwässerung', 'Regenwasser', 'Notentwässerung', 'Regenspende', 'Freispiegelentwässerung'],
    kurz: 'Dach- und Hofflächen werden nach der örtlichen Regenspende bemessen; zusätzlich ist eine Notentwässerung für Starkregen vorzusehen.',
    funktion:
      'Grundlage ist die Berechnungsregenspende r(5,5) – die Regenmenge, die statistisch alle fünf Jahre für fünf Minuten auftritt. Aus wirksamer Dachfläche, Regenspende und Abflussbeiwert ergibt sich der Regenwasserabfluss. Für den Jahrhundertregen r(5,100) muss die Differenz über eine Notentwässerung frei auf das Grundstück abgeführt werden, damit die Statik des Daches nicht überlastet wird. Neben der Freispiegelentwässerung gibt es die Druckströmungsentwässerung, bei der die Leitung vollgefüllt und mit Unterdruck arbeitet.',
    aufbau: ['Dachrinne oder Dachablauf (Gully)', 'Regenfallleitung', 'Grundleitung oder Versickerung/Rückhaltung', 'Notüberlauf oder Notgully mit freiem Auslauf'],
    einsatz: ['Alle Dach- und befestigten Flächen', 'Flachdächer besonders kritisch – dort Notentwässerung zwingend'],
    hinweise: [
      'Örtliche Regenspende beim Kanalnetzbetreiber oder aus KOSTRA-Daten ermitteln.',
      'Notentwässerung muss frei auf eine schadlos überflutbare Fläche münden – nicht in die Grundleitung.',
      'Abflussbeiwert je Fläche berücksichtigen (Flachdach 1,0, Kiesdach 0,5, Gründach je nach Aufbau 0,3 bis 0,7).',
      'Regenwasser darf nicht in die Schmutzwasserleitung eingeleitet werden, wenn ein Trennsystem vorliegt.',
    ],
    formeln: [
      { name: 'Regenwasserabfluss', formel: 'Q = r(5,5) · A · C / 10.000', erklaerung: 'Q in l/s, r in l/(s·ha), A = Fläche in m², C = Abflussbeiwert.' },
      { name: 'Notentwässerung', formel: 'Q_not = (r(5,100) − r(5,5)) · A · C / 10.000', erklaerung: 'Die Differenz muss die Notentwässerung abführen können.' },
    ],
    werte: ['Typische Berechnungsregenspende r(5,5): 200 bis 400 l/(s·ha) je nach Ort', 'Jahrhundertregen r(5,100) etwa das Zwei- bis Dreifache'],
    normen: ['DIN 1986-100', 'DIN EN 12056-3', 'DIN EN 752'],
    verwandt: ['entwaesserung_grundlagen', 'regenwassernutzung', 'kg_rohr'],
  },
  {
    id: 'bodenablauf',
    begriff: 'Bodenablauf und Reinigungsöffnung',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['Bodeneinlauf', 'Gully', 'Putzstück', 'Reinigungsrohr', 'Revisionsöffnung'],
    kurz: 'Bodenabläufe entwässern Flächen; Reinigungsöffnungen ermöglichen das Reinigen und Kamerabefahren der Leitungen.',
    funktion:
      'Der Bodenablauf besteht aus Ablauftopf, Geruchverschluss-Einsatz und Rost. In Nassräumen wird er mit der Bauwerksabdichtung verklebt (Klemmflansch), damit kein Wasser in die Konstruktion läuft. Reinigungsöffnungen werden an Richtungsänderungen, am Fuß von Fallleitungen und in langen Sammelleitungen gesetzt, damit Verstopfungen ohne Bauarbeiten beseitigt werden können.',
    aufbau: ['Ablauftopf mit Aufsatz und Rost', 'Geruchverschluss-Einsatz (herausnehmbar)', 'Klemmflansch für die Abdichtung', 'Reinigungsrohr mit dichtem Deckel'],
    einsatz: ['Duschen, Waschküchen, Heizräume, Garagen, Hofflächen', 'Grundleitungen und Sammelleitungen'],
    hinweise: [
      'Reinigungsöffnungen müssen dauerhaft zugänglich bleiben – Lage dokumentieren.',
      'In selten genutzten Räumen Sperrwasser nachfüllen oder Trockenverschluss verwenden.',
      'Rost und Einsatz regelmäßig reinigen.',
      'Bei bodengleichen Duschen Abdichtung nach DIN 18534 mit dem Ablauf verbinden.',
    ],
    normen: ['DIN EN 1253', 'DIN 1986-100', 'DIN 18534'],
    verwandt: ['geruchsverschluss', 'entwaesserung_grundlagen', 'sanitaerobjekte'],
  },

  /* ------------------------------------------------------------ Objekte */
  {
    id: 'vorwandinstallation',
    begriff: 'Vorwandinstallation',
    bereich: 'sanitaer',
    kategorie: 'Anlage',
    synonyme: ['Vorwand', 'Sanitärmodul', 'Installationselement', 'Unterputzspülkasten', 'Trockenbau Sanitär'],
    kurz: 'Tragende Montageelemente vor der Wand nehmen Spülkasten, Rohrleitungen und Befestigungen auf – unabhängig von der Tragfähigkeit der Wand.',
    funktion:
      'Ein verzinkter Stahlrahmen wird am Boden und an der Wand befestigt und mit Gewindestangen ausgerichtet. Er trägt die Objektlasten und nimmt Spülkasten, Wasser- und Abwasseranschlüsse auf. Die Beplankung erfolgt mit feuchtebeständigen Bauplatten. Für den Schallschutz wird der Rahmen mit Dämmstreifen vom Baukörper entkoppelt.',
    aufbau: ['Stahlrahmen mit höhenverstellbaren Füßen', 'Unterputzspülkasten mit Betätigungsplatte und Revisionsöffnung', 'Anschlussbogen DN 90/100 und Wasseranschlüsse', 'Schallschutzset und Dämmstreifen', 'Beplankung und Abdichtung'],
    einsatz: ['Wand-WC, Wand-Bidet, Waschtisch, Urinal', 'Sanierung ohne Wandöffnung', 'Barrierefreie Bäder mit Stützklappgriffen'],
    hinweise: [
      'Rahmen lot- und waagerecht ausrichten, Befestigungspunkte nicht auf Estrich, sondern auf Rohboden setzen.',
      'Montagehöhen: WC-Sitzhöhe fertig etwa 40 bis 42 cm (barrierefrei 46 bis 48 cm), Waschtisch Oberkante 85 cm (barrierefrei 80 cm).',
      'Revisionsöffnung des Spülkastens zugänglich halten.',
      'Vor dem Verschließen Dichtheitsprüfung durchführen.',
    ],
    normen: ['DIN EN 997 (WC)', 'DIN 4109', 'DIN 18040-2 (barrierefrei)', 'DIN 18534 (Abdichtung)'],
    verwandt: ['sanitaerobjekte', 'schallschutz', 'dichtheitspruefung', 'barrierefrei'],
  },
  {
    id: 'sanitaerobjekte',
    begriff: 'Sanitärobjekte und ihre Montage',
    bereich: 'sanitaer',
    kategorie: 'Bauteil',
    synonyme: ['WC', 'Waschtisch', 'Dusche', 'Badewanne', 'Urinal', 'Spülkasten'],
    kurz: 'Waschtisch, WC, Dusche, Wanne und Urinal werden nach festen Montagehöhen und mit passender Abdichtung eingebaut.',
    funktion:
      'Sanitärobjekte bestehen meist aus Sanitärkeramik (Vitreous China), Acryl oder Stahl-Email. Sie werden entweder an der Wand (Vorwandelement) oder am Boden befestigt. Wichtig sind spannungsfreie Montage auf Dichtungsscheiben, korrekte Anschlusshöhen und der dichte Übergang zur Bauwerksabdichtung. Spülkästen arbeiten mit Füll- und Ablaufventil und lassen sich auf zwei Spülmengen einstellen.',
    aufbau: ['Objekt mit Befestigungssatz und Dichtungen', 'Ab- und Überlaufgarnitur', 'Geruchverschluss', 'Anschlussleitungen mit Eckventil', 'Silikonfuge als Wartungsfuge'],
    einsatz: ['Wohnungsbau, Hotel, Schule, Pflege', 'Barrierefreie Ausstattung nach DIN 18040'],
    hinweise: [
      'Standardhöhen: Waschtisch OK 85 cm · WC-Sitz 40–42 cm · Duscharmatur 100–120 cm · Wannenarmatur 60–70 cm · Urinal OK 60–65 cm.',
      'Keramik nie verspannen – Dichtungsscheiben und Kunststoffhülsen verwenden.',
      'Silikonfuge ist eine Wartungsfuge und kein Ersatz für die Abdichtung.',
      'Spülmenge einstellen: üblich 6 bzw. 3 Liter Teilspülung.',
    ],
    stoerungen: ['Spülkasten läuft ständig nach: Ablaufventil undicht oder Füllventil falsch eingestellt', 'WC spült schlecht: Spülmenge zu klein oder Spülrohr/Manschette undicht'],
    normen: ['DIN EN 997', 'DIN EN 14688 (Waschtisch)', 'DIN EN 14516 (Wanne)', 'DIN 18534', 'DIN 18040-2'],
    verwandt: ['vorwandinstallation', 'sanitaerarmaturen', 'geruchsverschluss', 'barrierefrei'],
  },
  {
    id: 'barrierefrei',
    begriff: 'Barrierefreies Bad',
    bereich: 'sanitaer',
    kategorie: 'Regelwerk',
    synonyme: ['DIN 18040', 'behindertengerecht', 'bodengleiche Dusche', 'Stützklappgriff'],
    kurz: 'Barrierefreie Sanitärräume brauchen Bewegungsflächen, angepasste Montagehöhen, bodengleiche Duschen und tragfähige Befestigungen.',
    funktion:
      'DIN 18040-2 unterscheidet barrierefrei und uneingeschränkt mit dem Rollstuhl nutzbar (R-Anforderungen). Entscheidend sind Bewegungsflächen vor den Objekten, seitliche Anfahrbarkeit des WCs, unterfahrbare Waschtische, bodengleiche Duschen ohne Schwelle und tragfähige Wandkonstruktionen für Stützklappgriffe.',
    aufbau: ['Bewegungsfläche 120 x 120 cm, mit Rollstuhl 150 x 150 cm', 'WC mit seitlicher Anfahrfläche und Stützklappgriffen', 'Unterfahrbarer Waschtisch mit Unterputzsiphon', 'Bodengleiche Dusche mit rutschhemmendem Belag und Duschklappsitz'],
    einsatz: ['Öffentliche Gebäude', 'Pflege- und Seniorenwohnungen', 'Privates altersgerechtes Umbauen (Förderung möglich)'],
    hinweise: [
      'WC-Sitzhöhe 46 bis 48 cm inklusive Sitz; Stützklappgriffe 28 cm über dem Sitz, 15 cm über die Vorderkante hinausragend.',
      'Waschtisch Oberkante maximal 80 cm, Unterfahrbarkeit mindestens 67 cm Höhe.',
      'Armaturen als Einhebel- oder berührungslose Ausführung mit Verbrühschutz.',
      'Tragfähigkeit der Vorwand für Stützgriffe prüfen (Mindestlast meist 1 kN).',
    ],
    normen: ['DIN 18040-1 und -2', 'DIN 18534', 'VDI 6000'],
    verwandt: ['sanitaerobjekte', 'vorwandinstallation'],
  },
  {
    id: 'leckage',
    begriff: 'Leckagesuche und Leckageschutz',
    bereich: 'sanitaer',
    kategorie: 'Verfahren',
    synonyme: ['Wasserschaden', 'Leck', 'Leckortung', 'Leckageschutz', 'undicht'],
    kurz: 'Unbemerkte Leckagen verursachen große Schäden; zur Ortung dienen Zählerbeobachtung, Druckabfallprüfung und akustische oder thermografische Verfahren.',
    funktion:
      'Erster Schritt ist immer die Eingrenzung: Alle Entnahmestellen schließen und den Wasserzähler beobachten. Dreht er weiter, liegt eine Leckage im Netz. Abschnittsweises Absperren grenzt ein. Zur genauen Ortung dienen Korrelations- und Geräuschmessung, Tracergas (Wasserstoff-Stickstoff-Gemisch), Thermografie oder Feuchtemessung. Leckageschutzgeräte am Hausanschluss erkennen ungewöhnliche Entnahmemuster und sperren automatisch ab.',
    aufbau: ['Absperrarmaturen zur Abschnittsbildung', 'Manometer für die Druckabfallprüfung', 'Elektroakustik, Tracergas, Thermografie, Feuchtemessgerät', 'Leckageschutzgerät mit Absperrventil'],
    einsatz: ['Ungeklärter Wasserverbrauch', 'Feuchteschäden an Wand und Decke', 'Vorbeugend in Objekten mit längerem Leerstand'],
    hinweise: [
      'Zählerstand über Nacht ablesen – das ist der einfachste und günstigste Test.',
      'Versicherung frühzeitig einbinden und Schaden dokumentieren (Fotos, Protokolle).',
      'Nach der Reparatur trocknen lassen und Ursache dokumentieren.',
    ],
    normen: ['DIN 1988-200', 'VDI 6003', 'DIN EN 806-5'],
    verwandt: ['wasserzaehler', 'dichtheitspruefung', 'korrosion'],
  },
];
