/**
 * Fachdatenbank – Versorgungs- und Anlagentechnik:
 * Fernwärme, Druckerhöhung, Betriebswasser, Druckluft, Mess- und Regeltechnik,
 * Abscheideranlagen, Instandhaltung, Recht und Dokumentation.
 */

export const VERSORGUNG = [
  {
    id: 'fernwaerme',
    begriff: 'Fernwärme und Hausübergabestation',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Nahwärme', 'Wärmenetz', 'Übergabestation', 'Hausstation', 'Fernwärmeanschluss'],
    kurz: 'Fernwärme liefert Heizwärme über ein Wärmenetz; die Hausübergabestation trennt Netz und Hausanlage und regelt die Wärmeabgabe.',
    funktion:
      'Im Primärnetz zirkuliert Heizwasser mit hoher Temperatur. In der Übergabestation überträgt ein Plattenwärmeübertrager die Wärme auf den Sekundärkreis des Gebäudes (indirekter Anschluss); dadurch sind Drücke und Wasserqualität getrennt. Ein Regelventil mit Stellantrieb passt den Primärvolumenstrom an den Bedarf an. Beim direkten Anschluss fließt Netzwasser durch die Hausanlage – das ist nur bei passenden Druck- und Temperaturverhältnissen zulässig.',
    aufbau: [
      'Hausanschluss mit Absperrarmaturen und Schmutzfänger',
      'Wärmemengenzähler mit Volumenmessteil und Temperaturfühlern',
      'Plattenwärmeübertrager für Heizung und ggf. Trinkwassererwärmung',
      'Primärregelventil mit Stellantrieb und Differenzdruckregler',
      'Sekundärseite mit Pumpe, Ausdehnungsgefäß und Sicherheitsventil',
    ],
    einsatz: ['Verdichtete Wohngebiete, Innenstädte', 'Neubaugebiete mit Nahwärmenetz', 'Ersatz von Einzelfeuerstätten'],
    hinweise: [
      'Niedrige Rücklauftemperatur ist der entscheidende Effizienzfaktor – viele Versorger verlangen sie vertraglich und berechnen Zuschläge.',
      'Schmutzfänger regelmäßig reinigen; Verschmutzung ist die häufigste Ursache für Leistungsmangel.',
      'Plattenwärmeübertrager bei hartem Wasser regelmäßig auf Verkalkung prüfen.',
      'Arbeiten an der Primärseite nur nach Freigabe des Versorgers.',
    ],
    werte: [
      'Vorlauftemperatur Primärnetz: 70 bis 130 °C je nach Netz und Jahreszeit',
      'Geforderte Rücklauftemperatur: häufig unter 50 °C, in Niedertemperaturnetzen deutlich darunter',
      'Übergabeleistung Einfamilienhaus: typisch 10 bis 20 kW',
    ],
    normen: ['AGFW FW 515', 'DIN EN 14419', 'DIN 4747', 'AVBFernwärmeV'],
    verwandt: ['waermemengenzaehler', 'heizungsanlage', 'trinkwassererwaermer', 'mess_regeltechnik'],
  },
  {
    id: 'druckerhoehungsanlage',
    begriff: 'Druckerhöhungsanlage (DEA)',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['DEA', 'Druckerhöhung', 'Hauswasserwerk', 'Druckboosteranlage'],
    kurz: 'Reicht der Versorgungsdruck nicht bis zur obersten Entnahmestelle, erhöht eine Druckerhöhungsanlage den Druck im Gebäude.',
    funktion:
      'Mehrere drehzahlgeregelte Pumpen arbeiten parallel und halten über einen Drucksensor den eingestellten Ausgangsdruck konstant. Ein kleiner Membranbehälter dämpft Druckschwankungen und verhindert ständiges Schalten bei Kleinstentnahmen. Die Anlage wird entweder direkt an das Netz angeschlossen (nur mit Zustimmung des Versorgers und Zulaufdrucküberwachung) oder über einen Vorbehälter mit freiem Auslauf gespeist.',
    aufbau: [
      'Pumpengruppe mit Frequenzumrichter',
      'Membrandruckbehälter',
      'Drucksensor, Manometer, Trockenlaufschutz',
      'Schaltschrank mit Pumpenwechselautomatik',
      'ggf. Vorbehälter mit Sicherungsarmatur',
    ],
    einsatz: ['Hochhäuser und mehrgeschossige Gebäude', 'Löschwasseranlagen', 'Objekte mit schwankendem Netzdruck'],
    hinweise: [
      'Anlage so klein wie möglich dimensionieren – überdimensionierte DEA takten und verursachen Druckschläge.',
      'Hygiene beachten: Behälter regelmäßig reinigen, Stagnation vermeiden, geeignete Werkstoffe verwenden.',
      'Zulaufdruckschalter schützt das Versorgungsnetz vor Unterdruck.',
      'Körperschallentkopplung vorsehen (elastische Kompensatoren, Schwingungsdämpfer).',
    ],
    werte: [
      'Mindestfließdruck an der obersten Entnahmestelle: 1,0 bar',
      'Druckbedarf: etwa 0,1 bar je Meter Höhenunterschied plus Leitungs- und Armaturenverluste',
      'Zulässiger Ruhedruck in der Installation: 5 bar (sonst Druckminderer)',
    ],
    formeln: [
      { name: 'Erforderlicher Pumpendruck', formel: 'p_Pumpe = p_geo + Σ(R·l + Z) + p_Arm + p_minFl − p_Zulauf', erklaerung: 'Alle Anteile in bar; p_geo = 0,1 bar je Meter Höhe.' },
    ],
    normen: ['DIN 1988-500', 'DIN EN 806-2', 'DVGW W 557'],
    verwandt: ['rohrnetzberechnung', 'druckminderer', 'trinkwasserhygiene', 'loeschwasser'],
  },
  {
    id: 'regenwassernutzung',
    begriff: 'Regenwassernutzung und Betriebswasser',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Regenwasseranlage', 'Zisterne', 'Betriebswasser', 'Grauwasser', 'Brauchwasser'],
    kurz: 'Regenwasser kann für WC-Spülung, Waschmaschine und Gartenbewässerung genutzt werden – streng getrennt vom Trinkwassernetz.',
    funktion:
      'Das Regenwasser von Dachflächen läuft über einen Filter in die Zisterne, wird dort beruhigt zugeführt und über eine schwimmende Entnahme mit einer Pumpe ins Betriebswassernetz gefördert. Bleibt der Zulauf aus, speist eine Trinkwassernachspeisung über einen freien Auslauf nach – nur so ist eine Rückwirkung auf das Trinkwasser sicher ausgeschlossen. Betriebswasserleitungen müssen dauerhaft gekennzeichnet sein.',
    aufbau: [
      'Zisterne mit beruhigtem Zulauf, Überlauf mit Geruchverschluss und Rückstausicherung',
      'Filter (Vor- oder Nachfilter)',
      'Tauchpumpe oder Saugpumpe mit schwimmender Entnahme',
      'Steuerung mit Trinkwassernachspeisung über freien Auslauf (AA oder AB)',
      'Kennzeichnung aller Leitungen und Entnahmestellen „Kein Trinkwasser“',
    ],
    einsatz: ['WC-Spülung, Waschmaschine, Gartenbewässerung, Reinigungszwecke'],
    hinweise: [
      'Niemals eine direkte Verbindung zum Trinkwassernetz herstellen – auch nicht „nur zum Nachfüllen“.',
      'Entnahmestellen abschließbar oder ohne Schlauchanschluss ausführen, damit keine Verwechslung möglich ist.',
      'Anlage beim Gesundheitsamt bzw. Wasserversorger anzeigen (regional geregelt).',
      'Filter und Zisterne regelmäßig kontrollieren und reinigen.',
    ],
    werte: [
      'Ertrag: Dachfläche x Jahresniederschlag x Abflussbeiwert (Ziegeldach etwa 0,8) x Filterwirkungsgrad (0,9)',
      'Zisternengröße Richtwert: etwa 5 % des Jahresertrags bzw. 1 m³ je 25 m² Dachfläche',
      'Betriebswasserbedarf: WC-Spülung etwa 30 l je Person und Tag',
    ],
    normen: ['DIN 1989-100', 'DIN EN 16941-1', 'DIN EN 1717', 'Trinkwasserverordnung'],
    verwandt: ['sicherungsarmaturen', 'regenentwaesserung', 'trinkwasserhygiene'],
  },
  {
    id: 'druckluft',
    begriff: 'Druckluftanlagen',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Kompressor', 'Druckluftnetz', 'Drucklufttrockner', 'Kondensatableiter'],
    kurz: 'Druckluft ist ein teures Betriebsmittel; Erzeugung, Aufbereitung, Verteilung und Dichtheit bestimmen die Kosten.',
    funktion:
      'Der Kompressor verdichtet Umgebungsluft; dabei steigt die Temperatur und die Luft wird bezogen auf ihren Druck übersättigt. Nach dem Nachkühler fällt Kondensat an und wird abgeschieden. Der Kältetrockner kühlt die Luft weiter ab, damit der Drucktaupunkt unter der niedrigsten Umgebungstemperatur des Netzes liegt – sonst fällt im Rohrnetz Wasser aus. Filter entfernen Öl und Partikel. Im Netz kosten Leckagen dauerhaft Energie.',
    aufbau: [
      'Kompressor (Schrauben- oder Kolbenverdichter) mit Nachkühler',
      'Druckluftbehälter als Puffer',
      'Kältetrockner oder Adsorptionstrockner',
      'Filterstufen und Kondensatableiter mit Öl-Wasser-Trenner',
      'Ringleitung mit Gefälle und Abgängen von oben',
    ],
    einsatz: ['Werkstätten und Produktion', 'Steuerluft in der Gebäudeautomation', 'Sanitär- und Heizungsbau (Werkzeuge, Prüfungen)'],
    hinweise: [
      'Netzdruck so niedrig wie möglich halten: 1 bar weniger spart etwa 6 bis 7 % Antriebsenergie.',
      'Leckagen systematisch suchen – in vielen Betrieben gehen 20 bis 30 % der erzeugten Luft verloren.',
      'Abgänge von oben abzweigen, damit kein Kondensat mitgerissen wird; Leitungen mit Gefälle verlegen.',
      'Kondensat ist ölhaltig und muss über einen Öl-Wasser-Trenner entsorgt werden.',
      'Druckbehälter unterliegen der Betriebssicherheitsverordnung – Prüffristen beachten.',
    ],
    werte: [
      'Üblicher Netzdruck: 6 bis 8 bar',
      'Drucktaupunkt Kältetrockner: etwa +3 °C',
      'Energiebedarf: etwa 0,1 kWh je m³ Druckluft bei 7 bar',
      'Reinheitsklassen nach ISO 8573-1 (Partikel, Wasser, Öl)',
    ],
    normen: ['ISO 8573-1', 'BetrSichV', 'DIN EN 1012'],
    verwandt: ['c_stahlrohr', 'pressverbindung', 'mess_regeltechnik'],
  },
  {
    id: 'mess_regeltechnik',
    begriff: 'Mess-, Steuer- und Regelungstechnik (MSR)',
    bereich: 'versorgung',
    kategorie: 'Grundlagen',
    synonyme: ['MSR', 'Regelungstechnik', 'GLT', 'Gebäudeautomation', 'Fühler', 'Stellantrieb'],
    kurz: 'MSR-Technik erfasst Messwerte, vergleicht sie mit Sollwerten und stellt über Aktoren den gewünschten Zustand ein.',
    funktion:
      'Im Regelkreis misst ein Fühler die Regelgröße (z. B. Vorlauftemperatur), der Regler vergleicht sie mit dem Sollwert und berechnet die Stellgröße, die ein Aktor (Ventil, Pumpe, Klappe) umsetzt. Bei einer Steuerung fehlt diese Rückführung. Übliche Regelalgorithmen sind P, PI und PID: Der P-Anteil reagiert proportional auf die Abweichung, der I-Anteil beseitigt die bleibende Regelabweichung, der D-Anteil reagiert auf Änderungsgeschwindigkeit.',
    aufbau: [
      'Fühler: Pt1000/Pt100, NTC, Druck-, Volumenstrom-, CO₂- und Feuchtefühler',
      'Regler bzw. DDC-Station mit Zeitprogramm',
      'Aktoren: Stellantriebe, Frequenzumrichter, Magnetventile',
      'Bussysteme: KNX, Modbus, BACnet, M-Bus',
      'Gebäudeleittechnik mit Visualisierung, Trend und Störmeldung',
    ],
    einsatz: ['Heizungs- und Lüftungsregelung', 'Fernüberwachung und Störmeldung', 'Energiemonitoring und Betriebsoptimierung'],
    hinweise: [
      'Fühler richtig platzieren – ein falsch sitzender Fühler macht jede Regelung unbrauchbar (Tauchhülse mit Wärmeleitpaste, Außenfühler nach Norden).',
      'Regelparameter zur Trägheit der Strecke passen: träge Strecken (Fußbodenheizung) brauchen langsame Regelung.',
      'Funktionsbeschreibung und Schaltpläne der Dokumentation beilegen.',
      'Störmeldungen sinnvoll priorisieren, damit wichtige Meldungen nicht untergehen.',
    ],
    werte: ['Pt1000: 1000 Ω bei 0 °C, etwa +3,85 Ω je Kelvin', 'Analogsignale: 0–10 V, 4–20 mA', 'Stellantrieb-Laufzeiten: 30 bis 240 s je nach Anwendung'],
    normen: ['VDI 3814', 'DIN EN ISO 16484', 'DIN EN 15500', 'GEG (Gebäudeautomation)'],
    verwandt: ['heizkurve', 'rlt_anlage', 'elektro_grundlagen', 'fernwaerme'],
  },
  {
    id: 'waermemengenzaehler',
    begriff: 'Wärmemengenzähler und Verbrauchserfassung',
    bereich: 'versorgung',
    kategorie: 'Bauteil',
    synonyme: ['Wärmezähler', 'WMZ', 'Heizkostenverteiler', 'Verbrauchserfassung', 'Zählerfernauslesung'],
    kurz: 'Der Wärmemengenzähler bestimmt die gelieferte Wärme aus Volumenstrom und Temperaturdifferenz zwischen Vor- und Rücklauf.',
    funktion:
      'Das Volumenmessteil misst den Durchfluss, zwei gepaarte Temperaturfühler erfassen Vor- und Rücklauftemperatur. Das Rechenwerk multipliziert Volumen, Temperaturdifferenz und die Wärmekapazität des Wassers und summiert die Energie. Heizkostenverteiler an Heizkörpern messen dagegen keine Energie, sondern eine relative Größe aus Heizkörpertemperatur und Zeit; die Verteilung erfolgt über Bewertungsfaktoren.',
    aufbau: ['Volumenmessteil (Flügelrad oder Ultraschall)', 'gepaarte Temperaturfühler mit Tauchhülsen', 'Rechenwerk mit Anzeige und Schnittstelle', 'Funk- oder M-Bus-Auslesung'],
    einsatz: ['Fernwärmeübergabe', 'Wohnungsweise Abrechnung', 'Energiemonitoring von Anlagenteilen'],
    hinweise: [
      'Einbaurichtung und Einbauort (Vor- oder Rücklauf) nach Typenschild beachten; Fühler nicht vertauschen.',
      'Beruhigungsstrecken vor und hinter dem Messteil einhalten.',
      'Eichfrist für Wärmezähler in der Regel 5 Jahre – rechtzeitig tauschen oder beglaubigen lassen.',
      'Heizkostenverordnung: Abrechnung mit 50 bis 70 % verbrauchsabhängigem Anteil; fernauslesbare Geräte müssen monatliche Verbrauchsinformationen liefern.',
    ],
    werte: ['Eichfrist Wärmezähler 5 Jahre', 'Messgenauigkeitsklassen 1 bis 3 nach MID', 'Verbrauchsanteil nach HeizkostenV: 50 bis 70 %'],
    formeln: [
      { name: 'Wärmemenge', formel: 'Q = V · ρ · c · ΔT', erklaerung: 'Mit Wasser vereinfacht: Q [kWh] = V [m³] · 1,163 · ΔT [K].' },
    ],
    normen: ['DIN EN 1434', 'MessEG/MessEV', 'Heizkostenverordnung', 'AVBFernwärmeV'],
    verwandt: ['fernwaerme', 'mess_regeltechnik', 'wasserzaehler'],
  },
  {
    id: 'fettabscheider',
    begriff: 'Fettabscheideranlage',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Fettabscheider', 'Küchenabwasser', 'DIN 4040', 'Abscheider Gastronomie'],
    kurz: 'Fettabscheider halten pflanzliche und tierische Fette aus dem Abwasser zurück, damit sie die Kanalisation nicht zusetzen.',
    funktion:
      'Das Abwasser durchläuft einen Schlammfang, in dem sich Feststoffe absetzen, und anschließend den Abscheideraum. Weil Fett leichter als Wasser ist, steigt es dort auf und bildet eine Schicht an der Oberfläche. Das gereinigte Wasser wird unterhalb dieser Schicht abgezogen. Die Wirkung beruht allein auf dem Dichteunterschied, daher darf das Abwasser nicht emulgiert sein – Hochdruckreiniger und bestimmte Reinigungsmittel zerstören die Trennwirkung.',
    aufbau: ['Schlammfang', 'Abscheideraum mit Fettschicht', 'Probenahmeschacht', 'Direktabsaugleitung für die Entsorgung', 'Füllstands- und Schichtdickenmelder'],
    einsatz: ['Gastronomie und Großküchen', 'Metzgereien, Bäckereien, Lebensmittelbetriebe', 'Kantinen'],
    hinweise: [
      'Entleerung und vollständige Reinigung in der Regel alle 14 Tage; Betriebstagebuch führen.',
      'Monatliche Eigenkontrolle, jährliche Wartung durch Fachkundige, Generalinspektion alle 5 Jahre.',
      'Keine emulgierenden Reinigungsmittel einsetzen – sie führen das Fett durch den Abscheider hindurch.',
      'Nach dem Entleeren wieder mit Wasser befüllen, sonst wirkt der Abscheider nicht.',
    ],
    werte: ['Bemessung nach Nenngröße NS (l/s) aus Abwassermenge, Temperatur und Dichtefaktor', 'Abwassertemperatur möglichst unter 60 °C'],
    normen: ['DIN EN 1825-1/-2', 'DIN 4040-100', 'DIN 1986-100'],
    verwandt: ['abscheideranlagen', 'entwaesserung_grundlagen', 'instandhaltung'],
  },
  {
    id: 'abscheideranlagen',
    begriff: 'Leichtflüssigkeits- und Sonderabscheider',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Ölabscheider', 'Benzinabscheider', 'Koaleszenzabscheider', 'Amalgamabscheider', 'DIN 1999'],
    kurz: 'Leichtflüssigkeitsabscheider trennen Öl und Benzin vom Abwasser; Sonderabscheider erfassen weitere Stoffe wie Amalgam oder Stärke.',
    funktion:
      'Wie beim Fettabscheider nutzt man den Dichteunterschied: Leichtflüssigkeiten steigen auf und sammeln sich an der Oberfläche. Koaleszenzeinsätze lassen feinste Tröpfchen zu größeren zusammenfließen und verbessern die Abscheideleistung deutlich. Ein selbsttätiger Abschluss (Schwimmer) verschließt den Ablauf, sobald die maximale Speichermenge erreicht ist, damit kein Öl in den Kanal gelangt.',
    aufbau: ['Schlammfang', 'Abscheider mit Koaleszenzeinsatz', 'Selbsttätiger Abschluss', 'Probenahmeschacht', 'Warnanlage für Schichtdicke und Aufstau'],
    einsatz: ['Werkstätten und Waschplätze', 'Tankstellen und Parkflächen', 'Zahnarztpraxen (Amalgamabscheider)', 'Küchen mit Stärkeabscheider'],
    hinweise: [
      'Betriebstagebuch führen, monatliche Eigenkontrolle, jährliche Wartung, Generalinspektion alle 5 Jahre.',
      'Nach jeder Entleerung Anlage mit Wasser befüllen und Koaleszenzeinsatz reinigen.',
      'Wasserrechtliche Erlaubnis und Zulassung des Abscheidertyps beachten.',
    ],
    normen: ['DIN EN 858-1/-2', 'DIN 1999-100', 'DIN EN 1825', 'AwSV'],
    verwandt: ['fettabscheider', 'entwaesserung_grundlagen', 'instandhaltung'],
  },
  {
    id: 'schwimmbadtechnik',
    begriff: 'Schwimmbadtechnik',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Pool', 'Badewasser', 'Filteranlage Pool', 'DIN 19643', 'Chlorung'],
    kurz: 'Badewasser wird ständig umgewälzt, gefiltert, desinfiziert und im pH-Wert korrigiert; öffentliche Bäder folgen DIN 19643.',
    funktion:
      'Das Wasser wird über Überlaufrinne oder Skimmer abgezogen, im Haarfänger von Grobstoffen befreit und von der Umwälzpumpe durch den Filter gefördert. Flockungsmittel binden feinste Trübstoffe, damit der Filter sie zurückhalten kann. Danach folgen pH-Korrektur und Desinfektion, meist mit Chlor. Das aufbereitete Wasser wird über Einströmdüsen so eingeleitet, dass das gesamte Becken durchströmt wird.',
    aufbau: ['Überlaufrinne/Skimmer und Schwallwasserbehälter', 'Umwälzpumpe mit Haarfänger', 'Sand-, Mehrschicht- oder Kieselgurfilter', 'Dosieranlagen für Flockung, pH und Desinfektion', 'Messtechnik für pH, Redox und freies Chlor', 'Wärmeübertrager zur Beckenwassererwärmung'],
    einsatz: ['Öffentliche Bäder, Hotels, Therapiebäder (DIN 19643)', 'Private Schwimmbäder'],
    hinweise: [
      'Filter regelmäßig rückspülen; Rückspülwasser fachgerecht ableiten.',
      'Beckenwassererwärmer und Rohrleitungen aus beständigen Werkstoffen (chloridhaltiges Wasser greift Standard-Edelstahl an).',
      'Hallenbäder brauchen Entfeuchtung – sonst Tauwasser und Bauschäden.',
      'Dosierchemikalien getrennt lagern: Säure und Chlor niemals zusammenbringen.',
    ],
    werte: [
      'Freies Chlor im Beckenwasser: 0,3 bis 0,6 mg/l (öffentliche Bäder)',
      'pH-Wert: 6,5 bis 7,6',
      'Umwälzung privat: Beckeninhalt etwa 2-mal am Tag; öffentlich nach DIN 19643 deutlich häufiger',
      'Raumluft Hallenbad: Lufttemperatur etwa 2 K über Wassertemperatur, relative Feuchte 50 bis 64 %',
    ],
    normen: ['DIN 19643', 'DIN EN 16713', 'VDI 2089 (Hallenbadlüftung)'],
    verwandt: ['luftzustand', 'rlt_anlage', 'enthaertung'],
  },
  {
    id: 'loeschwasser',
    begriff: 'Löschwasseranlagen',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['Wandhydrant', 'Steigleitung nass', 'Steigleitung trocken', 'Feuerlöschanlage', 'DIN 14462'],
    kurz: 'Löschwasseranlagen stellen Wasser für die Brandbekämpfung bereit; sie sind hygienisch vom Trinkwasser zu trennen.',
    funktion:
      'Nasse Steigleitungen stehen dauerhaft unter Wasser, trockene werden erst von der Feuerwehr eingespeist. Wandhydranten für die Selbsthilfe (Typ S) sind an das Trinkwassernetz angeschlossen und benötigen eine Sicherungseinrichtung, weil stehendes Löschwasser hygienisch kritisch ist – üblich ist eine Systemtrennung über freien Auslauf mit nachgeschalteter Druckerhöhung. Sprinkleranlagen lösen selbsttätig über Glasfässchen aus.',
    aufbau: ['Wandhydrant Typ F (Feuerwehr) oder Typ S (Selbsthilfe)', 'Steigleitung nass, nass/trocken oder trocken', 'Trennstation mit freiem Auslauf und Druckerhöhung', 'Einspeisearmatur für die Feuerwehr'],
    einsatz: ['Hochhäuser, Tiefgaragen, Versammlungsstätten', 'Industriebauten', 'Sonderbauten nach Brandschutzkonzept'],
    hinweise: [
      'Löschwasseranlagen nie ohne Sicherung direkt mit dem Trinkwassernetz verbinden.',
      'Regelmäßige Prüfung nach DIN 14462 und Landesrecht, Dokumentation im Prüfbuch.',
      'Nasse Leitungen brauchen einen bestimmungsgemäßen Wasseraustausch – sonst Verkeimung.',
      'Abstimmung mit Brandschutzkonzept und Feuerwehr zwingend.',
    ],
    normen: ['DIN 14462', 'DIN 1988-600', 'DIN EN 671', 'DIN EN 12845 (Sprinkler)'],
    verwandt: ['sicherungsarmaturen', 'druckerhoehungsanlage', 'trinkwasserhygiene'],
  },
  {
    id: 'instandhaltung',
    begriff: 'Instandhaltung nach DIN 31051',
    bereich: 'versorgung',
    kategorie: 'Verfahren',
    synonyme: ['Wartung', 'Inspektion', 'Instandsetzung', 'Verbesserung', 'Wartungsvertrag'],
    kurz: 'Instandhaltung umfasst vier Grundmaßnahmen: Wartung, Inspektion, Instandsetzung und Verbesserung.',
    funktion:
      'Wartung verzögert den Abbau des Abnutzungsvorrats (Reinigen, Einstellen, Schmieren, Austausch von Verschleißteilen). Die Inspektion stellt den Istzustand fest und bewertet ihn. Die Instandsetzung stellt den Sollzustand wieder her. Die Verbesserung erhöht die Funktionssicherheit, ohne die geforderte Funktion zu ändern. Wartungsverträge legen Umfang, Intervalle, Reaktionszeiten und Dokumentation fest.',
    aufbau: ['Wartungsplan je Anlagenteil', 'Checklisten und Messprotokolle', 'Ersatzteil- und Verschleißteilliste', 'Anlagenbuch mit Historie'],
    einsatz: ['Heizungs-, Lüftungs- und Sanitäranlagen', 'Abscheider, Hebeanlagen, Sicherungsarmaturen', 'Gewerbliche und öffentliche Objekte mit Prüfpflichten'],
    hinweise: [
      'Typische Intervalle: Heizung jährlich · Lüftung je nach VDI 6022 · Sicherungsarmaturen jährlich · Abscheider monatlich/jährlich/5 Jahre · Hebeanlagen je nach Objektart.',
      'Messwerte immer dokumentieren – nur so lassen sich Veränderungen erkennen.',
      'Betreiber über Pflichten informieren (Trinkwasserhygiene, Abscheiderbetrieb, Prüffristen).',
      'Beim Kundendienst: Störungsbild, Ursache, Maßnahme und verwendetes Material festhalten.',
    ],
    normen: ['DIN 31051', 'VDI 6022', 'DIN EN 13306', 'BetrSichV'],
    verwandt: ['dokumentation', 'kundendienst', 'fettabscheider', 'rlt_hygiene'],
  },
  {
    id: 'kundendienst',
    begriff: 'Kundendienst und Störungssuche',
    bereich: 'versorgung',
    kategorie: 'Verfahren',
    synonyme: ['Störung', 'Reparatur', 'Fehlersuche', 'Notdienst', 'Serviceeinsatz'],
    kurz: 'Systematische Fehlersuche spart Zeit: erst Symptom und Betriebszustand erfassen, dann eingrenzen, prüfen und erst danach tauschen.',
    funktion:
      'Bewährt hat sich ein festes Vorgehen: Kundengespräch und Symptombeschreibung, Sichtprüfung, Betriebsdaten ablesen (Druck, Temperaturen, Fehlercode), Versorgung prüfen (Strom, Gas, Wasser), dann funktionsweise eingrenzen und Messungen durchführen. Bauteile werden erst getauscht, wenn ihre Fehlfunktion nachgewiesen ist. Abschließend werden Ursache, Maßnahme und eingebautes Material dokumentiert und der Kunde eingewiesen.',
    aufbau: [
      'Auftragsannahme mit Fehlerbeschreibung und Objektdaten',
      'Messgeräte: Multimeter, Manometer, Thermometer, Abgasmessgerät, CO-Warner',
      'Ersatzteile und Verschleißmaterial',
      'Serviceprotokoll mit Messwerten und Unterschrift',
    ],
    einsatz: ['Heizungsausfall, Wasserschaden, Verstopfung, Geräteausfall', 'Notdienst außerhalb der Geschäftszeit'],
    hinweise: [
      'Sicherheit zuerst: bei Gasgeruch, CO-Verdacht oder Wasser auf elektrischen Anlagen zunächst absichern.',
      'Typische Ursachen zuerst prüfen: Anlagendruck, Luft im System, verschmutzte Filter, blockierte Pumpe, Fehlercode ablesen.',
      'Keine Sicherheitsfunktion überbrücken, um eine Anlage „zum Laufen“ zu bringen.',
      'Kunden über Folgekosten und empfohlene Maßnahmen schriftlich informieren.',
    ],
    normen: ['DIN 31051', 'DGUV Vorschrift 1', 'BGB Werkvertragsrecht'],
    verwandt: ['instandhaltung', 'dokumentation', 'gasgeruch', 'abgasmessung'],
  },
  {
    id: 'dokumentation',
    begriff: 'Dokumentation und Übergabe',
    bereich: 'versorgung',
    kategorie: 'Verfahren',
    synonyme: ['Anlagenbuch', 'Revisionsunterlagen', 'Bestandsdokumentation', 'Übergabeprotokoll', 'Einweisung'],
    kurz: 'Zur vollständigen Leistung gehören Bestandsunterlagen, Protokolle, Betriebsanleitungen und die Einweisung des Betreibers.',
    funktion:
      'Die Dokumentation macht die Anlage nachvollziehbar und wartbar. Dazu gehören Bestandspläne mit tatsächlicher Leitungsführung, Berechnungen, Prüf- und Messprotokolle, Datenblätter der eingebauten Bauteile, Einstellwerte (Abgleich, Heizkurve, Regelparameter) und die Betriebsanleitungen. Ohne Einweisung des Betreibers ist die Übergabe unvollständig – viele Schäden entstehen durch falsche Bedienung.',
    aufbau: [
      'Bestandspläne und Strangschemata',
      'Berechnungen: Heizlast, Rohrnetz, Abgleich, Ausdehnungsgefäß',
      'Protokolle: Dichtheitsprüfung, Spülung, Wasseraufbereitung, Abgasmessung, Aufheizen',
      'Wartungsplan und Betreiberpflichten',
      'Übergabeprotokoll mit Einweisungsnachweis',
    ],
    einsatz: ['Jede Neuanlage und jeder größere Umbau', 'Betrieblicher Auftrag in der Gesellenprüfung', 'Grundlage für spätere Wartung und Erweiterung'],
    hinweise: [
      'Fotos der Leitungsführung vor dem Verschließen anfertigen – später Gold wert.',
      'Einstellwerte an Ort und Stelle markieren (Ventile, Regler).',
      'Digitale Ablage mit Objektbezug erleichtert den Kundendienst.',
      'Im Berichtsheft und Fachbericht gehört die Dokumentation als eigener Arbeitsschritt beschrieben.',
    ],
    normen: ['VOB/C DIN 18380 und 18381', 'VDI 6039 (Inbetriebnahmemanagement)', 'DIN EN 12828'],
    verwandt: ['inbetriebnahme', 'instandhaltung', 'gesellenpruefung', 'berichtsheft_wissen'],
  },
  {
    id: 'geg_recht',
    begriff: 'GEG, Förderung und Wärmeplanung',
    bereich: 'versorgung',
    kategorie: 'Regelwerk',
    synonyme: ['Gebäudeenergiegesetz', 'Heizungsgesetz', '65 Prozent', 'BEG', 'Förderung', 'Energieausweis'],
    kurz: 'Das Gebäudeenergiegesetz regelt energetische Anforderungen an Gebäude und Anlagentechnik, einschließlich der Anforderungen an neue Heizungen.',
    funktion:
      'Das GEG fasst Anforderungen an Wärmeschutz und Anlagentechnik zusammen. Für neu eingebaute Heizungen gilt die Anforderung, dass sie einen Mindestanteil erneuerbarer Energien nutzen; die Fristen für Bestandsgebäude sind an die kommunale Wärmeplanung gekoppelt. Daneben bestehen Nachrüst- und Betreiberpflichten: Dämmung zugänglicher Verteilleitungen, Dämmung der obersten Geschossdecke, Austauschpflicht für alte Konstanttemperaturkessel sowie Prüf- und Optimierungspflichten für Heizungsanlagen. Maßnahmen werden über die Bundesförderung für effiziente Gebäude (BEG) gefördert.',
    aufbau: [
      'Anforderungen an den baulichen Wärmeschutz',
      'Anforderungen an Anlagentechnik und Dämmung von Leitungen',
      'Anteil erneuerbarer Energien bei neuen Heizungen',
      'Betriebs-, Prüf- und Optimierungspflichten',
      'Energieausweis und Beratungspflichten',
    ],
    einsatz: ['Neubau und Sanierung', 'Heizungstausch', 'Beratung von Kunden zu Förderung und Pflichten'],
    hinweise: [
      'Konkrete Fristen und Fördersätze ändern sich – vor der Beratung immer den aktuellen Stand prüfen (BAFA/KfW, Landesrecht, kommunale Wärmeplanung).',
      'Förderanträge in der Regel vor Auftragsvergabe bzw. mit Vorhabenbeginn-Vorbehalt stellen.',
      'Der hydraulische Abgleich ist regelmäßig Fördervoraussetzung und wird mit Protokoll nachgewiesen.',
      'Kunden auf Nachrüst- und Betreiberpflichten hinweisen und dies dokumentieren.',
    ],
    normen: ['GEG', 'BEG-Förderrichtlinien', 'Wärmeplanungsgesetz', 'EnSimiMaV (Prüf- und Optimierungspflichten)'],
    verwandt: ['heizungsoptimierung', 'daemmung_geg', 'hydraulischer_abgleich', 'waermepumpe'],
  },
  {
    id: 'sektorenkopplung',
    begriff: 'Photovoltaik, Speicher und Wärmepumpe',
    bereich: 'versorgung',
    kategorie: 'Anlage',
    synonyme: ['PV', 'Photovoltaik', 'Stromspeicher', 'Eigenverbrauch', 'Sektorenkopplung', 'Smart Grid'],
    kurz: 'Die Kombination aus Photovoltaik, Speicher und Wärmepumpe erhöht den Eigenverbrauch und senkt die Betriebskosten der Wärmeerzeugung.',
    funktion:
      'Die Photovoltaikanlage erzeugt Strom, der zunächst im Gebäude verbraucht wird. Ein Energiemanagementsystem erkennt Überschüsse und startet damit bevorzugt die Wärmepumpe oder die Trinkwassererwärmung – die Wärme wird im Speicher zwischengelagert. Ein Batteriespeicher verschiebt zusätzlich Strom in die Abendstunden. Über die SG-Ready-Schnittstelle lässt sich die Wärmepumpe in vier Betriebszuständen ansteuern.',
    aufbau: ['PV-Generator mit Wechselrichter', 'Energiemanagementsystem mit Messung am Netzanschluss', 'Wärmepumpe mit SG-Ready-Eingang', 'Warmwasser- und Pufferspeicher als thermischer Speicher', 'optional Batteriespeicher und Wallbox'],
    einsatz: ['Einfamilienhäuser mit Wärmepumpe', 'Gewerbeobjekte mit Tagesverbrauch', 'Neubau mit Effizienzstandard'],
    hinweise: [
      'Thermische Speicher sind deutlich günstiger als Batteriespeicher – Überschüsse zuerst in Wärme umwandeln.',
      'Speichertemperatur nur so weit anheben, wie die Wärmepumpe effizient arbeitet.',
      'Elektrische Arbeiten an PV und Netzanschluss gehören zur Elektrofachkraft; die Einbindung der Wärmeerzeugung ist SHK-Aufgabe.',
      'Netzbetreiber-Anmeldung und Zählerkonzept frühzeitig klären.',
    ],
    werte: ['PV-Ertrag in Deutschland: etwa 900 bis 1100 kWh je kWp und Jahr', 'Eigenverbrauchsanteil ohne Speicher 25 bis 35 %, mit Speicher und Wärmepumpe 50 bis 70 %'],
    normen: ['VDE-AR-N 4105', 'DIN EN 50549', 'SG Ready (Label des Bundesverbands Wärmepumpe)'],
    verwandt: ['waermepumpe', 'pufferspeicher', 'mess_regeltechnik', 'elektro_grundlagen'],
  },
];
